### ISSUE TITLE
Update FIA links

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1002]
It's that time of year again where FIA puts out a new release and moves things around. See https://github.com/weecology/retriever/issues/865#issuecomment-325588307

We need to track down the most recent links and update the script.

Thanks to @nestorperez for reporting this.

**Comment by nestorperez** [comment]
Thanks to the entire Retriever's team for making available this quite useful package.

**Comment by henrykironde** [comment]
@nestorperez, we have updated the links to match the new links from FIA. Thank you for reporting this.
In case you are using mac please read the comments in #1004

**Comment by nestorperez** [comment]
Thanks again @henrykironde

**Comment by ethanwhite** [comment]
For anyone else landing here: you'll need to update the retriever scripts using:

```
retriever update
```

And then everything should work.
