### ISSUE TITLE
Predicts data failing, looks like it is due to new updates

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1006]
It does look like the data has changed.
The two attributes are missing, [N_samples](https://github.com/weecology/retriever/blob/master/scripts/predicts.py#L94) and [Higher_taxa](https://github.com/weecology/retriever/blob/master/scripts/predicts.py#L111).

On the main website it says, "You are viewing a beta release of the Natural History Museum's Data Portal." http://data.nhm.ac.uk/dataset
I think this has nothing to do with the data
ref: #792

**Comment by ethanwhite** [comment]
Predicts is installing properly on `master`.
