### ISSUE TITLE
Create a format for testing builds

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1012]
The scripts `build_win`, `build_mac`, `build.sh`, `retriever_installer.iss`, `pyinstaller.spec` are used when creating a new release. We need to find a mechanism to automatically test these function so that they are always up to date

**Comment by shreyneil** [comment]
Sir , just give me heads up on how to proceed.
Thank you.

**Comment by shreyneil** [comment]
I was thinking of making a shell script for formating the builds. Any ideas on how to run the .iss file.

**Comment by henrykironde** [comment]
Since we moved away from builds, we are closing the issue
