### ISSUE TITLE
Add `fetch` to Python interface

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1019]
In the R package we have a `fetch` function which downloads a dataset as csv and then loads it into a list of data frames (one per table). We should add the same function to the Python interface. The default format for fetching should be a pandas data frame, but it might also be worth having some other optional formats (e.g., a numpy structured array).

**Comment by henrykironde** [comment]
Just wondering which one would serve better in terms of memory.

**Comment by ethanwhite** [comment]
Which input format (pandas vs. numpy) or something else? I think most folks will want the Pandas dataframe as the default, but once the basics are implemented I could definitely see adding some options for larger datasets that store the data in an SQL database or HDF5 so that they can be worked with on disk. We could also start to implement fine tuning based on types (e.g., https://www.dataquest.io/blog/pandas-big-data/).

**Comment by zhangcandrew** [comment]
Pandas seems to have the ability to[ download a csv file directly from a url into a dataframe ](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html), and numpy supports [similar functionality when used with urllib](https://machinelearningmastery.com/load-machine-learning-data-python/). Which I think makes this a lot easier for us.

 When fetching the data, do we want our fetch to download a local copy of the csv file?

**Comment by ethanwhite** [comment]
Because we want to take advantage of all of the cleaning code I think we probably want to use either `install_csv` to create a set of csv's and then load them or `install_sqlite` to create an SQLite file and then load all of the tables from it. Using SQLite would be a little more complicated up front because we'd have to write the code to look up the table names and then load them, but it might also be simpler in the long run since it would be an easier change to keep the data in the database instead of pulling it into memory.

Here's what we do in R (which uses csv not SQLite):
https://github.com/ropensci/rdataretriever/blob/master/R/rdataretriever.R#L72

**Comment by adhaamehab** [comment]
Hi @ethanwhite @henrykironde @zhangcandrew 
I'll work on this issue.
Any example test or advice to start working on it ?

**Comment by henrykironde** [comment]
This should be worked on after the PR #1042 . 
It will be much simpler. 

The mail goal is to use the python interface to load the dataset into a data frame like Pandas
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html
http://www.datacarpentry.org/python-ecology-lesson/08-working-with-sql/

The retriever has several engines. We want to use the SQlite(prefered) or CSV engine to download a dataset and then use panda to to load it.

**Comment by adhaamehab** [comment]
Hi @henrykironde 
as PR #1042  is now merged could I work on this issue now ?

**Comment by henrykironde** [comment]
@adhaamehab yes sure

**Comment by adhaamehab** [comment]
Great. I will work on it.

**Comment by ethanwhite** [comment]
Implemented in f7dc96c22c80982cec81c86268e87c5ad76a6669. Thanks again @adhaamehab!
