### ISSUE TITLE
Improve OS X installer

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1028]
There are a number of suggestions for improving the OS X installer (thanks @davharris!). This is basically one chunk of work for someone who knows something about packaging in OS X, so I'm going combine them together here:

1. Double clicking on the app should give users information (#1015 & #802). Right now, double-clicking the icon like a normal app causes it to load and then silently quit without any indication of what's wrong (at least on Mac). If clicking the app would bring up the information about "Method 2: Installers" from http://www.data-retriever.org/, I think that would make things a lot less mysterious for users that download binaries.
2. Alterantively turn the installer into a `dmg` (#802)
3. Sign the OS X binaries (#390). Double-clicking the app icon, gives a warning about the program having been compiled by an “unidentified developer”. Most users won’t know how to bypass this. Apple describes how to sign the code to avoid this error on this page: https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/DistributingApplicationsOutside/DistributingApplicationsOutside.html

I think the best solution here is probably a signed `dmg`. A build script for this would be a great contribution from someone with experience with OS X packaging.

**Comment by ss-is-master-chief** [comment]
@ethanwhite Want me to look into this?

**Comment by ethanwhite** [comment]
My general feeling at the moment is that we should be moving away from packaged installers and towards providing simple clear instructions for installing Python and the package. We've generally been heading in that direction and if that's the approach I don't think we should spend any more time fine tuning the installers. What do you think @henrykironde (and others)?

**Comment by henrykironde** [comment]
Yes I think source code package managers are a way to go. Easy to support and work with.
`I don't think we should spend any more time fine tuning the installers.`, I think this is a good idea, But I am also open to what others think.

**Comment by ethanwhite** [comment]
OK, given that lack of any protest I'm going to go ahead and close this issue and we will prioritize good documentation for installing Python packages over further improvements to the standalone installers.
