### ISSUE TITLE
There should be a separate command to get the description of a dataset

### ISSUE THREAD

**Issue by apoorvaeternity** [weecology/retriever#1038]
Currently the description of a database appears under the `citation` command.
```
retriever citation mammal-life-hist 

Dataset:  mammal-life-hist
Citation:   S. K. Morgan Ernest. 2003. Life history characteristics of placental non-volant mammals. Ecology 84:3402.
Description:   The purpose of this data set was to compile general life history characteristics for a variety of mammalian species to perform comparative life history analyses among different taxa and different body size groups.
```

IMO there should be a separate command for getting the description of the dataset.
Something like 

```
retriever description mammal-life-hist 

Dataset:  mammal-life-hist
Description:   The purpose of this data set was to compile general life history characteristics for a variety of mammalian species to perform comparative life history analyses among different taxa and different body size groups.
```

@ethanwhite @henrykironde Your thoughts on this?

**Comment by ss-is-master-chief** [comment]
@ethanwhite @henrykironde 
Even though a CLI command like `retriever description <data-set-name>` could be implemented, it would function so as to just not fetch meta-data regarding i.e. `Citation` for the data-set in spotlight.

`retriever citation <data-set-name>` gives us all the details in one single go. @apoorvaeternity It would be great if you could elaborate on why `description` would be fundamentally useful. If so, we may start working on it in no time.

**Comment by apoorvaeternity** [comment]
@ss-is-master-chief A `citation` is the way you tell that certain material in your work came from another source and you also give information necessary to find that source again. 
A `description` is something that tells you what something  is like.

As a user when I fetched the dataset list from retriever I wanted to get the details of a particular dataset that what kind of data it contains. Though generally we don't want to add too many commands. `description` seems a more appropriate term for that as I was searching for it. IMO it would be better to add a `description` command.

**Comment by apoorvaeternity** [comment]
@ss-is-master-chief Yeah just now I was thinking the same. We can have `citation` renamed to `description`

**Comment by henrykironde** [comment]
Thank you guys for this great discussion. I personally don't want several commands, however, I will discus with the team and get back to you.

**Comment by ss-is-master-chief** [comment]
@henrykironde That would be great Sir.

**Comment by apoorvaeternity** [comment]
@ethanwhite Okay! I think we can close this issue then.

**Comment by ethanwhite** [comment]
Thanks @apoorvaeternity! I hope that life is treating you well.
