### ISSUE TITLE
DOCS : A more comprehensive documentation for Data Retriever using Python

### ISSUE THREAD

**Issue by ss-is-master-chief** [weecology/retriever#1053]
The [Data Retriever using Python ](https://retriever.readthedocs.io/en/latest/pyretriever.html#) page needs a bit of updation. The CLI documentation is a work in progress but for users like me who would like to interface with Data-Retriever using Python, the document could do better maybe.

@ethanwhite @henrykironde Should I go ahead and start working on the documentation?

**Comment by henrykironde** [comment]
@ss-is-master-chief, that would be great.

**Comment by ethanwhite** [comment]
Fixed in several commits by @ss-is-master-chief. Thanks @ss-is-master-chief!

**Comment by ss-is-master-chief** [comment]
@ethanwhite Thank you
