### ISSUE TITLE
Failing Travis CI tests

### ISSUE THREAD

**Issue by ss-is-master-chief** [weecology/retriever#1056]
I wrote a simple JSON file to an exiting Python Script and issued a PR for it. Upon running the tests, the log stated stated `test/test_json.py::test_valid_json **FAILED**`.

Here is the JSON script

`{
  "citation": "Myhrvold, N.P., Baldridge, E., Chan, B., Sivam, D., Freeman, D.L. and Ernest, S.M., 2015. An amniote life-history database to perform comparative analyses with birds, mammals, and reptiles:Ecological Archives E096-269. Ecology, 96(11), pp.3109-000.",
  "description": "Compilation of life history traits for birds, mammals, and reptiles.",
  "homepage": "https://figshare.com/collections/An_amniote_life-history_database_to_perform_comparative_analyses_with_birds_mammals_and_reptiles/3308127",
  "keywords": [
    "mammals",
    "literature-compilation"
  ],
  "name": "amniote-life-hist",
  "licenses": [{"name": "CC0-1.0"}],
  "resources": [
      {
          "dialect": {},
          "name": "data",
          "schema": {},
          "url": "https://ndownloader.figshare.com/files/8067269"
      }
  ],
  "retriever": "True",
  "retriever_minimum_version": "2.0.dev",
  "title": "Amniote life History database",
  "urls": {
      "data": "https://ndownloader.figshare.com/files/8067269"
  },
  "version": "2.0.2"
}`

@ethanwhite @henrykironde Please have a look.

**Comment by apoorvaeternity** [comment]
@ss-is-master-chief Did you mention the json file in `version.txt`?

**Comment by ss-is-master-chief** [comment]
@apoorvaeternity Worked like a charm. Thank you so much. May I know why mentioning the file to the `version.txt` facilitates Travis CI to validate the JSON validity tests?

**Comment by ss-is-master-chief** [comment]
#1057 `aquatic_animal_excretion.json` shows a **FAILED** JSON Validation Case as well. @apoorvaeternity Please look into it.
