### ISSUE TITLE
retriever/lib/repository.py

### ISSUE THREAD

**Issue by ss-is-master-chief** [weecology/retriever#1060]
The `repository.py` script has a function `_redownload_from_repository(filepath, newpath, repo=REPOSITORY)`. Where has this been called?

The code that follows, also has a call to the function `_download_from_repository()`. Where has this been defined to not throw an error upon execution?

@ethanwhite @henrykironde

**Comment by henrykironde** [comment]
Could you provide the  line numbers, can't seem to find `_redownload_from_repository`

**Comment by ss-is-master-chief** [comment]
@henrykironde The issue is resolved. Looks like I was trying something out the other day and forgot to revert the changes to original.

Thank you.
