### ISSUE TITLE
Working on : Expansion of Spatial Data Support to the Data Retriever

### ISSUE THREAD

**Issue by ss-is-master-chief** [weecology/retriever#1062]
I have started to look into and working on the project : **Expansion of Spatial Data Support to the Data Retriever**.

@ethanwhite @henrykironde Please let me know of any aspects in particular I should be prioritising over others.

Would it be okay if I carried on the discussion through this `Issue`?

**Comment by henrykironde** [comment]
Great @ss-is-master-chief, We can have this discussion here.  Have you worked on GIS data before?

**Comment by ss-is-master-chief** [comment]
@henrykironde I have mostly worked with the basics of it, but I am willing to learn as much as I can. For the past few days I have been looking into SQLite support for Data-Retriever. How may I proceed?

**Comment by henrykironde** [comment]
First steps would be to try a small script to install Rasters into Sqlite.

Sample rasters that you could use are `https://viewer.nationalmap.gov/:`  https://s3-us-west-2.amazonaws.com/prd-tnm/StagedProducts/NLCD/data/2011/landcover/3x3/NLCD2011_LC_N39W105.zip

Also `retriever download bioclim` will give you some more samples to work with

There is an extension for Sqlite that can do that.

**Comment by ss-is-master-chief** [comment]
@henrykironde I go ahead with this Sir. Thank you for the reference.

**Comment by ss-is-master-chief** [comment]
@henrykironde The rasters file which was referred to only provides `txt` and `xlsx` formats for data. To import such files, it might be necessary to convert them into one of the supported formats by SQLite. One of the ways they could be converted is through the `pandoc` wrapper `pypandoc`. But it seems that the file conversion doesn't take place correctly always and many a times may show errors as well.

Are there any better methods?

**Comment by henrykironde** [comment]
The only file to consider is the image file `NLCD2011_LC_N39W105.tif` and you can use Qgis to see the map https://qgis.org/en/site/

**Comment by ss-is-master-chief** [comment]
@henrykironde When we talk of installing raster datasets into SQLite, how do we exactly mean to do that. Is Data Retriever supposed to take into consideration the raster image from online sources and extract data from it? Once data is extracted, what are the supposed fields to the tables? What kind of information should be derived from the `.tif` so as to have a moderate size of the data set?

I am going through SQLite and QGis documentation. This seems absolutely fascinating. Some things are very new to me but will be able to wrap my head around everything in no time.

**Comment by henrykironde** [comment]
Is Data Retriever supposed to take into consideration the raster image from online sources and extract data from it? yes

To handle rasters, SQlite has an extension called rasterlite http://www.gaia-gis.it/gaia-sins/rasterlite-docs/rasterlite-how-to.pdf

**Comment by ss-is-master-chief** [comment]
@henrykironde The `TIF` raster-image was installed in the SQLite database. These are the tables. I have converted the contents into a CSV format for better readability.

How would you like me to proceed? 


<img width="324" alt="screen shot 2018-02-04 at 11 54 13 am" src="https://user-images.githubusercontent.com/26060275/35774870-55a9d25c-09a2-11e8-9021-986642551889.png">

**Comment by henrykironde** [comment]
let's make a simple python program to do the same

**Comment by ss-is-master-chief** [comment]
@henrykironde Wrote a basic script for fetching spatial data from SQLite database and converting each of the tables into their respective `CSV` files. The code seems to work fine until this error shows up:

```OperationalError: no such module: VirtualSpatialIndex```

How do I go about this? The code written in [here]( https://github.com/ss-is-master-chief/scratchpad/blob/master/create_csv.py)

<img width="648" alt="screen shot 2018-02-04 at 3 36 54 pm" src="https://user-images.githubusercontent.com/26060275/35776382-4dfe19f4-09c1-11e8-883f-471842ddfd7d.png">

**Comment by henrykironde** [comment]
That's okey we shall figure out what went wrong later. lets also write a script that takes the image and installs it into sqlite.

**Comment by ss-is-master-chief** [comment]
@henrykironde Working on it.

**Comment by henrykironde** [comment]
What did you use to insert the data into Sqlite?

**Comment by ss-is-master-chief** [comment]
@henrykironde The first drafting was just the module to convert SQLite data into CSV formats. It was done using Rasterlite from the Command Line itself.

**Comment by henrykironde** [comment]
` module to convert SQLite data into CSV formats` what does this mean? The problem at hand is to get a raster and insert it into SQLite. So i think i am lost. could you paste the command you used?

**Comment by ss-is-master-chief** [comment]
@henrykironde The TIFF image was converted into raster data using `rasterlite_load` as per the documentation here : http://www.gaia-gis.it/gaia-sins/rasterlite-docs/rasterlite-how-to.pdf. 

This created a database called : truemarble.sqlite, and the data was inserted here successfully.

Now coming back to Python, I took the database and converted the tables into respective CSV files.

If I haven't misunderstood, I am to implement the loading of raster data to SQLite in Python?

**Comment by henrykironde** [comment]
Great, Okey let us create a script and the input will be the path to the raster file and it will do everything you have done. Load the data and get that data out. I understand loading is a command line. And we can use python to call that.

**Comment by henrykironde** [comment]
Let me know if I am clear

**Comment by ss-is-master-chief** [comment]
@henrykironde Yes absolutely.

**Comment by ss-is-master-chief** [comment]
@henrykironde 
[Please have a look](https://github.com/ss-is-master-chief/scratchpad/blob/master/create_csv.py)

**Comment by henrykironde** [comment]
looks good overall. when you are done removing the errors, we shall try to import and export other raster data formats.

**Comment by ss-is-master-chief** [comment]
@henrykironde On it..

**Comment by ss-is-master-chief** [comment]
@henrykironde [Debugged Code](https://github.com/ss-is-master-chief/scratchpad/blob/master/create_csv.py) : Please do have a look and advice on the necessary.

**Comment by ss-is-master-chief** [comment]
<img width="1062" alt="screen shot 2018-02-19 at 12 14 00 pm" src="https://user-images.githubusercontent.com/26060275/36366895-39497704-1576-11e8-9014-ad8b445cece6.png">

Source : [GIS Formats: Wikipedia](https://en.wikipedia.org/wiki/GIS_file_formats)

@ethanwhite @henrykironde Please let me know the initial formats to extend support to.

**Comment by henrykironde** [comment]
So in the script you created, you only consider `tif` files, `Scouts all files with the extension : TIF`.

```python
    files = []
    for file in glob.glob("*.tif"):
        files.append(file)
    return files
```

But as you have shown above, there are many extensions for spatial data. And the good thing is that they are handled by gdal and postgis straight out of the box. Reference: http://postgis.net/docs/manual-2.1/using_raster_dataman.html#RT_Raster_Loader 

If you run `raster2pgsql -G` you will get a list of supported formats. you will have to look for a few examples in those formats. Some of the common ones you can start with are Binary file, Esri Grid, GeoTiFF, IMG, JPEG2000, Esri .hdr. With the use of a few sample, you can test your code. 

That means if given a raster in any of those formats, the script should be able to install it.

**Comment by ss-is-master-chief** [comment]
@henrykironde I was working on support for HDF. What I was thinking was to tackle the popular formats (as mentioned above) first and have them ready. I could get the relevant documentation ready in parallel.

**Comment by henrykironde** [comment]
Okey keep working on the` HDF`.

**Comment by ss-is-master-chief** [comment]
Since HDF deals with Hierarchical datasets, it would take more time. I suggest I work on the above formats first.

**Comment by henrykironde** [comment]
Spatial data support is now supported.
