### ISSUE TITLE
Add test on tab delimiter data

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1064]
In the test_integration, we have tests on CSV(comma separated). We need a similar example for tab separated data.

An example of comma separated data. The tab separated data will follow the same setup.
You may get an error if you specify the delimiter as tab ("    "),  we can track the error and include a patch

```
simple_csv = {
    'name': 'simple_csv',
    'raw_data': ['a,b,c',
                 '1,2,3',
                 '4,5,6'],
    'script': {"name": "simple_csv",
               "resources": [
                   {"dialect": {"do_not_bulk_insert": "True"},
                    "name": "simple_csv",
                    "schema": {},
                    "url": "http://example.com/simple_csv.txt"}
               ],
               "retriever": "True",
               "retriever_minimum_version": "2.0.dev",
               "version": "1.0.0",
               "urls":
                   {"simple_csv": "http://example.com/simple_csv.txt"}
               },
    'expect_out': ['a,b,c', '1,2,3', '4,5,6']
```

**Comment by aswanipranjal** [comment]
Hey @henrykironde, I'd like to take up this issue.

**Comment by ss-is-master-chief** [comment]
@shreyneil Regarding the specified delimiter for the tab spaced data. Doesn't it throw an error when run locally?

**Comment by henrykironde** [comment]
The raw data should be tab separated 
```
    'raw_data': ['a    b    c',
                 '1    2    3',
                 '4    5    6'],
```

**Comment by henrykironde** [comment]
And i think we should escape the tab to work

**Comment by shreyneil** [comment]
i have made some changes, Please review @henrykironde.
