### ISSUE TITLE
Fetching Raster Data from online sources

### ISSUE THREAD

**Issue by ss-is-master-chief** [weecology/retriever#1074]
A lot of websites offer good quality and cleaned raster datasets in `zip` formats.. 

Websites 

[http://atlas.ca.gov/download.html](http://atlas.ca.gov/download.html)
[https://freegisdata.rtwilson.com/](https://freegisdata.rtwilson.com/)

@henrykironde @ethanwhite  Any suggestions?

**Comment by henrykironde** [comment]
Thanks @ss-is-master-chief these are good datasets. We do not store/distribute data, so we can not save the files. The retriever has that capability to unzip the files, We just need to figure out the right `urls` that point to these datasets. Thanks for the sources. I will describe the sample dataset script for raster and vector data in the coming week.

**Comment by ss-is-master-chief** [comment]
@henrykironde Looking forward to it

**Comment by ss-is-master-chief** [comment]
@henrykironde Please update me regarding the `urls` and sample dataset script.

**Comment by henrykironde** [comment]
Thanks for the reminder, I have it on my calendar on this weekend Friday - Sunday. Will get back to you on one of those days

**Comment by ss-is-master-chief** [comment]
@henrykironde Sure Sir.

**Comment by zhangcandrew** [comment]
Hey @ss-is-master-chief, just wanted to pop in and say you can find the urls that all the zip files come from by right clicking and just copying the link address. As far as the sample dataset script goes, looking over some of the .py files in the scripts folder should get you started on the right foot with that!

**Comment by ss-is-master-chief** [comment]
Thank you for the input @zhangcandrew !!

**Comment by ss-is-master-chief** [comment]
Some Raster-Data Sources:
1. https://planet.openstreetmap.org/ - historical shapefiles, planet data, etc.
2. http://www.naturalearthdata.com/downloads/ - small, medium, large scale earth data
3. https://hub.arcgis.com/pages/open-data - data is available in form of spreadsheets, shapefiles, GeoJSON, etc
4. https://gisgeography.com/free-satellite-imagery-data-list/ - list of Satellite Image sources

**Comment by henrykironde** [comment]
These data sources have been added to the latest issue `Ref 1575`
