### ISSUE TITLE
[TEST] Error at test_modified_scripts.py 

### ISSUE THREAD

**Issue by ss-is-master-chief** [weecology/retriever#1076]
Running `py.test ./test/test_modified_scripts.py` throws the following error

<img width="1279" alt="screen shot 2018-02-10 at 9 50 16 am" src="https://user-images.githubusercontent.com/26060275/36058501-17638bc8-0e48-11e8-82e8-0947f0e80388.png">

```ImportError while importing test module '/Users/sumitsaha/Desktop/retriever-master-2/test/test_modified_scripts.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_modified_scripts.py:20: in <module>
    from retriever.lib.engine_tools import get_module_version
E   ModuleNotFoundError: No module named 'retriever.lib.engine_tools'```

**Comment by henrykironde** [comment]
Get the recent copy of master.
Install either `pip install . -U` or `python setup.py`. (sudo if required).
Run `retriever reset all`. and `git clean -fx`.
Then run `python test/test_modified_scripts.py`.

Test if it works:
Change iris's version number and update the `version.txt` using `python version.py`.
Run` python test/test_modified_scripts.py`

To test using `py.test`
uncomment the line 
```
def test_install_modified():
    assert install_modified() == []
```
run `py.test ./test/test_modified_scripts.py`

**Comment by ss-is-master-chief** [comment]
@henrykironde The error still persists. I tried looking for looping dependencies among the classes but they aren't an issue.

**Comment by henrykironde** [comment]
Give me results of `git log`

**Comment by ss-is-master-chief** [comment]
```commit fe50141c64f179e3565b9f372c017f8e3d20bb81 (HEAD -> master, origin/master, origin/HEAD)
Merge: d00452ac 987f6566
Author: ss-is-master-chief <sumit.saha666@gmail.com>
Date:   Thu Feb 15 14:00:28 2018 +0530

    Merge branch 'master' of https://github.com/ss-is-master-chief/retriever
    trial```

**Comment by henrykironde** [comment]
try `sudo py.tests .....`

**Comment by ss-is-master-chief** [comment]
Same error @henrykironde

**Comment by henrykironde** [comment]
Give me `which retriever` and `which python` results

**Comment by ss-is-master-chief** [comment]
`/Users/sumitsaha/Desktop/venv/bin/retriever` : `which retriever`
`/Users/sumitsaha/Desktop/venv/bin/python` : `which python`

v2.1.dev [retriever version]

**Comment by henrykironde** [comment]
On the same terminal run` python`
And then run these commands 
```
from retriever.lib.engine_tools import sort_csv
from retriever.lib.scripts import MODULE_LIST, SCRIPT_LIST
from retriever.lib.engine_tools import get_module_version
```

**Comment by ss-is-master-chief** [comment]
In this manner?

<img width="910" alt="screen shot 2018-02-16 at 9 47 34 pm" src="https://user-images.githubusercontent.com/26060275/36317426-138e07b0-1363-11e8-8750-5dc2e6c2ea4d.png">

**Comment by henrykironde** [comment]
Are using anaconda?

**Comment by henrykironde** [comment]
From what I see, it sometimes runs and then fails. Try to run with -v.
`py.test ./test/test_modified_scripts.py -v `
and uncomment these lines
```
def test_install_modified():
    assert install_modified() == []
```

**Comment by ss-is-master-chief** [comment]
`Are using anaconda?` : Yes
`py.test ./test/test_modified_scripts.py -v` : Still persists.

Already unocmmented:
```
def test_install_modified():
    assert install_modified() == []
```

**Comment by apoorvaeternity** [comment]
For me, it is failing on `retriever version 2.1.0` and working on `retriever version 2.1.dev`.
![screenshot from 2018-02-17 02-25-36](https://user-images.githubusercontent.com/21103831/36328913-f5fd396a-1389-11e8-86ce-69b6e540331b.png)

**Comment by apoorvaeternity** [comment]
`engine_tools` is not added to `__all__` of `__init__.py` in `lib` that is why it cannot be imported but if you create a new environment and use `python setup.py develop` to install `retriever` the script will run fine.

**Comment by ss-is-master-chief** [comment]
@apoorvaeternity I had created a virtual environment to test this and included `engine_tools` under `__all__`, but the issue persisted.

`__all__` doesn't contain `defaults` or `scripts` either. The respective imports in `test_modified_scripts.py` doesn't seem to throw that error. Why is this so? @henrykironde

**Comment by apoorvaeternity** [comment]
I saw the code again` __all__` is not the reason behind it because `__all__` is the list of module names that should be imported when `from package import *` is encountered but in this case, we are directly referring to `from retriever.lib.engine_tools import get_module_version`.

What I can see is that `engine_tools.py` is not part of the final package.
![screenshot from 2018-02-17 10-16-25](https://user-images.githubusercontent.com/21103831/36338063-ad681688-13cb-11e8-85b7-9f9dd876f06b.png)

**Comment by ss-is-master-chief** [comment]
```__all__ is the list of module names that should be imported when from package import * is encountered```  CORRECT!

<img width="886" alt="screen shot 2018-02-17 at 11 21 11 am" src="https://user-images.githubusercontent.com/26060275/36338424-bb863ffc-13d4-11e8-8655-e67398d6be63.png">

Yep. It is not there.
