### ISSUE TITLE
wine_composition.json has no urls key

### ISSUE THREAD

**Issue by apoorvaeternity** [weecology/retriever#1078]
While working on #1068 I found that wine_composition.json has no urls key so when I use dataset.urls it returns an empty dictionary where dataset is a script object of `wine-composition`

**Comment by henrykironde** [comment]
As I mentioned earlier, you should consider the tables not urls keys.
The `table{}` dict is a cleaning version of `urls {keys: }`.  If you debug the code to look at the objects as they are created, you will notice the wine_composition object has tables. These tables are what you need to process instead of url.keys.
<img width="966" alt="screen shot 2018-02-12 at 1 20 03 pm" src="https://user-images.githubusercontent.com/5192965/36112599-35028e48-0ff8-11e8-9b57-9287102a607a.png">

**Comment by henrykironde** [comment]
Thanks @apoorvaeternity for the issue. I hope this will help you with understanding the new code base more. The `url.key` was used previously, right now, the best way to handle and get table names is by looking at the tables' property of the script(dataset object).

If that did not work as you wanted, let me know you can reopen this issue anytime

**Comment by apoorvaeternity** [comment]
Okay

**Comment by apoorvaeternity** [comment]
@henrykironde The tables property of following datasets returns an empty dictionary.
```
amniote-life-hist
aquatic-animal-excretion
bioclim
biomass-allometry-db
breed-bird-survey
breed-bird-survey-50stop
flensburg-food-web
forest-inventory-analysis
forest-plots-wghats
gentry-forest-transects
NPN
pantheria
plant-life-hist-eu
predator-prey-size-marine
predicts
prism-climate
socean-diet-data
tree-demog-wghats
vertnet
vertnet-amphibians
vertnet-birds
vertnet-fishes
vertnet-mammals
vertnet-reptiles
wood-density
amniote-life-hist
aquatic-animal-excretion
bioclim
biomass-allometry-db
breed-bird-survey
breed-bird-survey-50stop
flensburg-food-web
forest-inventory-analysis
forest-plots-wghats
gentry-forest-transects
NPN
pantheria
plant-life-hist-eu
predator-prey-size-marine
predicts
prism-climate
socean-diet-data
tree-demog-wghats
vertnet
vertnet-amphibians
vertnet-birds
vertnet-fishes
vertnet-mammals
vertnet-reptiles
wood-density
```

**Comment by apoorvaeternity** [comment]
I think right now if the tables is empty I will have to check urls.

**Comment by henrykironde** [comment]
Okey that sounds right, because those are python custom scripts. Go to the urls

**Comment by apoorvaeternity** [comment]
So should I add urls key in wine_composition.json? Though I have modified my code to work as I mentioned in [my comment](https://github.com/weecology/retriever/issues/1078#issuecomment-365282983).

**Comment by henrykironde** [comment]
Let us not add those url keys because if you look at the values, they are a composition of already existing properties. So if we can do with out them, that would be good, else we can try to see how to accommodate that issue.
