### ISSUE TITLE
[Spatial Data WIP] HDF support

### ISSUE THREAD

**Issue by ss-is-master-chief** [weecology/retriever#1079]
@henrykironde Working on support for HDF files. Need to test code. It would be helpful if you could link some downloadable `.hf5` files. Thank you.

**Comment by henrykironde** [comment]
https://ndownloader.figshare.com/files/7024985

obtained from http://neondataskills.org/self-paced-tutorial/Python-HDF5-basics

**Comment by ss-is-master-chief** [comment]
@henrykironde Thank you for the reference.

**Comment by henrykironde** [comment]
I am not sure if hdf5 can be loaded directly by `rasterlite_load` but you can check the formats supported

**Comment by ss-is-master-chief** [comment]
@henrykironde The dataset has to loaded using the `h5py` module. It comes pre-loaded with `conda`. I can make the functions to be executed conditionally.

**Comment by henrykironde** [comment]
We don't need conda to load this. If the files can't be loaded directly, I guess we can transform them to single files and load them as individual datasets. Reference http://www2.geog.ucl.ac.uk/~plewis/geogg122_local/geogg122.old/Chapter4_GDAL/GDAL_HDF.html

**Comment by ss-is-master-chief** [comment]
@henrykironde Yes, we could also opt for the GDAL method. Since on MacOS, I have some unresolved issues with the `gdal` libraries. Hence, I am facing difficulty testing. Would it okay if I created the scaffolding with `h5py` and have a fully functional module? What I could do following this, is to make changes to the code wrt `gdal`.

**Comment by henrykironde** [comment]
What issues are you facing on mac?

**Comment by henrykironde** [comment]
`Would it okay if I created the scaffolding with h5py and have a fully functional module?` Sure go for it.
_Some additional reference for issue_
https://gis.stackexchange.com/questions/209075/postgis-storing-large-gridded-time-series.
http://lists.osgeo.org/pipermail/postgis-users/2014-July/039405.html
https://trac.osgeo.org/postgis/ticket/1761
http://slideplayer.com/slide/5144580/

**Comment by ss-is-master-chief** [comment]
@henrykironde Thank you for the references

**Comment by ss-is-master-chief** [comment]
@henrykironde Resolved issues with `gdal`.
