### ISSUE TITLE
Installation of breed-bird-survey dataset is failing

### ISSUE THREAD

**Issue by apoorvaeternity** [weecology/retriever#1084]
![screenshot from 2018-02-14 11-42-39](https://user-images.githubusercontent.com/21103831/36210998-f23b5764-11c5-11e8-9cba-1fa13900bd8d.png)

**Comment by ethanwhite** [comment]
This seems to be working for me right now on `master` and the url seems to be working in the browser. Can you run again in case it was just a temporary connectivity issue and if it's still not working see if you can see this url in your browser?

ftp://ftpext.usgs.gov/pub/er/md/laurel/BBS/DataFiles/SpeciesList.txt

**Comment by apoorvaeternity** [comment]
I tried opening this URL in the browser in the morning at that time it was not working and I checked again an hour back it was not working but just now and it seems to work fine. 
While working on #1068 I get to check all the urls of all datasets so encountered it at that time.

For how long should we wait before actually reporting that a dataset is failing?

Closing this now.

**Comment by ethanwhite** [comment]
I think it's OK to flag it immediately. This sort of situation won't be very common.

**Comment by henrykironde** [comment]
Yes. I also tested it and it was  failing then, I have not tested again. Any error or perceived error should be reported and we do appreciated this a lot.

**Comment by ethanwhite** [comment]
Yes, thanks very much for reporting this @apoorvaeternity!

**Comment by apoorvaeternity** [comment]
@ethanwhite @henrykironde My pleasure :)
