### ISSUE TITLE
different usage prompt for retriever install 

### ISSUE THREAD

**Issue by ss-is-master-chief** [weecology/retriever#1090]
If we use `retriever install`, we are prompted with `usage: retriever install [-h] [--compile] [--debug] [--not-cached] {mysql,postgres,sqlite,msaccess,csv,json,xml} ...` and on using, for example`retriever install csv`, prompted with `usage: retriever install csv [-h] [--table_name [TABLE_NAME]] dataset`.

Could we change the usage alert into something common to both the incomplete command? How about `usage: retriever install {mysql,postgres,sqlite,msaccess,csv,json,xml} [-h] [--compile] [--debug] [--not-cached] [--table_name [TABLE_NAME]] dataset`?

`[-path]` could be a part of the usage alert as well.

**Comment by henrykironde** [comment]
@ss-is-master-chief, thanks for that idea, however this cannot be generic. It is a step wise process that only returns usage per level at which you are messing up. let me know if we are on the same page.

**Comment by ss-is-master-chief** [comment]
@henrykironde I agree. What about `[-path]`?

**Comment by henrykironde** [comment]
Good question. So in the CSV engine we don't have `path` as part of the `required_opts`
```
    required_opts = [
        ("table_name",
         "Format of table name",
         os.path.join(DATA_DIR, "{db}_{table}.csv")),
    ]
```

**Comment by ss-is-master-chief** [comment]
@henrykironde Got it. Thanks for the clarification.
