### ISSUE TITLE
Verbose Mode Overwritten by License/Keyword Search

### ISSUE THREAD

**Issue by zhangcandrew** [weecology/retriever#1091]
In a prior version of retriever, the user was allowed to run `retriever ls -l` to return a verbose list of all of our datasets. This functionality no longer exists since it was overwritten in a newer PR.

I think it might still be useful to have in the retriever though. 

See #488,  #1037.

**Comment by adhaamehab** [comment]
Hi @zhangcandrew I will work in this issue

**Comment by adhaamehab** [comment]
@zhangcandrew  could you review the PR?

**Comment by ethanwhite** [comment]
Fixed in a6ddc9cbd697c0cae91db79ca2983c8e0b46eabe. Thanks @adhaamehab!
