### ISSUE TITLE
Python 2 encoding issues in Python interface only

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1097]
In the Python interface some datasets (at least `airports` and `gentry-forest-transects`) report encoding issues and fail. E.g.,

```
In [11]: rt.install_sqlite('gentry-forest-transects')
=> Installing gentry-forest-transects
'ascii' codec can't encode characters in position 5-6: ordinal not in range(128)
```

But these same datasets install fine from the CLI.

**Comment by ss-is-master-chief** [comment]
May I go ahead with this? @ethanwhite

**Comment by ethanwhite** [comment]
Go for it. If you have questions @goelakash may have some ideas since he dealt with a lot of the issues involving encoding in the past.

**Comment by ss-is-master-chief** [comment]
Thank you.

**Comment by apoorvaeternity** [comment]
@ethanwhite 
According to docs
`The csv module doesn’t directly support reading and writing Unicode, but it is 8-bit-clean save for some problems with ASCII NUL characters. So you can write functions or classes that handle the encoding and decoding for you as long as you avoid encodings like UTF-16 that use NULs. UTF-8 is recommended.`

[Link to docs](https://docs.python.org/2/library/csv.html)
A possible fix to this would be adding this in engine.py
```python
import sys
from imp import reload
from retriever.lib.defaults import ENCODING
encoding = ENCODING.lower()
reload(sys)
if hasattr(sys, 'setdefaultencoding'):
    sys.setdefaultencoding(encoding)
```
or use the way that is recommended in docs but then we will have to check unicode strings everywhere.

If no one is working on this issue I would like to take this up.

**Comment by ss-is-master-chief** [comment]
@apoorvaeternity Please go ahead :)

**Comment by ethanwhite** [comment]
I think the big question (which maybe @apoorvaeternity answered, but I didn't follow) is why this is only happening in the Python interface not the CLI. The should both be running largely the same code for the actual data processing and installation. Once we understand that then I think we'll understand the best fix.

**Comment by apoorvaeternity** [comment]
@ethanwhite In CLI we use `__main__.py`. In it we have set the default encoding as
```python
from retriever.lib.defaults import sample_script, CITATION, ENCODING, SCRIPT_SEARCH_PATHS
encoding = ENCODING.lower()
# sys removes the setdefaultencoding method at startup; reload to get it back
reload(sys)
if hasattr(sys, 'setdefaultencoding'):
    sys.setdefaultencoding(encoding)
```
Removing these lines give the same error in CLI too. In python interface we have not set the default encoding so the error occurs.

**Comment by henrykironde** [comment]
@apoorvaeternity thats sounds right. I was expecting a PR on that. I think @ss-is-master-chief was working on that. We could confirm from @ss-is-master-chief else you could go ahead and put in a fix.

**Comment by apoorvaeternity** [comment]
@henrykironde I already asked him.  (See)[https://github.com/weecology/retriever/issues/1097#issuecomment-368449124]. Shall I work on the fix?

**Comment by henrykironde** [comment]
Yes, thanks
