### ISSUE TITLE
Retriever does not display "Directory does not exist"

### ISSUE THREAD

**Issue by pranita-s** [weecology/retriever#1100]
Retriever does not display "Directory does not exist" when target directory for installation of files does not exist. 

![retriever](https://user-images.githubusercontent.com/14193989/36761659-196ea6e4-1c46-11e8-8cf7-ffcd5b3638b8.png)

It neither displays error,nor it installs files

**Comment by pranita-s** [comment]
@henrykironde I found this necessary because in the R wrapper, it is present in Fetch command and it was not pointing out that the temp folder does not exist and therefore the return value of the fetch command was an empty list.

**Comment by henrykironde** [comment]
Thank you @pranita-s, I will review the PR

**Comment by ethanwhite** [comment]
@pranita-s does the retriever report the missing directory if you remote the `-q`?

**Comment by pranita-s** [comment]
Yes, it does. I am closing this issue. 
I raised it because I felt it as a bottleneck to the R's wrapper for fetch function. After reading the doc of retriever I could not comprehend the meaning of "quiet" in this context.

**Comment by ethanwhite** [comment]
Thanks. I think it's an excellent point that this error should be seen in the R wrapper. With the addition to our new progress bar system I suspect that we don't need the `-q` flag in the R wrapper anymore. Would you mind opening an issue over there for this same problem? Thanks!

**Comment by henrykironde** [comment]
@pranita-s sorry for the 👎 it had to be 👍 .

**Comment by pranita-s** [comment]
@ethanwhite Sure !

**Comment by pranita-s** [comment]
@ethanwhite Its related to ropensci/rdataretriever#113. Should a separate issue be raised for this?

**Comment by ethanwhite** [comment]
@pranita-s Yes, I think so. The fixes might end up being the same, but the problems are different. Mention the relationship with https://github.com/ropensci/rdataretriever/issues/113 in the new issue. Thanks!
