### ISSUE TITLE
Incorrectly lower casing table_name for csv

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1101]
It looks like we're lower casing manually set table/directory names, at least for csv but probably for all flat file engines.

```
$ mkdir TESTER
$ retriever install csv mammal-masses --table_name TESTER/test.csv
=> Installing mammal-masses
[Errno 2] No such file or directory: 'tester/test.csv'
Done!

$ mkdir tester
$ retriever install csv mammal-masses --table_name TESTER/test.csv
=> Installing mammal-masses
Progress: 5731/5731 rows inserted into tester/test.csv totaling 5731:

Done!
```

This is causing issues for the R package, see https://github.com/ropensci/rdataretriever/issues/131, but is also a general problem since directory names are case sensitive for 2/3 OSs.

**Comment by ethanwhite** [comment]
This happens in the very first line of `__main__.py`:

```
sys.argv[1:] = [arg.lower() for arg in sys.argv[1:]]
```

This makes sense of course, but is an issue for that particular arg. I suspect that something changed in how R was creating it's temp dirs recently which is why this suddenly cropped up over there, but this is a bug regardless.

**Comment by ethanwhite** [comment]
@henrykironde - do you remember the motivation for https://github.com/weecology/retriever/commit/33788bd236a04c77bb4de66688ff3c590427f0bf ?

**Comment by henrykironde** [comment]
That is definitely a bug, I think it was a something I added when working on `the retriever ls ... `.
