### ISSUE TITLE
Switch from urllib to requests

### ISSUE THREAD

**Issue by zhangcandrew** [weecology/retriever#1114]
Right now the retriever uses the urllib/urllib2 module, but the requests module has proven itself as a much friendlier url request handler. 

Switching over would save us a lot of trouble/code in the future. 

Reference: http://docs.python-requests.org/en/master/

**Comment by apoorvaeternity** [comment]
Yes the requests module is a lot easier and error handling is also better.

**Comment by blue-atom** [comment]
Can I do this??

**Comment by henrykironde** [comment]
Go for it @blue-atom

**Comment by blue-atom** [comment]
@henrykironde  Thanks for assigning it to me.....
