### ISSUE TITLE
Error on custom table name.

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1117]
The current state of the retriever uses the required_opts  `"table_name"` to customize the installation of dataset into dataset. This works fine for single table datasets however, it over rides the tables when the dataset contains multi tables. The best way to use this option is by using this custom `table_name` as a prefix to the table name. 

For example:

"{db}.{prefix_name}_{table}")

**Comment by henrykironde** [comment]
@adhaamehab i have create an issue for the bug

**Comment by adhaamehab** [comment]
@henrykironde  I'll look into this bug
