### ISSUE TITLE
Add a description field(s) to setup.py

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1120]
This populates the description on PYPI:

https://packaging.python.org/tutorials/distributing-packages/#description

**Comment by apoorvaeternity** [comment]
@ethanwhite Shall I send a PR for this?

**Comment by apoorvaeternity** [comment]
`The Data Retriever is a package manager for data. It downloads, cleans, and stores publicly available data, so that analysts spend less time cleaning and managing data, and more time analyzing it.`
Is this text fine? It's the same as on http://www.data-retriever.org/

**Comment by ethanwhite** [comment]
Looks great. Go for it!
