### ISSUE TITLE
Add BioTIME dataset

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1123]
Database of biodiversity time series. The data is available here:
https://zenodo.org/record/1095628

I think we just want the three csv files.

**Comment by ss-is-master-chief** [comment]
@ethanwhite Python and JSON scripts are to be made for the BioTIME dataset?

**Comment by henrykironde** [comment]
@ss-is-master-chief, just checked the dataset and only json files may be enough for this dataset.
The .csv files are the one that we want.
BioTIMECitations_06_12_2017.csv 
BioTIMEMetadata_06_12_2017.csv
BioTIMEQuery_06_12_2017.csv

**Comment by ss-is-master-chief** [comment]
Thank you for the update @henrykoronde!!

**Comment by henrykironde** [comment]
@ss-is-master-chief, how is this issue going on?

**Comment by ss-is-master-chief** [comment]
@henrykironde I'll share an update by 17th April
