### ISSUE TITLE
Broken link to datasets in online documentation

### ISSUE THREAD

**Issue by dlebauer** [weecology/retriever#1127]
When 
* I go to the home page http://www.data-retriever.org/
* then click 'docs'
* then click link to available datasets https://retriever.readthedocs.io/en/latest/datasets.html

I get the message "Sorry this page does not exist yet"

Perhaps a simple broken link? Something wrong with https://github.com/weecology/retriever/blob/master/retriever/lib/datasets.py?

**Comment by zhangcandrew** [comment]
Just Fixed! Closing the issue. Thanks @dlebauer.
