### ISSUE TITLE
Add a `directory` or `path` argument to flat file installs

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1137]
It's not uncommon to want to install data files into a specific directory. We currently support this through the `table_name` function and `-t` CLI flag, but this requires being familiar with the somewhat tricky table name syntax, e.g.,

`retriever install csv mammal-masses -t datadir/{db}_{table}.csv`

A simpler and more common version of this would be something like

`retriever install csv mammal-masses -d datadir`

Related to #1117 and #1136.

**Comment by harshitbansal05** [comment]
@ethanwhite can I work on this one?

**Comment by ethanwhite** [comment]
Yes @harshitbansal05 that would be great!

**Comment by ashishpriyadarshiCIC** [comment]
@harshitbansal05 We may to work together to solve the issues #1136 and this one. Can you tell me where we should communicate to work.

**Comment by harshitbansal05** [comment]
@ashishpriyadarshiCIC I have tried to fix this issue and pushed it to my fork(the above branch). You can pull this and work on #1136 and open a pull request on my branch.

**Comment by ashishpriyadarshiCIC** [comment]
@ethanwhite @harshitbansal05 I've fixed issue #1136 . Should I open a pull request here or @harshitbansal05's repository ?
