### ISSUE TITLE
Urgent: Datasets failing with Exception KeyError: KeyError weakref to 'tqdm'

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1147]
Something is not right with the tqdm package. If anyone gets the same error let me know

Try to install 
```amniote-life-hist
car-eval
elton-traits
community-abundance-misc
```

`Exception KeyError: KeyError(<weakref at 0x105995d8; to 'tqdm' at 0x1051d0>,) in <object repr() failed> ignored`

**Comment by ethanwhite** [comment]
Working fine for me on Python 2 and 3 on Ubuntu 18.04.

**Comment by henrykironde** [comment]
Closing, Installing fine after update of tqdm
