### ISSUE TITLE
Datasets Available webpage link broken

### ISSUE THREAD

**Issue by KristinaRiemer** [weecology/retriever#1160]
The "Edit on GitHub" link at the top of [Datasets Available](https://retriever.readthedocs.io/en/latest/datasets_list.html) goes to a 404 page. I wasn't sure what link should replace it.

**Comment by ethanwhite** [comment]
Yeah, we automatically generate that page, so there's nothing to edit on GitHub, but the docs templates assume that there is. I'm not sure how easy it would be to remove that from the template, but we can definitely look into it. Was the process that led you to click on the link something that you think other people will do frequently?

**Comment by henrykironde** [comment]
We shall insert a file `docs/datasets_list.rst` with that information. It will fix it.

**Comment by henrykironde** [comment]
fixed in 1b213a6952ba5cacb7c8cc691adf1374dcb799e5

**Comment by KristinaRiemer** [comment]
@ethanwhite FYI, I only clicked on that link to try to fix the mistake that was addressed in 3a0d73e2. I don't think many people would click on it.

**Comment by ethanwhite** [comment]
Even if it wouldn't have been common it's always great to fix these sorts of things when possible. Thanks!
