### ISSUE TITLE
Add supplemental BBS data

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#117]
Via: http://ecologicaldata.org/node/15/talk

Add http://esapubs.org/archive/ecol/E093/215/ to Retriever.

**Comment by davharris** [comment]
Wow, where has this data set been all my life? :+1:

**Comment by ethanwhite** [comment]
Integration should be handled by our new upcoming software effort, so I'm modifying this issue to just include adding the data.

**Comment by shreyneil** [comment]
@ethanwhite It would be great if you could close this issue.

**Comment by ethanwhite** [comment]
Thanks @shreyneil!
