### ISSUE TITLE
Use shared table schema

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1172]
Use a shared table schema in frictionless data json files:
https://discuss.okfn.org/t/shared-table-schema/6969

**Comment by harshitbansal05** [comment]
@henrykironde I was thinking to work on it, but could not understand properly from the discussion in the link. Could you please elaborate?

**Comment by henrykironde** [comment]
Hi, @harshitbansal05 I think we should not work on this for not. I will have to revise the issue or I will close it and open a new one later.

**Comment by henrykironde** [comment]
Closing due to change in the frictionless table schema. 
We also have a pr that handles using frictionless data packages.
