### ISSUE TITLE
Add LakeCat data

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1184]
Dataset on US lake locations and associated watersheds: https://www.epa.gov/national-aquatic-resource-surveys/lakecat

**Comment by henrykironde** [comment]
I guess we have the spatial dataset and the tabular datasets.

Tabular : ftp://newftp.epa.gov/EPADataCommons/ORD/NHDPlusLandscapeAttributes/LakeCat/FinalTables/

Spatial: ftp://newftp.epa.gov/EPADataCommons/ORD/NHDPlusLandscapeAttributes/LakeCat/Framework/
Let me know if that is correct

**Comment by ethanwhite** [comment]
Yeah, I think that's right. It would be great to have both.
