### ISSUE TITLE
gentry install error

### ISSUE THREAD

**Issue by dmcglinn** [weecology/retriever#1194]
There seems to be a problem with the stem data. Specifically, on my windows machine the error is `"There is no item named 'NDAKANNI.xls' in the archive"`. I checked and this file does exist at this path `.retriever\raw_data\gentry-forest-transects\all_Excel.zip\africa\NDAKANNI.xls` so the file exists but for some reason retriever does not see it. I also check that `retriever install` would work for other datasets and it worked fine. 

On a linux machine I received a different error: `'module' object has no attribute 'BadZipFile'`. 

Here is the full call and error statement from the PC: 
```
retriever install csv gentry-forest-transect
fao_global_capture_product is supported by Retriever version 2.1.dev
Current version is v2.0.0
nd_gain is supported by Retriever version 2.1.dev
Current version is v2.0.0
noaa_fisheries_trade is supported by Retriever version 2.1.dev
Current version is v2.0.0
partners_in_flight is supported by Retriever version 2.1.dev
Current version is v2.0.0
fao_global_capture_product is supported by Retriever version 2.1.dev
Current version is v2.0.0
nd_gain is supported by Retriever version 2.1.dev
Current version is v2.0.0
noaa_fisheries_trade is supported by Retriever version 2.1.dev
Current version is v2.0.0
partners_in_flight is supported by Retriever version 2.1.dev
Current version is v2.0.0
=> Installing Alwyn H. Gentry Forest Transect Dataset
Progress: 226 / 226 rows inserted into .\gentry_forest_transects_sites.csv totalFailed to load script: nla (C:\Users\mcglinn/.retriever/scripts/)
Exception: name 'UTF' is not defined
Failed to load script: prism_climate (C:\Users\mcglinn/.retriever/scripts/)
Exception: No module named 'requests'
Failed to load script: usgs_elevation (C:\Users\mcglinn/.retriever/scripts/)
Exception: No module named 'requests'
Failed to load script: nla (C:\Users\mcglinn/.retriever/scripts/)
Exception: name 'UTF' is not defined
Failed to load script: prism_climate (C:\Users\mcglinn/.retriever/scripts/)
Exception: No module named 'requests'
Failed to load script: usgs_elevation (C:\Users\mcglinn/.retriever/scripts/)
Exception: No module named 'requests'



"There is no item named 'NDAKANNI.xls' in the archive"
Done!
```

**Comment by dmcglinn** [comment]
It looks like my error may be related to #1144

**Comment by dmcglinn** [comment]
It looks like #1144 was addressed with a patch in #1145, specifically commit 27bd7849bceb8736fe6860d750a6bab43f92360c . If I roll back the changes for this script back to the state it was in 5280865792ab0246065793f35fa35b65f06f2187 then the install works. So something is going on with respect to how the data file paths are being parsed. Can someone who is more familiar with python please tackle the patch here?

**Comment by ethanwhite** [comment]
Hey @dmcglinn - thanks for reporting this. The current master seems to be working for me on Linux, but it looks like maybe we broke backward compatibility with 2.0.0 (which looks like what you're running. If you update to the current master things should work:

```
pip install git+https://git@github.com/weecology/retriever.git
```

Let me know if that works.

@henrykironde - we should still try to fix the backwards compatibility issue.

**Comment by ethanwhite** [comment]
@dmcglinn - Did upgrading to the current `master` (or now the new release) fix this for you?
