### ISSUE TITLE
Add National Land Cover Database 2011 (NLCD 2011)

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1195]
National Land Cover Database 2011 (NLCD 2011)  provides 16-class land cover classification scheme across the United States at a spatial resolution of 30 meters. The dataset is based on a decision-tree classification of circa 2011 Landsat satellite data. 

Ref: https://www.mrlc.gov/nlcd2011.php
citation: `Preferred NLCD 2011 citation: Homer, C.G., Dewitz, J.A., Yang, L., Jin, S., Danielson, P., Xian, G., Coulston, J., Herold, N.D., Wickham, J.D., and Megown, K., 2015, Completion of the 2011 National Land Cover Database for the conterminous United States-Representing a decade of land cover change information. Photogrammetric Engineering and Remote Sensing, v. 81, no. 5, p. 345-354`

**Comment by DumbMachine** [comment]
I fear that the [link](https://www.mrlc.gov/nlcd2011.php) is not functional anymore.
[This](https://nrcs.app.box.com/v/gateway/folder/39752407577) I beleive points to the same dataset. If so then I would like to implement the script for the same.

**Comment by henrykironde** [comment]
The data is here https://www.mrlc.gov/data and these are spatial datasets.
Some of the examples are `Bioclim` and `harvard-foreset`. I have not updated the docs on creating spatial datasets, so it may be a little hard. If you can start with some simpler examples like 1138

**Comment by henrykironde** [comment]
Added to list of `#1575`
