### ISSUE TITLE
Update contribution instructions

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1196]
Remove nose instructions from `CONTRIBUTING.md` file.

**Comment by apoorvaeternity** [comment]
Do we want to completely remove it or replace it with the pytest instructions?

**Comment by henrykironde** [comment]
@apoorvaeternity, we no longer use nose. Running the tests should describe `Pytests`.
Also, I have not tested your Pr, busy on the weaver, but i will get back up in a weak .
