### ISSUE TITLE
Not working in R 3.5.1?

### ISSUE THREAD

**Issue by JPGibert** [weecology/retriever#1197]
I was coming back to an old project for which I used the retriever and I was hoping to get it running in my new setup. When I tried to get it to work in R (R 3.5.1, on a High Sierra mac), it just doesn't seem to correctly install or else, it's having some PATH issues? install.packages() runs well, and library() seems to load it well, but then it doesn't seem to recognize any function within the package.

For example, when I use  "datasets()" or "rdataretriever::datasets()" it gives me

sh: retriever: command not found

Ethan mentioned that I might be lacking the original Python package but I seem to be able to call the retriever from the terminal, it just doesn't seem to want to work in R. Any ideas as to what might be happening? Thanks!

**Comment by ethanwhite** [comment]
Thanks for the report @JPGibert!

Two quick follow up questions:

1. Are you running in a terminal or in RStudio?
2. Can you provide the output from `which retriever` run from a terminal?

**Comment by henrykironde** [comment]
Could you give me the results for 
$retriever ls,
$retriever -v

**Comment by JPGibert** [comment]
Hey guys! Thanks for the prompt answer: 

@ethanwhite : 
1. R console + Script, I don't use RStudio.                       
2. /Applications/retriever.app/Contents/MacOS/retriever

@henrykironde 
1. 
Applications	Documents	Library		Music		Public
Desktop		Downloads	Movies		Pictures
2. -bash: -v: command not found

Something isn't right it seems :(

**Comment by JPGibert** [comment]
Also, the app itself seems to crash on startup. Dunno if that matters.

**Comment by henrykironde** [comment]
@JPGibert great, Are you using python on your computer.
I would recommend that you use python. The retriever.app is old and we are planning a release in the next two weeks. If you are using python let me know, we could have that configured for you pretty fast.

**Comment by JPGibert** [comment]
@henrykironde thanks! I definitely have Python on my computer, but I rarely ever code in Python, if that's what you're asking.

**Comment by ethanwhite** [comment]
> Also, the app itself seems to crash on startup. Dunno if that matters.

I don't think it's crashing on startup. It's just that we removed the GUI so running the App directly doesn't appear to do anything.

I agree with @henrykironde that it's generally easiest to install directly using Python, but if you want to use the installer that you have I think maybe you just haven't gotten it properly added to the path. Install instructions for the OS X package (https://www.data-retriever.org/#install) include the following commands to run from the terminal:

```
echo "/Applications/retriever.app/Contents/MacOS" > retrieverapp
sudo mkdir -p /etc/paths.d
sudo mv retrieverapp /etc/paths.d
```

Can you try that and see if it fixes things?

**Comment by JPGibert** [comment]
@ethanwhite, @henrykironde  alrighty! 

Seems to be working on python, through the terminal. See below: 

`>>> rt.check_for_updates()
Downloading scripts...
Download Progress: [#############################################] 100.00%
The retriever is up-to-date`

Thanks for the help guys!

**Comment by ethanwhite** [comment]
Awesome! Let us know if there's anything more we can do.

**Comment by JPGibert** [comment]
Cool, thank you guys!
