### ISSUE TITLE
BBS dataset "counts" file issue

### ISSUE THREAD

**Issue by JPGibert** [weecology/retriever#1198]
Hey all,

Sorry to be back. I tried to download the Bird Breeding Survey dataset. In the past, it would download, among other things, a weather file, a routes file, a species list file, and a "counts" file, which is the important one. For some reason, regardless of which version of the BBS data I download, the counts file is nowhere to be found, but all other files are there. Communicating with @ethanwhite, he mentioned that he downloaded the BBS dataset and got a counts file.

I already did reset/update to no avail, and below is the output for 'retriever --version'

```bash
Jeans-iMac-Pro:.retriever jeanphi$ retriever --version
Failed to load script: nla (scripts)
Exception: name 'UTF' is not defined 
partners_in_flight is supported by Retriever version 2.1.dev
Current version is v2.0.0
fao_global_capture_product is supported by Retriever version 2.1.dev
Current version is v2.0.0
nd_gain is supported by Retriever version 2.1.dev
Current version is v2.0.0
Failed to load script: usgs_elevation (scripts)
Exception: No module named 'requests' 
Failed to load script: prism_climate (scripts)
Exception: No module named 'requests' 
noaa_fisheries_trade is supported by Retriever version 2.1.dev
Current version is v2.0.0
Failed to load script: nla (scripts)
Exception: name 'UTF' is not defined 
partners_in_flight is supported by Retriever version 2.1.dev
Current version is v2.0.0
fao_global_capture_product is supported by Retriever version 2.1.dev
Current version is v2.0.0
nd_gain is supported by Retriever version 2.1.dev
Current version is v2.0.0
Failed to load script: usgs_elevation (scripts)
Exception: No module named 'requests' 
Failed to load script: prism_climate (scripts)
Exception: No module named 'requests' 
noaa_fisheries_trade is supported by Retriever version 2.1.dev
Current version is v2.0.0
v2.0.0
```

**Comment by henrykironde** [comment]
@JPGibert thanks for the issue. How did you install the retriever?

**Comment by JPGibert** [comment]
Hey @henrykironde! I followed the instructions in https://www.data-retriever.org/. Although it didn't quite work at first (got some error using the pip command, even after I installed pip the installation would go well then throw me an error) so in the end I installed the app then used:

```
echo "/Applications/retriever.app/Contents/MacOS" > retrieverapp
sudo mkdir -p /etc/paths.d
sudo mv retrieverapp /etc/paths.d
```

**Comment by henrykironde** [comment]
We could do a google hangout session and I could guide you through the installation . `henrykironde@ gmail.com`

**Comment by JPGibert** [comment]
@henrykironde that'd be awesome! I'm running to a seminar now, any chance we could do that either later 4:30 EDT or tomorrow?

**Comment by henrykironde** [comment]
Both work for me , Just ping me 30-15 minutes before.

**Comment by JPGibert** [comment]
@henrykironde , turns out the seminar is canceled, do you want to do that now?

**Comment by henrykironde** [comment]
Sure

**Comment by JPGibert** [comment]
Alrighty, thanks @henrykironde who spent one and a half hours to make sure everything was working well. I just downloaded the BBS data, "counts" file and all!
