### ISSUE TITLE
Add a long download warning/check for large datasets

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#121]
For really large datasets like FIA, NPN, and BBS we should have a large download warning that requires reconfirmation of desire to download the data. This should be suppressible from the CLI.

**Comment by jainamritanshu** [comment]
@henrykironde @ethanwhite I am working on this issue.

**Comment by ethanwhite** [comment]
I think this is a low priority addition. In most cases folks should have a good idea that a dataset is large if they are downloading it. Closing for now as low priority.
