### ISSUE TITLE
List of Data sites to include

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1218]
Feel free to edit and add more dataset links or sources.

1. https://freegisdata.rtwilson.com/ (**GIS Datasets**)
2. https://data.gov/
3. https://data.worldbank.org/
4. http://data.un.org/
5. https://piktochart.com/blog/8-useful-databases-to-dig-for-data/(reference point)

**Comment by DumbMachine** [comment]
[EU Open Data Portal](http://data.europa.eu/euodp/en/data/)
[Public Data by Google](https://cloud.google.com/bigquery/public-data/)
[Unicef Data Resources](https://data.unicef.org/resources/resource-type/datasets/)
[Wikipedia Dump](https://wiki.dbpedia.org/develop/datasets)

**Comment by henrykironde** [comment]
https://edg.epa.gov/metadata/catalog/main/home.page

**Comment by hrs2203** [comment]
https://www.kaggle.com/datasets
https://www.figure-eight.com/data-for-everyone/
https://registry.opendata.aws/

**Comment by ethanwhite** [comment]
Kaggle required logging in to download data the last time I looked, which won't work for our current tooling. If they've implemented API key based access (something they were talking about the last time I talked with them) then we could talk about adding functionality to allow users to specify an API key for datasets that require it.

**Comment by DumbMachine** [comment]
Kaggle has a very solid, cli based api for downloading and uploading datasets. The api requires an `access_token` in the ~/.kaggle folder. User could allow `retriever package` to read that dataset and accordingly perform the required actions or we could take the key as a parameter.

**Comment by ethanwhite** [comment]
@DumbMachine - ah that's great! I'm :+1: for adding support for reading the api key and then adding the Kaggle datasets. When adding this support we'll need messaging to users that indicates that they need to get the api key if they try to download a kaggle dataset and don't have one. Would you be up for opening an issue describing this feature addition?

**Comment by DumbMachine** [comment]
@ethanwhite I would love to open the issue and describe it further. I'll do it soon.

**Comment by henrykironde** [comment]
Added to the latest data collection `# 1575`
