### ISSUE TITLE
Link update in installation instructions?

### ISSUE THREAD

**Issue by ha0ye** [weecology/retriever#1225]
The [install webpage](https://www.data-retriever.org/#install) points to https://www.continuum.io/downloads for installing Anaconda, which times out for me. I think the preferred place might be https://www.anaconda.com/distribution/, but I'm not sure?

**Comment by pradeepgangwar** [comment]
@ha0ye Should i update it in this repo https://github.com/weecology/retriever-site?

**Comment by henrykironde** [comment]
Please go ahead

**Comment by pradeepgangwar** [comment]
@ha0ye @henrykironde Done. https://github.com/weecology/retriever-site/pull/6

**Comment by ethanwhite** [comment]
Thanks @pradeepgangwar! I just merged in the change to the website.
