### ISSUE TITLE
Update the passwordless setup on Windows 10 for Postgres

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1230]
Current Postgres instructions are using ~/.pgpass
There is a shift to using `pgpass.conf`
Let us include a setup for `pgpass.conf`

Could we try these instructions.

Entering `%APPDATA%` will take you to `C:\Users\username\AppData\Roaming`. Once you get there you need to create the `postgresql` directory and then create `pgpass.conf` inside it

**Comment by harshitbansal05** [comment]
@henrykironde can I work on this?

**Comment by henrykironde** [comment]
Yes please do

**Comment by piyushchauhan** [comment]
If this issue in not fixed can I work on this? @henrykironde  @harshitbansal05

**Comment by harshitbansal05** [comment]
@piyushchauhan I have partially worked on it.
