### ISSUE TITLE
Add in logic for when to check_for_updates

### ISSUE THREAD

**Issue by zhangcandrew** [weecology/retriever#1235]
Running `retriever reset all` after a previous one will cause retriever to download all files again only to be deleted. We should add some logic for when to check_for_updates on startup. 

Related to issue #1229 and PR #1231 

![image](https://user-images.githubusercontent.com/15080652/52377019-a914fd80-2a31-11e9-8758-b3db76733a61.png)

**Comment by ethanwhite** [comment]
Good catch.

**Comment by zhangcandrew** [comment]
Fixed in PR #1231
