### ISSUE TITLE
 duplicate .retriever folders on windows

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/retriever#1239]
there are sometimes that windows machines create a `.retriever` folder in `c:\users\<username>` as well as `c:\users\<username>\documents`

new installation of the development version from github (`pip install git+https://git@github.com/weecology/retriever.git`) on my laptop only creates it in `c:\users\<username>`. 

the first time i run an `rdataretriever::fetch` call in R (using R Console), it creates it in `c:\users\<username>\documents`

**Comment by ethanwhite** [comment]
@juniperlsimonis - thanks again for opening this. Did you find this as an issue when using either the CLI or Python interface or just when using R. My impression from my initial digging into this is that this is an R related issue, in which case I'll move the issue over to https://github.com/ropensci/rdataretriever and get it on my To Do list over there.

**Comment by juniperlsimonis** [comment]
@ethanwhite  I only tried using it through R.

**Comment by ethanwhite** [comment]
Thanks @juniperlsimonis! I'm not seeing this using Python and the CLI on a Windows 10 machine, so I'm going to move it over the `rdataretriever`.
