### ISSUE TITLE
edit_json cannot dump to file correctly

### ISSUE THREAD

**Issue by zhangcandrew** [weecology/retriever#1240]
Looks like the arguments json.dumps takes in have changed within the last year or so. It only takes in 1 positional argument now, whereas before it could take two. Looks like we might have to use json.dump instead. 

Currently when doing an edit_json, I get this error on Ubuntu 18/python 3.7. 

![image](https://user-images.githubusercontent.com/15080652/52660542-de0bcf00-2ecd-11e9-9eb6-e8cec10bd4c5.png)

Looks like it's caused by lines 429/430 in datapackage.py.

**Comment by ashishpriyadarshiCIC** [comment]
Can I work on this?

**Comment by zhangcandrew** [comment]
Sure thing @ashishpriyadarshiCIC!

**Comment by ashishpriyadarshiCIC** [comment]
@zhangcandrew How should I test if the issue is fixed?

**Comment by zhangcandrew** [comment]
The best way to test it is probably just to run through the edit_json. 

type in `retriever edit_json (script_name)` where (script_name) is any script we currently have. For example:

'retirever edit_json iris'

Try to make some changes using the edit_json interface and then when it gets to the end, it should dump out a json instead of erring out like above.

**Comment by zhangcandrew** [comment]
fixed in #1249
