### ISSUE TITLE
Suggesting name change for `testdb` to retriever specific namespace

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1243]
Current tests use` testdb`. 
This is often used by many platforms and many projects.
However, I think it would be a good practice to use a retriever specific namespace for `testdb`,
something like `testdb_retiever` or ...
What do folks think

**Comment by ethanwhite** [comment]
Sounds good to me. Always worth avoiding stepping on other codes toes if possible.

**Comment by harshitbansal05** [comment]
@henrykironde can I work on this one?

**Comment by henrykironde** [comment]
Sure got for it.
