### ISSUE TITLE
Update docs on making scripts.

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1244]
We currently do not need the the extra "urls": {}
For example:
In action-lake 
we have https://github.com/weecology/retriever/blob/master/scripts/acton_lake.json#L104
"urls": {}
We do not need the values 
Let us revise the acton-lake script and update the docs.

**Comment by piyushchauhan** [comment]
I anybody is not assigned can I work on this issue? @henrykironde

**Comment by henrykironde** [comment]
@piyushchauhan, please go ahead and work on the issue.

**Comment by Naba7** [comment]
Can I take up this issue,if no one is working on it

**Comment by henrykironde** [comment]
@Naba7, thank you for your interests in the Retriever project, I think @piyushchauhan is working on this issue. A similar one could be using our new script making tool ref to issue 1254. I have given an abstract explanation but adding a well explained part to the docs, would be nice.

**Comment by Naba7** [comment]
Okay thank you I will be working on that
