### ISSUE TITLE
Raw Github 503 error 

### ISSUE THREAD

**Issue by zhangcandrew** [weecology/retriever#1246]
Looks like we can no longer hit  https ://raw.github.com/weecology/retriever/. This is causing issues with retriever update and check_for_updates. 

The new github raw seems to have this format: https ://raw.githubusercontent.com/weecology/retriever/. 

Not sure if this is a temporary change or not. Changing it over in defaults.py though solves the issue.

**Comment by henrykironde** [comment]
Looks like it is resolved https://twitter.com/githubstatus.

On my side it is working fine
