### ISSUE TITLE
Improve output when connection is not made

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1247]
In both cases (Postgres and MySql), I have no databases up.
A run will finish with a **Done!**. I think we should catch the error and print something that tells the user of no installation made.

`retriever install postgres poker-hands`
```shell
=> Installing poker-hands
Creating database poker_hands...

could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

Installing into existing database
Downloading poker-hand-testing.data: 11.7kB [00:03, 3.52kB/s]
could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

Replacing existing table
could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

Done!
```
`C:\HenryGitHub\retriever [master +1 ~0 -0 !]> retriever install mysql  poker-hands`

```shell
=> Installing poker-hands
Creating database poker_hands...

(1045, "Access denied for user 'root'@'localhost' (using password: NO)")
Installing into existing database
(1045, "Access denied for user 'root'@'localhost' (using password: NO)")
Replacing existing table
(1045, "Access denied for user 'root'@'localhost' (using password: NO)")
Done!
```

**Comment by ashishpriyadarshiCIC** [comment]
@henrykironde So it means to remove the message `Done!` with a descriptive message in case installations fails? If that is the case can I work on it?

**Comment by henrykironde** [comment]
It should be something like connection failed. We  seem like we are not catching the connection failure error.
and we should not see that Done, coz we shall return on a failed connection.

**Comment by ashishpriyadarshiCIC** [comment]
So it should run a loop until it connects or there is a keyboard interrupt.

**Comment by henrykironde** [comment]
Not sure if that is what we should do. 
For MySQL and PostgresDB, the API drivers have a connection type of looping done to get the connection values. And if the looping goes on beyond a default timeout value, then a connection failed signal is sent stdout. 

Best place is to start in the get connect methods and play around with some code
may be some thing like 
```python 
try:
    # someconnection methods        
except Exception as e:
    print (e)
```

**Comment by ashishpriyadarshiCIC** [comment]
I understand. I will start working on it right away

**Comment by henrykironde** [comment]
@ashishpriyadarshiCIC , ref #1255 yes we shall need to catch this error

```j
could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
```

**Comment by p-murli** [comment]
Hey, is this issue open and can I take it up? I'm a newcomer so could you give me a few pointers on how to get started?

**Comment by ethanwhite** [comment]
Hi @p-murli. Welcome to the retriever team! This issue is already being worked on in #1281. If you have questions about starting to engage with the project I'd recommend stopping by the Gitter channel (https://gitter.im/weecology/retriever) and introducing yourself and folks can help from there.
