### ISSUE TITLE
Using datasets

### ISSUE THREAD

**Issue by scls19fr** [weecology/retriever#1262]
Hello,

According description of this repository

    Quickly download, clean up, and install ecological datasets into a database management system

with this tool, we should be able to quickly download, clean up, and install datasets, unfortunately, according documentation, it doesn't seems very clear (at least to me) that being able to easily "use" a dataset is a goal of this project.

By "using", I mean for example being able to simply get 
- a Python [Pandas](https://pandas.pydata.org/) DataFrame (for tabular data)
- an [xarray](http://xarray.pydata.org/en/stable/) dataset (for n-dimensional data)
- a [Blaze](https://github.com/blaze/blaze) Data

from a dataset name.

Let's take an example (inspired by retriever documention) storing dataset to CSV

```python
In [1]: import retriever as rt

In [2]: import pandas as pd

In [3]: pd.set_option("max_rows", 10)

In [4]: engine = rt.install_csv("wine-composition")
Installing ./wine_composition_WineComposition.csv: 100%|████████████████████████████████████████████████████████████| 178/178 [00:00<00:00, 3980.22rows/s]

In [5]: pd.read_csv(engine.file.name)
Out[5]:
     alcohol  malic_acid   ash  alcalinity_of_ash  magnesium   ...     proanthocyanins  color_intensity    hue  od280_od315_of_diluted_wines  proline
0          1       14.23  1.71               2.43       15.6   ...                0.28             2.29   5.64                          1.04        3
1          1       13.20  1.78               2.14       11.2   ...                0.26             1.28   4.38                          1.05        3
2          1       13.16  2.36               2.67       18.6   ...                0.30             2.81   5.68                          1.03        3
3          1       14.37  1.95               2.50       16.8   ...                0.24             2.18   7.80                          0.86        3
4          1       13.24  2.59               2.87       21.0   ...                0.39             1.82   4.32                          1.04        2
..       ...         ...   ...                ...        ...   ...                 ...              ...    ...                           ...      ...
173        3       13.71  5.65               2.45       20.5   ...                0.52             1.06   7.70                          0.64        1
174        3       13.40  3.91               2.48       23.0   ...                0.43             1.41   7.30                          0.70        1
175        3       13.27  4.28               2.26       20.0   ...                0.43             1.35  10.20                          0.59        1
176        3       13.17  2.59               2.37       20.0   ...                0.53             1.46   9.30                          0.60        1
177        3       14.13  4.10               2.74       24.5   ...                0.56             1.35   9.20                          0.61        1

[178 rows x 13 columns]
```

but it's harder from json...

```python
engine = rt.install_json("wine-composition")
```

`retriever.engines.jsonengine.engine` doesn't seem to keep filename (`./wine_composition_WineComposition.json`) at least not in a similar manner than `retriever.engines.csvengine.engine` (`engine.file.name` doesn't exist)

Fortunately we can do:

```python
pd.read_json("./wine_composition_WineComposition.json")
```

but that's not a very convenient approach...

I think that engine could provide `to_pandas` (and even `to_xarray`, `to_blaze` ...) methods.

What is your opinion about this?

Kind regards

**Comment by ethanwhite** [comment]
Hi @scls19fr - thanks for your thoughts on this. We really appreciate the feedback and definitely want to support the "using" side of things.

At the moment that is handled through the `fetch()` function. This function goes through the installation process and then loads the data into a dictionary of pandas data frame (one data frame per table).

 ```python
In [1]: import retriever as rt                                                                                                                                                                                     

In [2]: wine_data = rt.fetch("wine-composition")                                                                                                                                                                   
Installing wine_composition_WineComposition: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 178/178 [00:00<00:00, 16478.38rows/s]

In [3]: wine_data['WineComposition'].head()                                                                                                                                                                        
Out[3]: 
   alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  od280_od315_of_diluted_wines  proline
0        1       14.23  1.71               2.43       15.6          127.0        2.80                  3.06             0.28             2.29  5.64                          1.04        3
1        1       13.20  1.78               2.14       11.2          100.0        2.65                  2.76             0.26             1.28  4.38                          1.05        3
2        1       13.16  2.36               2.67       18.6          101.0        2.80                  3.24             0.30             2.81  5.68                          1.03        3
3        1       14.37  1.95               2.50       16.8          113.0        3.85                  3.49             0.24             2.18  7.80                          0.86        3
4        1       13.24  2.59               2.87       21.0          118.0        2.80                  2.69             0.39             1.82  4.32                          1.04        2
```

There are two steps that go into this, first an SQLite install and then loading all of the tables into a dictionary of data frames from that SQLite install.

We've talked about expanding the functionality of `fetch` to allow different backends and storing the data locally to the project. This could include different formats to load the data in:

```
wine_data = rt.fetch("wine-composition", type = "xarray")
```

I'd also like it to support different backends so that the database backends so that the installed data can be stored somewhere other than in a (currently temporary) SQLite database. For example, storing the data in JSON and caching a local copy of those JSON files in the working directory:

```
wine_data = rt.fetch("wine-composition", engine = "json", cache = True)
```

Is this the kind of functionality you're interested in?

**Comment by henrykironde** [comment]
Thanks @scls19fr for this great issue. 
What the retriever does is download the data into your desired databases. 
The returned engine object is a function used for testing. However in the current dev we are improving things and we could document how to get the paths of the cleaned and installed datasets.

**Comment by henrykironde** [comment]
Thanks for this issue and contributing to the project, we really appreciate. We have this handled to our best at the moment and we hope to improve later
