### ISSUE TITLE
Avoid the use of `raise`

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1265]
We should re visit error handling. The use of raise should be avoided and we should user return.
This is because raising will terminate the interpret and this will cause some of the tools using retriever to stop processing. Returning gives the users a chance to control the flow of execution.

**Comment by Jaffrey98** [comment]
@henrykironde Can I take up this issue?

So basically every raise has to be replaced by a return?

**Comment by henrykironde** [comment]
Hi @Jaffrey98 welcome to the Data retriever. 

> So basically every raise has to be replaced by a return?

 In good well designed way with example to support the change.
Just a replacement may become terrible .

**Comment by scls19fr** [comment]
One Python motto is "Ask forgiveness not permission", so raising exception is completely part of the design of the language. Why not just catching exceptions?

**Comment by henrykironde** [comment]
Since raise shows the error trace, We could probably add raise to debug
 ```python
if debug:
    raise
```

**Comment by scls19fr** [comment]
```python
traceback.format_exc()
```

could help

**Comment by Jaffrey98** [comment]
> Since raise shows the error trace, We could probably add raise to debug
> 
> ```python
> if debug:
>    raise
> ```

👆  This is added in some places in the codebase.

I didn't fully understand why raise is an issue, as most likely the code written after it is usually dependent on successful execution of previous code. 
For eg: - (in `retriever\retriever\__main__.py`)
```python
if args.dataset is not None:
    scripts = name_matches(script_list, args.dataset)
else:
    raise Exception("no dataset specified.")
```
Here as dataset  is not specified further execution doesn't make sense.

If possible an _explanation_ with an _example from the codebase_ would be appreciated 😅

**Comment by scls19fr** [comment]
Maybe this issue should be considered with #151 (logging)

**Comment by henrykironde** [comment]
@Jaffrey98,In case of a failing code, one can run it with debug=True, we expect it to print most of the errors and also most processes to get a clear picture of what is happening. We actually should limit raising in normal code flow. 

Why is this an issue: Take an example of Reticulate in R library. 
 Reticulate will interface with a python program, but whenever something fails in the python program side,  Python will send a signal to Reticulate which will stop the entire program. 


```R
library(reticulate)
check__import = function(){
  # Check if reticulate can import retriever
  tryCatch(
      {imported_retriever = reticulate::import('PyMySQL')},
      error=function(error_message) {
    
      # do some computing
      # like checking Postgres server, which will fail
      # if server does not respond, move on to some  other process

      message("The python module PyMySQL was not found")
      message("Full error trace:")
      message(error_message)
      return(NA)
    }
  )
}
```
In this case if the python module PyMSQL fails, it raises, which causes reticulate to shut down R as per my testing. 

We want to avoid such cases in the tool. I think we should rather catch the exception, print out and lead the program to return back. If I use the interface and None is returned, I should know that something did not execute. 

I could then re run the program with debug flag to raise and print out all the trace

**Comment by henrykironde** [comment]
Thank you @sahiljajodia01, for the interest to contribute to the Data retriever. This issue is already work-in-progress with a PR up. Look through the issues list for issues tagged `getting-started`. We also welcome anyone to open new issues for new ideas.
