### ISSUE TITLE
fetch method should return an ordered dict (not a dict)

### ISSUE THREAD

**Issue by scls19fr** [weecology/retriever#1266]
Hello,

I noticed that `fetch` method returns a dict of dataframes.
To preserve order of tables (which may have a meaning) it should return an ordered dict.
[Datapackage](https://frictionlessdata.io/specs/data-package/) ressources are stored in a list so it's ordered.

Kind regards

**Comment by henrykironde** [comment]
That would  be great  👍 @scls19fr

**Comment by Jaffrey98** [comment]
@henrykironde  @scls19fr 
For this to be implemented are the following changes enough in `retriever\retriever\engines\sqlite.py` ?

```diff
+from collections import OrderedDict

@@ -44,10 +45,10 @@ class engine(Engine):
     def fetch_tables(self, dataset, table_names):
         """Return sqlite dataset as list of pandas dataframe."""
         connection = self.get_connection()
-        data = {table[len(dataset) + 1:]: pd.read_sql_query("SELECT * "
+        data = OrderedDict({table[len(dataset) + 1:]: pd.read_sql_query("SELECT * "
                                                             "FROM {};".format(table),
                                                             connection)
-                for table in table_names}
+                for table in table_names})
         return data
```

**Comment by henrykironde** [comment]
Thank @Jaffrey98, I am not sure, we shall have to test this. Could you put in a PR and we could follow up with some testing.

**Comment by Jaffrey98** [comment]
Sure !
