### ISSUE TITLE
fetch method should preserve order

### ISSUE THREAD

**Issue by scls19fr** [weecology/retriever#1271]
Following https://github.com/weecology/retriever/issues/1266 (because I can't reopen issue)
because https://github.com/weecology/retriever/pull/1267 doesn't fix it (I'm pretty sure)

See https://github.com/weecology/retriever/pull/1267#issuecomment-469147555

**Comment by henrykironde** [comment]
Thanks @scls19fr, Could we get an example of the order to be preserved

**Comment by scls19fr** [comment]
Sorry but I can't do it now, I'm moving (using my phone)

You just need to create a sample dataset with tables not alphabetically ordered to catch this.

**Comment by harshitbansal05** [comment]
@henrykironde I think that scls19fr is absolutely right. Reference: https://stackoverflow.com/questions/15711755/converting-dict-to-ordereddict. The dictionary passed to the Ordered Dict as an argument is inherently not ordered, so the the `ordered dict` would also not be ordered. It should be solved by passing tuples of key, value pairs. If possible, can I work on it?

**Comment by henrykironde** [comment]
I see what you mean and thank you for the explanation folks, I think what it is doing now is keeping the order of tables as they are given in the script. If we want to produce a new ordering, we can add a feature for that where we do some fetch or fetch ordered. Hope I am right. Feel free to put in a PR.

**Comment by Jaffrey98** [comment]
@harshitbansal05 Yes I agree, it seems it slipped my mind that I was actually doing a `normal dictionary comprehension`  inside `OrderedDict()`. Thank you for the FIX 😄

**Comment by Jaffrey98** [comment]
@harshitbansal05 
It seems it isn't necessary to wrap the `comprehension` in `square brackets` , not that it changes the execution. Just wanted to mention it 😅 

> Both work the same
```python
data = OrderedDict([
            (table[len(dataset) + 1:],
            pd.read_sql_query(sql_query.format(table), connection))
            for table in table_names
        ])
```
```python
data = OrderedDict(
            (table[len(dataset) + 1:],
            pd.read_sql_query(sql_query.format(table), connection))
            for table in table_names
        )
```

**Comment by henrykironde** [comment]
I think what @scls19fr wants is to do a sort on the table here `for table in table_names`

**Comment by harshitbansal05** [comment]
@Jaffrey98 I had noticed that but had put the square brackets anyway. @henrykironde IMO, no. We were initially creating the dictionary with (table_name, table) as (k, v) pairs. Now, if I had to loop across all the keys of the dictionary by `for k in dict:`, the ordering of the keys(tables) would not be the same as when we inserted the keys into the dictionary. This is because the dictionary calculates a hash for each key and stores the values based on the hash. With ordered dict, the order remains preserved.

**Comment by Jaffrey98** [comment]
@henrykironde According to me, this is what @scls19fr expects : 

I am using the analogy of `rows` for `tables` and `table` for `table_names` as in the actual code the `key` is the `table_name` and value is the `dataframe` consisting all rows in that table.

If a table like 👇  exists:

| id  | fname | lname |
|----| ------- |-------|
|  1  |   john  |  doe  |
|  2  |   jane  |   doe  |

If a **normal** `dict` comprehension is used in the` fetch_tables` , method it is possible that when performing `dict_name.items()` ,  it **may not** return a list of key value pairs in  the the same order in which it was inserted, as in the above table i.e. row with `id = 2` comes after row with `id = 1`. The technical reason for this, given by @harshitbansal05 is what I agree with.

The `OrderedDict` ensures that it will return the list of key value pairs in the order it was inserted i.e. row with `id = 2` will always be in the list of key value pairs after row with `id = 1`.

**Comment by henrykironde** [comment]
> it may not return a list of key value pairs in the the same order in which it was inserted

I think you want the data to be in order 
for example in the table, order is `id, first, last ` > in dataframe order should be  `id, first, last `
I do recommend that we changing
```
    def fetch_tables(self, dataset, table_names):
        """Return sqlite dataset as list of pandas dataframe."""
        connection = self.get_connection()
        sql_query = "SELECT * FROM {};"
```
SQL  select * will return the tables not in any order  
we should change  to select columns of the given table in that script

**Comment by henrykironde** [comment]
Thanks @harshitbansal05, I think it will be very good if we get a review from @scls19fr.
I do not think this solves the issue number 1271,  so we should remove the tag 1271.
Waiting for @scls19fr 's recommendation.

**Comment by scls19fr** [comment]
LGTM
Thanks @harshitbansal05 @Jaffrey98 and @henrykironde
