### ISSUE TITLE
Plan to Drop Python 2

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1277]
We are happy to announce that we are planning to drop python 2. 
However we shall need to do this is steps.
We plan to follow test driven development in this shift

The main areas of python 3 are the unicodes  I believe we should create tests first and them move to changes in code and structure.

- [ ] Create retriever test sets for python 3 only.
        I think we shall create a copy of `test_retriever.py` we can call it something like `test_retriever_p_three.py`  and one for integration test. The files will be only run on python3 environment. 

- [ ] Create a sample unicode data sets and find the best encoding
     Some contributors have suggested UTF-8
     **_references:_**
      latin-1 -> utf-8 / Python 2.7 support #1276
      All encoding issues: https://github.com/weecology/retriever/search?q=encoding&type=Issues
- [ ] Remove code related to python2. This includes checks against the versions and Python2 related code, Future, etc

**Please feel free to add or remove anything.** 
Other things to discus: when to drop Python2

**Comment by harshitbansal05** [comment]
@henrykironde can I work on one of these?

**Comment by henrykironde** [comment]
Please go a head.

**Comment by Jaffrey98** [comment]
I too would like to work on this @henrykironde

**Comment by henrykironde** [comment]
Yes both of you can corroborate  on this. In case both of you are working on the same think you could make PR to each other and then later create one PR to master.
Also, It would be good to discus the design and the parts you are each working on among yourselves. 
 Whichever way you would want to solve this.
`if `sys.version_info >= (3, 0, 0):``

**Comment by Jaffrey98** [comment]
@henrykironde I had a discussion with @harshitbansal05. He is taking up the following task:
> Create retriever test sets for python 3 only.
I think we shall create a copy of test_retriever.py we can call it something like test_retriever_p_three.py and one for integration test. The files will be only run on python3 environment.

---

For task2 i.e. 👇 
> Create a sample unicode data sets and find the best encoding
    Some contributors have suggested UTF-8
    references:
    latin-1 -> utf-8 / Python 2.7 support #1276
    All encoding issues: https://github.com/weecology/retriever/search?q=encoding&type=Issues

- I had a look at the issues you linked to but couldn't figure out anything more than "Change default encoding from latin-1 i.e. ISO 8859-1 to UTF-8"
- I also referred the following resources:
https://docs.python.org/3.7/library/codecs.html#standard-encodings
https://www.pythoncentral.io/encoding-and-decoding-strings-in-python-3-x/
- In python 3 the default encoding is set to "utf-8" , to change the encoding you need to set an environment variable called `PYTHONIOENCODING`, a [workaround](https://stackoverflow.com/questions/12819099/change-encoding-of-stdin-stdout-at-runtime-in-python-3) to change encoding through code exists, but has some _gotchas_ .
- Could you elaborate more on what exactly are you expecting ?

---

Also it seems task 3 needs more discussion and has to be **incrementally done** , as according to me it involves _breaking changes_ / _backward compatibility issues_.
task 3 being:-
> Remove code related to python2. This includes checks against the versions and Python2 related code, Future, etc

**Comment by henrykironde** [comment]
@Jaffrey98, If you take a look at the code, you will see that we have the default encoding set to `# -*- coding: latin-1  -*-` and like 
issue 1276 states, we need to change that.

**Comment by Jaffrey98** [comment]
Thanks for the patient @henrykironde 😅. Will start working on **task2** right away. 🚀

**Comment by henrykironde** [comment]
No question is unnecessary. 👍

**Comment by scls19fr** [comment]
Searching for [sys.version_info](https://github.com/weecology/retriever/search?q=sys.version_info) could help

**Comment by hugovk** [comment]
https://github.com/asottile/pyupgrade is a useful tool for upgrading Python syntax for newer versions. For example:
```
pip install pyupgrade
pyupgrade `find . -name "*.py" -type f` --py3-plus
```

**Comment by hugovk** [comment]
A good tip for ensuring whole pipelines don't fall apart, is to include an argument like this in the call to `setup()` in `setup.py`:

```python
python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*',
```

This ensures that pip only installs the right version of a package for the user's running Python version. In this example, 2.7 and 3.3+ are supported.

When dropping Python 2, use something like this for 3.3+:

```python
python_requires='>=3.3',
```

**Comment by Jaffrey98** [comment]
@henrykironde For task2 do we need to change the value of `ENCODING` variable in [`/retriever/lib/defaults.py` ](https://github.com/weecology/retriever/blob/master/retriever/lib/defaults.py#L10) ?

Also there are other references where `latin-1`  is being used for decoding and encoding like in: 
- [`retriever/lib/scripts.py`](https://github.com/weecology/retriever/blob/master/retriever/lib/scripts.py#L166)
- [`retriever/lib/tools.py`](https://github.com/weecology/retriever/blob/master/retriever/lib/tools.py#L60)
- [`retriever/try_install_all.py`](https://github.com/weecology/retriever/blob/master/retriever/try_install_all.py#L22)

Do they require changing too?

I have created a PR for task2 #1279 , but it seems tests are failing on python2.
Is this good news because our goal is to drop python2 support?

**Comment by henrykironde** [comment]
I have created a branch to work towards dropping Python2 https://github.com/weecology/retriever/tree/python3_and_pep8

@scls19fr, could you please PR your previous PEP8 changes to this branch in case you have time else I go ahead and clean them up on your behalf. PR https://github.com/scls19fr/retriever/pull/1

@Jaffrey98 
> Is this good news because our goal is to drop python2 support? 

The tests will probably fail on Python 2 and we should remove the testing on Python2 later in the travis file. There is a way to allow failure for a given env, in this case python "2.7" using `allow_failures:`

It is good to understand why Python2 fails because it is key to making sure that we change to python3 in the best way.

> For task2 do we need to change the value of ENCODING variable in /retriever/lib/defaults.py ?

I guess that will need to change to UTF-8

**Comment by scls19fr** [comment]
Hi,

I'm very busy for the 2-3 next following weeks.
So go ahead guys!

Kind regards
