### ISSUE TITLE
JSON file generated using install json is not pretty

### ISSUE THREAD

**Issue by apoorvaeternity** [weecology/retriever#1285]
The .json file generated when installing datasets into json is not pretty.

For example, consider abalone-age-

The output file generated when using 'retriever install json abalone-age` looks like:
![current_look](https://user-images.githubusercontent.com/21103831/54385322-5aa3f000-46bc-11e9-8ccd-6679462f4f37.png)

The size of this file is 726.5 kB.

The output file when setting the indentation of json to 2:
![Screenshot from 2019-03-15 00-54-56](https://user-images.githubusercontent.com/21103831/54385582-fa617e00-46bc-11e9-919c-f076c186fe46.png)

The size of this file is 810.1 kB.

It would be great if we have an option of setting the indentation and sorting the keys
 `retriever install json abalone-age --sort-keys --indent 2` to increase the readability of the json file.
I am aware that we keep the json files the way it is right now to reduce the file size but again these new options are optional. When installing the `abalone-age` to `xml` it takes 1.3 MB.
It would be nice if we let the user decide upon the tradeoff between file size and readability.

@ethanwhite @henrykironde Your views on this?
If you like it I will send a PR for this.

**Comment by ethanwhite** [comment]
Thanks @apoorvaeternity. I think this is an important point. Are most data produced by other folks that are stored in JSON stored in the pretty format?

**Comment by apoorvaeternity** [comment]
I personally don't know about good JSON dataset providers.
I just googled `datasets in json` and found some of these sites and most of their datasets were indented:
https://catalog.data.gov/dataset?res_format=JSON
https://json-datasets.zeef.com/jdorfman
https://data.world/datasets/json

Even `Django` allows dumping of data from database in JSON format with the option of setting the indentation.
`python manage.py dumpdata table_name --indent 2 > table_name.json`

Similarly we can have that option here too
`retriever install json abalone-age --indent 2`

Again by default we will store the data like we do it right now but for JSON format this is something that is good to have.

**Comment by henrykironde** [comment]
I think if we add something like that we should use a default indent spacing and no need to provide a 2.

**Comment by ethanwhite** [comment]
Thanks @apoorvaeternity - I definitely agree that this should at least be optional. I asked because if most folks using JSON for data are already using pretty formatting then I think there's an argument for just making everything pretty. I agree with @henrykironde that we should skip the customization of the indent and using something like  `retriever install json --pretty abalone-age`
