### ISSUE TITLE
Idea for Retriever in Docker

### ISSUE THREAD

**Issue by DumbMachine** [weecology/retriever#1289]
I am proposing the Idea of using Docker along with Retriever to provide easy access to its users. With the help of Docker and Retriever setup, they can directly dive in without having to deal with any hassles of installation of packages or searching for the data. 

There are many libraries which are hard to install for new users or are broken on certain system like Windows (xgboost library). Having a container will take care of this. Since Retriever downloads the data, using the container will give the package independence as User can just choose the docker image for the dataset and on running the container he will have both the packages and dataset up and running for him/her to experiment and play around with.( local Volumes of systems can also be mounted to the container if the user wishes to use his own local data)

This will help developing a pipeline for Data Analysis as all the processing can be done inside the container whose state can be committed to an Image, which can be used latter to continue work from a checkpoint or reproduce the results obtained before, thus helping with consistency.

This pipeline can also be linked to Online Cloud based services like AWS and GCP for doing the processing thus saving time and providing the user an interface to submit jobs easily.

The above can also be linked with Kaggle datasets, with the help of their API, helping our users to get more data sets and a way to submit solutions if wanted. straight from the container.

NOTE: The Idea is still evolving and many things are subject to change after discussion with appropriate individuals.

Below is a small and early visualisation of the Idea in mind.

![image](https://user-images.githubusercontent.com/23381512/54875478-24860f00-4e26-11e9-8450-24dc7b8da356.png)

**Comment by henrykironde** [comment]
Thanks for the Idea, have you looked at the idea `Retriever Provenance`. This is very closely related to `Retriever Provenance` idea. I think it would be great to include the ideas that the Provenance issues are trying to solve. https://github.com/weecology/retriever/search?q=Retriever+Provenance&type=Issues.

And this will scale up the proposal/idea

**Comment by DumbMachine** [comment]
Solution for Provenance can surely be included here. Since the commit of a container creates an image with state same as that of commited container, all e
Command/code will be executed again. This will bring the state of the dataset to the one the author commited. This will work just fine with small datasets as executions on them won't be very time consuming.

For larger datasets we can use git-python and create local git repos for the dataset. This will help with delta checking and increasing speed and efficiency. Each commited version of dataset will be committed in the repo, rpoviding us many information such as time, hash, author etc and after this commit we can store that version to an archive. This will enable for smaller persistent storage.

Using a local repo will give us many opportunities to provide the user with features such as branching( if user desires for multiple working datasets), all information's regarding commits, difference matching.

**Comment by DumbMachine** [comment]
I could provide a more detailed action plan after a few hours when my classes have ended.

**Comment by DumbMachine** [comment]
Since I have decided to apply to a different organization, I won't be able to submit a proposal for the above Idea this time. If you see the potential in the above Idea, I would love it implement it outside of GSOC. If I'm not selected this time for GSOC, I would work on implementing this idea during the summer. If I'm selected I would work on this slowly and steadily on the side.
Do let me know your thoughts about this Idea and if it has a place here. If any points require further explanation, I would love to shed some light on it.

**Comment by henrykironde** [comment]
@DumbMachine, that is totally fine. we shall keep this open.

**Comment by henrykironde** [comment]
I will close this since we have an issue that covers updating the retriever docker image
