### ISSUE TITLE
[discussion] Extract Scripts into a separate system

### ISSUE THREAD

**Issue by harshitbansal05** [weecology/retriever#1290]
Hi, I was looking to work on the GSoC idea "Extract Scripts into a separate system". I researched for the project, and as far as I understand, it requires moving the scripts directory into a new repository for ease of maintenance(users downloading from source have to download the scripts directory as well because it comes with retriever). For moving it into a new repository, there have to be certain changes in the codebase where scripts are updated, edited, etc. However, I find this project somewhat small. Is there something am I missing? Also, please correct me if my understanding of the problem statement is incorrect.

**Comment by harshitbansal05** [comment]
@ethanwhite @henrykironde @zhangcandrew sorry I was a bit involved in my midterm examinations, so could not create an issue earlier. Could you please add your suggestions here?

**Comment by henrykironde** [comment]
I will add Andrew's comments here.

>  So the "Extract Scripts into a seperate system" project has a few more moving parts to it that we'd like to do. It deals a bit with how the retriever currently downloads and keeps track of scripts, how scripts are versioned and listed, portability to some of our other wrapper projects (R and Julia retrievers), and some other bits and pieces I can go into more detail about. If you want to start a discussion issue on retriever, we can talk about it a bit more in depth.

**Comment by zhangcandrew** [comment]
Thanks @harshitbansal05! 

Some of the items we had hoped to tackle with this included:
- Moving all scripts to a separate area (new repository/cloud storage/whatever else sounds good) where it could be separately added to, versioned, and controlled
- Keeping track of scripts that would now be split across three different areas. Retriever looks in two local folders (~/.retriever and local retriever git repo) for scripts, and with this addition, the upstream repo. Among these three areas, it would be useful to keep track of which ones can be used offline (the local folders) and which ones would need to be downloaded (new upstream repo). This is something that was started and could be expanded upon from our retriever dash project (https://github.com/weecology/retrieverdash). 
- Change retriever ls to reflect scripts in different places (see above)
- Restructuring code to not redownload everything unless needed. Right now retriever creates a singleton class which by default downloads all scripts. With the addition of separate scripts, we should be able to check which scripts are available locally and upstream without downloading all the scripts, and ONLY download a script when we want to install from it. Some of our CLI commands also need other information that is embedded in the script which we would ideally be able to retriever without having to download all scripts still. 
- Our Julia and R projects rely on our retriever python project, so there may be some work that needs to be done on those once we move the scripts over. 
- Once we have a separate repo up for scripts, we want to be able to test any modifications of scripts and have simple tests for new scripts. This could be done through new travis/appveyor tests that need to be setup. 
- Contributing to scripts guidelines/docs
- Finally, if we get the chance to, we want to be able to add a flag to download and create scripts that we DON'T currently keep track of (wouldn't be in our script repo). This allows users to leverage the retriever tools on data that is clean but we haven't created a script for. Users should be aware that they are downloading a foreign file though and not one we are maintaining.

**Comment by harshitbansal05** [comment]
@zhangcandrew thanks for the response. I was thinking that rather than searching for scripts in the local git repo and the home dir, we should only look for scripts in the home dir. First I found a shortcoming:
In the current Retriever implementation, if I call `edit_json` for a script, edit it, and then install that dataset while staying in the local git repo, the edited json script would not be considered (instead the script in the scripts folder in the git repo would be considered due to a higher priority in `SCRIPT_SEARCH_PATHS`). Thus how about simply keeping only two tracks of scripts, one in `~/.retriever` and the other online?
@henrykironde @ethanwhite your reviews on this?

**Comment by henrykironde** [comment]
The edit json functionality is mainly for users.
Users do not usually work within the git repo. They install retriever using package manager like pip or conda and will only have one script directory which will be the `~/.retriever/script`

The git repo is mainly for developers.

**Comment by zhangcandrew** [comment]
Thanks for the suggestion @harshitbansal05! A large part of having the scripts folder before was for developmental purposes. If you create a new script and drop it in your git repo’s script folder, when you run `retriever ls`, it will (or should) show up with any changes you made. Since the folder in ~/.retriever is hidden an not front facing, we don’t intend for our users to change or modify it. That folder is special in the sense that raw data is first downloded into that folder before being sanitized by retriever and saved in the proper format the user specified. When we create the separate scripts repo or directory, there’s the intention that we may have many many scripts in there eventually (potentially in the hundreds of thousands). If that were the case, `retriever ls` would be a bit impractical, so the idea of keeping track of 3 locations was to have retriever ship with some “example” scripts

**Comment by harshitbansal05** [comment]
@zhangcandrew @ethanwhite @henrykironde  I have written an initial draft of the proposal and submitted it on the GSoC website. Could you please review it and suggest the possible changes?

**Comment by harshitbansal05** [comment]
Also, @zhangcandrew could you please describe the last point `Finally, if we get the chance to, we want to be able to add a flag to download and create scripts that we DON'T currently keep track of (wouldn't be in our script repo). This allows users to leverage the retriever tools on data that is clean but we haven't created a script for. Users should be aware that they are downloading a foreign file though and not one we are maintaining.`? Should we simply create a function that given a url downloads a script and then allows the use of retriver on it?

**Comment by zhangcandrew** [comment]
Thanks @harshitbansal05, I gave your proposal a look over and suggested some changes!


Also yes, that's exactly what's meant. Retriever scripts currently try to use specs written out by frictionless data (see: https://frictionlessdata.io/data-packages/). Around the internet there are datapackages floating around that follow these specs that we didn't necessarily make. It would be cool to see retriever be able to still manage data delineated in these datapackages that weren't made by us through a command line tool. Something like 

`retriever install csv -u [url]` 

or something.

**Comment by harshitbansal05** [comment]
@zhangcandrew regarding the search of online scripts based on licenses and keywords, I thought of the following solutions:
1. Make a separate file similar to version.txt with two more columns, features and licenses. When a query is made, search this file.
2. Use github's search api. For example, the query `curl https://api.github.com/search/code?q=CC0-1.0+in:file+path:scripts+repo:weecology/retriever` returns the scripts with the license `CC0-1.0`. 
3. Also for licenses, since the number of licenses would be limited, we can create a folder named licenses containing the files like `license1`, `license2` and so on. These files would then contain the script names with those license. 
So, I request you, @henrykironde to tell your views on this.

**Comment by harshitbansal05** [comment]
@zhangcandrew I have also made some key design changes based on your suggestions. I request you to have a look at them.

**Comment by harshitbansal05** [comment]
@zhangcandrew sorry, but I could see only one comment on the doc. Are the design changes for the second and third task fine?

**Comment by zhangcandrew** [comment]
Putting this in here to keep track of things. @harshitbansal05, feel free to use this if it helps you too

- [ ] Moving all scripts to a separate area (new repository/cloud storage/whatever else sounds good) where it could be separately added to, versioned, and controlled
- [ ] Create CLI for retriever-recipes [WIP]
- [ ] Keeping track of scripts that would now be split across three different areas. Retriever looks in two local folders (~/.retriever and local retriever git repo) for scripts, and with this addition, the upstream repo. Among these three areas, it would be useful to keep track of which ones can be used offline (the local folders) and which ones would need to be downloaded (new upstream repo). This is something that was started and could be expanded upon from our retriever dash project (https://github.com/weecology/retrieverdash).
- [ ] Change retriever ls to reflect scripts in different places (see above)
- [ ] Restructuring code to not redownload everything unless needed. Right now retriever creates a singleton class which by default downloads all scripts. With the addition of separate scripts, we should be able to check which scripts are available locally and upstream without downloading all the scripts, and ONLY download a script when we want to install from it. Some of our CLI commands also need other information that is embedded in the script which we would ideally be able to retriever without having to download all scripts still.
- [ ] Our Julia and R projects rely on our retriever python project, so there may be some work that needs to be done on those once we move the scripts over.
- [ ] Once we have a separate repo up for scripts, we want to be able to test any modifications of scripts and have simple tests for new scripts. This could be done through new travis/appveyor tests that need to be setup.
- [ ] Contributing to scripts guidelines/docs

  - [ ] Add in docs for scripts in retriever-recipes
  - [ ] Change datasets.rst appropriately
  - [ ] Make other necessary changes to retriever docs

- [ ] Finally, if we get the chance to, we want to be able to add a flag to download and create scripts that we DON'T currently keep track of (wouldn't be in our script repo). This allows users to leverage the retriever tools on data that is clean but we haven't created a script for. Users should be aware that they are downloading a foreign file though and not one we are maintaining.

**Comment by ethanwhite** [comment]
First off - I'd just like to say that I'm super impressed with all of the work and thought that's been happening on this. It's so exciting to see this GSOC project making such great progress.

Given the length of the To Do list I thought I'd mention that I think that "Restructuring code to not redownload everything unless needed" might be something to consider placing lower down on the priority list. Other package managers (e.g., apt on Debian/Ubuntu) require an update step that pulls down up-to-date information on packages locally and takes a while to run (certainly longer than our updates). We already only update changed scripts, so the only time there's a meaningful download is on the initial setup or after a `reset`. For most users this will be very infrequent. Given that I think this is the lowest priority on the list. That said, this is more of an outsider's take, so whatever @zhangcandrew @henrykironde & @harshitbansal05 think is best is good with me.
