### ISSUE TITLE
[discussion] Retriever Out of Memory Functionality

### ISSUE THREAD

**Issue by coolalexzb** [weecology/retriever#1298]
Hi, I am eager to work on the GSoC idea called "Extract Scripts into a separate system". I have added some parts of LTREB datasets to retriever and tried to download and install large vertnet datasets.  The download function takes several minutes as for vertnet datasets, while it seems related to the speed of network. Both download and install function can work for large datasets but it takes long time. I also find a similar idea called "Improve Data Retriever efficiency for out-of-memory scale datasets" from Gsoc 2018. So, is the idea of the project to speed up the install function and add indexes to database and enhance efficiency of query? As for the idea in 2019, I want to know more details about "process datasets in a manner that does not involve us downloading all the data before we want to work with it". Thanks! @henrykironde @ethanwhite @zhangcandrew

**Comment by henrykironde** [comment]
> So, is the idea of the project to speed up the install function.

Yes, after downloading we need to speed up more processing.
We also want to make sure that when we are dealing with large files, bigger than the vertnet, we do not take that long and we make sure we do not run out of memory. Have you tried `retriever fetch` on the main vertnet

Also have a look at this
Ref: https://github.com/weecology/retriever/issues/1112

**Comment by coolalexzb** [comment]
> > So, is the idea of the project to speed up the install function.
> 
> Yes, after downloading we need to speed up more processing.
> We also want to make sure that when we are dealing with large files, bigger than the vertnet, we do not take that long and we make sure we do not run out of memory. Have you tried `retriever fetch` on the main vertnet
> 
> Also have a look at this
> Ref: #1112

**Comment by coolalexzb** [comment]
It seems that retriever fetch is not a valid command. 
![2019-03-30 12-44-52屏幕截图](https://user-images.githubusercontent.com/19755247/55271571-b63fc180-52e9-11e9-9ccc-df5953f975a1.png)

**Comment by coolalexzb** [comment]
It seems that retriever fetch is an invalid command.  @henrykironde 
![2019-03-30 12-44-52屏幕截图](https://user-images.githubusercontent.com/19755247/55271577-dd968e80-52e9-11e9-9fca-24152c45c0ce.png)

**Comment by ethanwhite** [comment]
fetch is only available in the Python interface, not the command line interface. 

In Python try:

    import retriever as rt
    rt.fetch(“mammal-masses”)

**Comment by coolalexzb** [comment]
I tried run rt.fetch("vertnet"), this command got out-of-memory in my PC, and I tried rt.fetch("vertnet-fishes") instead, however, it went corrupted as well. I read the source code of fetch, I found that it implemented download and install function, but I was confused that why I could use download and install function by command retriever download and retriever install for vertnet dataset.  I also installed Profiler but  I could not view the result for large datasets because the command corrupted before the result displayed. So, I think maybe  I could use small datasets instead to find the bottleneck of the function. The problem is that the stdout cannot show all of the information of profiler, and I write the result to a .dmp file but it gets messy code in the file. I tried runSnake. Unfortunately, it cannot work well for python3.x. Could you provide me some information about the bottleneck of the function or the tools to view the profiler result? Thank you! @henrykironde  @ethanwhite

**Comment by henrykironde** [comment]
What you have encountered is the problem that we want to solve.
Processing of large data files without putting everything in memory.

**Comment by coolalexzb** [comment]
I used profiler to visualize the usage of memory. `df = sqlite.fetch_tables(dataset, db_table_names)` in fetch function and 
```
data = OrderedDict([
                    (table[len(dataset) + 1:],
                    pd.read_sql_query(sql_query.format(table), connection))
                    for table in table_names
               ])
``` in fetch_table function need large memory. 
I am trying to set chunksize in `pd.read_sql_query()` function to control the number of rows to read each time and we will get an iterable set of data as a result.
Another point is that the installing speed gets slower compared when dealing with large datasets(speed of row/s), I am trying to discover the reason of the phenomena and find approaches to improve the speed of installing. 
At present, I think that the goal of the idea is to enhance the speed of install function and avoid out of memory function when processing large datasets under various types of database. I am ready to write proposal, and I also want to know more requirement of the idea to enrich my proposal, then I could search information to help solve all the problems. Now, I think I cannot solve all the problems immediately. Could you provide me some suggestion to write a qualified proposal? Thank you! @henrykironde @ethanwhite

**Comment by coolalexzb** [comment]
I used profiler to visualize the usage of memory. df = sqlite.fetch_tables(dataset, db_table_names) in fetch function and

```
data = OrderedDict([
                    (table[len(dataset) + 1:],
                    pd.read_sql_query(sql_query.format(table), connection))
                    for table in table_names
               ])
``` in fetch_table function need large memory. 
I am trying to set chunksize in `pd.read_sql_query()` function to control the number of rows to read each time and we will get an iterable set of data as a result.
Another point is that the installing speed gets slower compared when dealing with large datasets(speed of row/s), I am trying to discover the reason of the phenomena and find approaches to improve the speed of installing. 
At present, I think that the goal of the idea is to enhance the speed of install function and avoid out of memory function when processing large datasets under various types of database. I am ready to write proposal, and I also want to know more requirement of the idea to enrich my proposal, then I could search information to help solve all the problems. Now, I think I cannot solve all the problems immediately. Could you provide me some suggestion to write a qualified proposal? Thank you! @henrykironde @ethanwhite

**Comment by coolalexzb** [comment]
I used profiler to visualize the usage of memory. `df = sqlite.fetch_tables(dataset, db_table_names) `in fetch function and
```

data = OrderedDict([
                    (table[len(dataset) + 1:],
                    pd.read_sql_query(sql_query.format(table), connection))
                    for table in table_names
               ])
```
in fetch_table function need large memory. 
I am trying to set chunksize in `pd.read_sql_query()` function to control the number of rows to read each time and we will get an iterable set of data as a result.
Another point is that the installing speed gets slower compared when dealing with large datasets(speed of row/s), I am trying to discover the reason of the phenomena and find approaches to improve the speed of installing. 
At present, I think that the goal of the idea is to enhance the speed of install function and avoid out of memory function wh

**Comment by coolalexzb** [comment]
I used profiler to visualize the usage of memory. `df = sqlite.fetch_tables(dataset, db_table_names) `in fetch function and
```
data = OrderedDict([
                    (table[len(dataset) + 1:],
                    pd.read_sql_query(sql_query.format(table), connection))
                    for table in table_names
               ])
```
in fetch_table function need large memory.
I am trying to set chunksize in pd.read_sql_query() function to control the number of rows to read each time and we will get an iterable set of data as a result.
Another point is that the installing speed gets slower compared when dealing with large datasets(speed of row/s), I am trying to discover the reason of the phenomena and find approaches to improve the speed of installing.
At present, I think that the goal of the idea is to enhance the speed of install function and avoid out of memory function when processing large datasets. I am ready to write a proposal. To write a qualified proposal, could you provide me more reqirement of the idea and some suggestions to write a proposal? Thanks! @henrykironde

**Comment by henrykironde** [comment]
> some suggestions to write a proposal? 

https://google.github.io/gsocguides/student/proposal-example-2.html

> I think that the goal of the idea is to enhance the speed of install function and avoid out of memory function when processing large datasets. I am ready to write a proposal. To write a qualified proposal, could you provide me more reqirement of the idea 

You need to figure out some of those areas that need to be changed so that we can handle the large data sets

**Comment by coolalexzb** [comment]
I have wrote most part of my proposal. In the first two month, I decided to solve the problem of out of memory mainly by the usage of lazy computation mimicing the thoughts of Resilient Distributed Dataset(RDD) in spark and dividing datasets in several parts and process them sepearate when real computaion happen.  For large dataset, users are required to use sql command first  and I  decided to write semantic analysis function to simplify sql command and load less data to memory. Now, I want to know some more possible action by users, which might bring out out of retirever problems. I am also eager to speed up install function, while besides due to the volume, I do not find other possible causes. Could you provide me some suggestions to fill the work in third month? Thank you! @henrykironde

**Comment by henrykironde** [comment]
Can I see the proposal. You can upload it on the GSOC page as a doc, I will be able to see it

**Comment by coolalexzb** [comment]
I shared my draft with you and @ by your email. Some parts have not been filled yet and I will fill it soon. Thanks! @henrykironde

**Comment by henrykironde** [comment]
I have finished adding comments

**Comment by coolalexzb** [comment]
My draft has been uploaded and this is my final draft. Please give me some suggestions and guide. Thank you! @henrykironde

**Comment by henrykironde** [comment]
Looks ready, go ahead and submit

**Comment by henrykironde** [comment]
We need to recreate this when we have a better example of such data
