### ISSUE TITLE
Redundant functions in tools.py and scripts.py

### ISSUE THREAD

**Issue by harshitbansal05** [weecology/retriever#1299]
The functions `open_fr`, `open_fw`, `open_csvw`, and `to_str` are present in both tools.py and scripts.py. Can't we simply implement them in only one file, maybe tools.py? Please correct me if there's a reason behind doing so.

**Comment by henrykironde** [comment]
These functions are tailored to handle all sorts of file opening on multi platforms. We use the ones in the `scripts.py` module as part of the core functionality and tools as helper function (including testing).

The reason we are separating is to avoid circular dependencies. However, feel free to change the orientation/design where applicable.
