### ISSUE TITLE
Error when running retriever license with no dataset as argument

### ISSUE THREAD

**Issue by apoorvaeternity** [weecology/retriever#1308]
Currently, when running `retriever license` and providing no dataset as an argument it results into `KeyError: 'No dataset named: None'`
![retriever_ls](https://user-images.githubusercontent.com/21103831/56208546-069b7b00-606f-11e9-84e5-9952be6cc097.png)

In case of `retriever citation` if no dataset is given we show the citation for retriever. 
![retriever_ct](https://user-images.githubusercontent.com/21103831/56208927-ef10c200-606f-11e9-89aa-056c1c126e33.png)

How should we handle this? Show the license for retriever by reading the `LICENSE` file or create a new `LICENSE` variable in `retriever.lib.defaults` and show it?

**Comment by zhangcandrew** [comment]
Hey @apoorvaeternity thanks for catching this!

I think we should keep with convention and create a LICENSE variable in defaults to show.
