### ISSUE TITLE
Urgent linux help: Auto complete failing

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1318]
Is anyone getting an error related to
activate-global-python-argcomplete ,  eval "$(register-python-argcomplete retriever)"
When you run `python setup.py install` or `build.sh`

**Comment by zhangcandrew** [comment]
I just tried it out and I'm getting an Errno 13 Permission Denied error

**Comment by henrykironde** [comment]
Seems to be working, tested by @zhangcandrew and thank you.
