### ISSUE TITLE
[Bug] Data transformations with install_csv

### ISSUE THREAD

**Issue by ha0ye** [weecology/retriever#1322]
I noticed that data was importing slightly different on linux than on my Mac laptop for a particular data file and it seems to be an issue with how the CSV file is being generated on my Mac.

In all cases, I'm using retriever v2.3.0, and running from within Python3.
1. I use retriever to download dataset "veg-plots-sdl":
```python
import retriever
retriever.install_csv("veg-plots-sdl")
```

2. Then I look at the "Photo_info" file. On my mac, line 9 of the data (line 10 of the file) shows:
```
9,375,11/14/1988,Turner,9:30,Graphlex XL,,58,,280,up,20,1.45,2,0,0,,0
```
and on linux, it shows:
```
9,375,11/14/1988,Turner,9:30,Graphlex XL,,58,,280,up,2_0,1.45,2,0,0,,0
```
**notice the entry in column 12, which shows `20` vs. `2_0`**

3. Looking at the `veg_plots_sdl.json` script, I see the entry for Photo_info as:
```json
            "name": "Photo_info",
            "schema": {},
            "url": "https://ndownloader.figshare.com/files/5625354"
```

When I use that link to download the file directly, it seems to match up with the version of the file when downloading on Linux:
```
9,375,11/14/1988,Turner,9:30,Graphlex XL,NA,58,,280,up,2_0,1.45,2,0,0,NA,0
```

**Here, the NAs are explicitly present, but are not present when examining the CSV files downloaded by retriever.**

This suggests to me that there is some auto-conversion of CSVs operating under the hood of retriever, and that it does things slightly differently depending on OS. Perhaps, the missing values in the first rows of data cause that column to be set differently as a numeric or character column by default, and so the underscore gets dropped in one OS, but not another.

**Comment by henrykironde** [comment]
Thank you @ha0ye, this needs some redesign.
```Python
Python 3.6.5
>>> 2_0
20
>>> 
Python 2.7.15 
>>> 2_0
  File "<stdin>", line 1
    2_0
      ^
```
I guess we shall have to change the way we detect the data type in https://github.com/weecology/retriever/blob/master/retriever/lib/engine.py#L265

**Comment by ethanwhite** [comment]
For future reference (since I couldn't believe that 2_0 == 20): https://www.python.org/dev/peps/pep-0515/
