### ISSUE TITLE
[bug] (successful) version checking depends on updated pkg_resources/setuptools

### ISSUE THREAD

**Issue by ha0ye** [weecology/retriever#1324]
I ran into an issue where retriever didn't properly identify itself as being able to use certain scripts. For example, the R CMD check fail logs in https://travis-ci.org/weecology/MATSS/jobs/521510095 show a lot of messages like:
```
ngreatplains-flowering-dates is supported by Retriever version 2.0.0-dev
Current version is v2.2.1.dev
plant-occur-oosting is supported by Retriever version 2.0.dev
Current version is v2.2.1.dev
```

I traced this back to the `check_retriever_minimum_version()` function, which uses `parse_version` to compare version numbers (and didn't quite work).

The solution was to update `pkg_resources` by way of updating `setuptools`. I'm not sure if this is one of those things that could be included in `requirements.txt`?

**Comment by henrykironde** [comment]
Thanks for catching this @ha0ye , I am not sure why it never showed up in a new docker environment.
