### ISSUE TITLE
Change Debian packaging tool set or cancel packaging for Debian

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1325]
The current tool used for creating the debian package has not seen maintenance for a long time. The last release was in 2015 https://pypi.org/project/stdeb/.

I propose that we use dpkg-buildpackage
A sample example is illustrated here. 
https://krzysztofzuraw.com/blog/2017/building-python-packages-for-debian.html

I am trying this out but feel free to jump in and contribute.

**Comment by ethanwhite** [comment]
I think we should broaden this conversation to whether or not to drop all of the installers and focus our energy on really well refined and test installation instructions.

**Comment by veb7vmehra** [comment]
@henrykironde where should I create the folder for new version of dpkg-buildpackage, also should we have to remove something related to the previous version?

**Comment by henrykironde** [comment]
Thanks @veb7vmehra, the feature seems really cool however, I think I am leaning towards the removal of Os based packaging. I will update this issue if we really want to go in this direction

**Comment by henrykironde** [comment]
@veb7vmehra, after discussion with the team, you can go ahead and work on this. 👍 
You could refer to the https://krzysztofzuraw.com/blog/2017/building-python-packages-for-debian.html or any other current method. The more simple, the better.

> I create the folder for new version of dpkg-buildpackage, also should we have to remove something related to the previous version?
 
`You can develop this as you wish. I do not think the files collide. We shall remove the old way after confirming this works fine and smooth `

**Comment by veb7vmehra** [comment]
@henrykironde I am almost done with this issue I guess but there is a dockerfile in which I have to fill up the FROM part(which most prob needs server version or something) and MAINTAINER part which needs I guess the official email id. Can you please help me with that?

**Comment by veb7vmehra** [comment]
@henrykironde Any update sir?

**Comment by henrykironde** [comment]
Could you put in a PR and we have this conversation on the PR

**Comment by ethanwhite** [comment]
We have dropped support for OS specific installers thanks to pip and conda both providing good stable approaches to installing via Python and support for installing Python packages in both R & Julia.
