### ISSUE TITLE
Request more large datasets

### ISSUE THREAD

**Issue by coolalexzb** [weecology/retriever#1329]
When I am testing the threshold of large datasets, `vertnet` dataset is the largest dataset in retriever and it will cause out of memory problem when users implement `fetch` function. However, compared with `vertnet` datasets, other datasets are too small which makes it difficult to find a threshold. I hope users and developers can provide more datasets source (size between 400M to 3G is better), which makes it possible not only to find the threshold but also be used as test data in the future to solve out of memory problem. Thank you!

**Comment by henrykironde** [comment]
You can create and test one locally. 
For example, create a python script to read the row values of any` vertnet_*` csv data and write to a new file  _`n`_ times. (_`n`_ starting from the small numbers and test with increasing _`n`_)
That could be a lot of data. Save the new data in `~/retriever/rawdata/bertnet-birds`
I would name this file i.e `bertnet_birds.csv`. 
Make a copy of the `vertnet_bird.py` script, rename it `bertnet_birds.py`. In this case we have created a new `bertnet-birds` data package with size _`n`_ of the original dataset

**Comment by coolalexzb** [comment]
A useful suggestion! I will try it!

**Comment by henrykironde** [comment]
Okey, I will close this for now
