### ISSUE TITLE
Allow consuming JSON data

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1334]
Currently we only support ingesting delimited tabular data. It is increasingly common for tabular style data to be distributed in JSON files and it would be nice to also be able to consume this. We would probably just convert it to CSV as a starting point and then process it using our standard pipeline.

There are a few not particularly active packages for doing this, but the code to do it is so simple enough that since none of the packages seem to be widely adopted we might be better off just writing and maintaining it ourselves.

(no rush on this, just a thought while looking at a cool dataset that's only available in JSON: http://data.unpaywall.org/products/snapshot)

**Comment by ethanwhite** [comment]
Here's one example of the basic approach: http://blog.appliedinformaticsinc.com/how-to-parse-and-convert-json-to-csv-using-python/

**Comment by DumbMachine** [comment]
Some time ago, I was doing the same and found that **pandas** provide good functions to help with JSON data. 
1. For simple ( not nested JSON ), it can be read directly:
```python
>>> data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": ["Team Lead", "Sr. Developer"]}'
>>> pd.read_json(data)
  employee_name            email    job_profile
0         James  james@gmail.com      Team Lead
1         James  james@gmail.com  Sr. Developer
```
2. For nested jsons, **pandas.io.json** provides [json_normalize](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.io.json.json_normalize.html). Using this [data](https://data.cityofnewyork.us/api/views/25th-nujf/rows.json?accessType=DOWNLOAD) (This method might require some preprocessing, if data has unwanted information)
```python
import json
from pandas.io.json import json_normalize

# This will load all the data in the ['data'] key of the json.
>>> df_json = json_normalize(
        json.load(open('babies.json', 'r')),
        'data',
        )
>>> df_json
                       0                                     1   ...   12  13
0      row-9uy2~edsf_2222  00000000-0000-0000-5403-09C9E652DA13  ...  172   1

# Now we will have to delete any extra columns. ( as there are 14 column, though only 6 are required )
>>> df_json.drop([i for i in range(14)][0:8], axis=1, inplace=True) # Dropping columns
         8       9                           10         11   12  13
0      2016  FEMALE  ASIAN AND PACIFIC ISLANDER     Olivia  172   1

# Renaming the columns.
>>> df_json.rename(columns={8:"Year of Birth", 9:"Gender",..., 12:"Count", 13:"Rank"})
       Year of Birth  Gender  ... Count Rank
0               2016  FEMALE  ...   172    1
```
In the end, the data is in the csv form. This transformation can be done easily, though I think this will require some *extra information* in the scripts.json to acknowledge the paths in JSON of the dataset.
This extra information will differ from dataset to dataset, depending upon the structure of JSON.

(if the above method doesn't work on some deeply nested or mixed JSON data)
We can make specific function to yield one row at a time and then use 
```python
>>> pd.read_records([record_data]) #list of records.
```

**Comment by veb7vmehra** [comment]
Created a function which take json file input as a list of dictionaries and then convert it to a csv file. It is appropriate for most of the json data I guess.
`def convertJson(data):
    count = 0
    for diction in data:
        print(diction)
        print(type(diction))
        if type(diction) == str:
            employ_data.write(diction+',')
        elif type(diction) == dict:
            temp.clear()
            employ_data.write('\n')
            if count == 0:
                header = diction.keys()
                csvwriter.writerow(header)
                count += 1
            for any in diction.values():
                temp.append(any)
            print(temp)
            list1 = temp
            print(list1)
            convertJson(list1)
            #csvwriter.writerow(diction.values())
        elif type(diction) == list:
            for item in diction:
                if type(item) == str:
                    employ_data.write(item+' ')
                elif type(item) == dict:
                    temp.clear()
                    if count == 0:
                        for i, (key, value) in enumerate(item.items()):
                            employ_data.write('('+key+'-'+value+') ')
                        count += 1
                    for any in item.values():
                        temp.append(any)
                    print(temp)
                    list1 = temp
                    print(list1)
                    convertJson(list1)`

@ethanwhite Should I make a pull request to add it to the repo? Also just tell me a bit about with which file in repo can I make proper path for json file so that any json file firstly convert to csv and then move for further procedure.

**Comment by DumbMachine** [comment]
@henrykironde  @ethanwhite Is this feature still required? I would love to work on this issue.

**Comment by veb7vmehra** [comment]
Created a function which take json file input as a list of dictionaries and then convert it to a csv file. It is appropriate for most of the json data I guess.
The Example code is here:
[data.txt](https://github.com/weecology/retriever/files/4082543/data.txt)

@ethanwhite Should I make a pull request to add it to the repo? Also just tell me a bit about with which file in repo can I make proper path for json file so that any json file firstly convert to csv and then move for further procedure.

**Comment by henrykironde** [comment]
```J
{
  "employee_details": [
    {
      "employee_name": "James",
      "email": "james@gmail.com",
      "job_profile": [
        "Sr. Developer",
        "Team Lead"
      ]
    },
    {
      "employee_name": "Smith",
      "email": "Smith@gmail.com",
      "job_profile": [
        {
          "Project Lead": "Managing Project"
        }
      ]
    }
  ]
}
```
Thank you @veb7vmehra for this code,  based on your work the out put was
```j
employee_name,email,job_profile
James,james@gmail.com,Sr. Developer Team Lead 
Smith,Smith@gmail.com,(Project Lead-Managing Project) Managing Project,
```
I expected something more to the lines of

```j
employee_name,email,job_profile_0, job_profile_1
James,james@gmail.com,Sr. Developer, Team Lead 
...
```

and 
```j
employee_name,email,job_profile_0, job_profile_0_comment, job_profile_1,  job_profile_1_comment
Smith,Smith@gmail.com,Project Lead, Managing Project,.........
```
 I would think that the structure should be consistent with in the entire Json. These two Json objects have different structures in "job_profile".

**Comment by henrykironde** [comment]
I would recommend @DumbMachine and @veb7vmehra to work together on this issue if possible. This has been incorporated into GSoC 2020

**Comment by veb7vmehra** [comment]
@henrykironde thanks for your review. The 2 structures were just to show the 2 kinds of complexities. I have used parenthesis to show kind of parent-child relationship but I can fix it to the way you are saying. Just tell me.

**Comment by henrykironde** [comment]
In fact the first edge case is covered well by the panda as @DumbMachine showed
```python
>>> data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": ["Team Lead", "Sr. Developer"]}'
>>> pd.read_json(data)
  employee_name            email    job_profile
0         James  james@gmail.com      Team Lead
1         James  james@gmail.com  Sr. Developer
```
for the second am not sure for now.

**Comment by DumbMachine** [comment]
@henrykironde, I believe the second case represents a flaw in the dataset. It seems like an example of unstructured data to me. Since the second row entity, `job_profile` represents a different pattern from its previous occurrence. Such cases would require special preprocessing to cater to the uniqueness of the dataset. 
If you agree with the above, then we would have two solutions:
1. Make a separate sub-module, which contains all the functions required by each dataset for preprocessing.
(or)
2. Store the code for the preprocessing function in the script of the dataset, in the following manner:
```
{
    "preprocess": ''''def preprocess(*args):
    ....'''
    "citation": [.....],
    "homepage": "http://mlr.cs.umass.edu/ml/datasets/Iris",
    "keywords": [
        "plants",
        "literature-compilation",
        "categorical"
    ],
    "name": "iris",
    "resources": [......],
    "retriever": "True",
    "retriever_minimum_version": "2.0.dev",
    "title": "Iris Plants Database",
    "version": "1.2.1"
}
```
Later on the function can be loaded into python, using something similar to this:
![image](https://user-images.githubusercontent.com/23381512/72685040-12d7cb80-3b0c-11ea-8368-4bc659855464.png)

**Comment by DumbMachine** [comment]
While scrolling through various JSON datasets, i came across this data:
```json
{
    "prizes": [
        {
            "year": "2019",
            "category": "chemistry",
            "laureates": [
                {
                    "id": "976",
                    "firstname": "John",
                    "surname": "Goodenough",
                    "motivation": "\"for the development of lithium-ion batteries\"",
                    "share": "3"
                },
                {
                    "id": "977",
                    "firstname": "M. Stanley",
                    "surname": "Whittingham",
                    "motivation": "\"for the development of lithium-ion batteries\"",
                    "share": "3"
                },
                {
                    "id": "978",
                    "firstname": "Akira",
                    "surname": "Yoshino",
                    "motivation": "\"for the development of lithium-ion batteries\"",
                    "share": "3"
                }
            ]
        },
        {
            "year": "2019",
            "category": "economics",
            "laureates": [
                {
                    "id": "982",
                    "firstname": "Abhijit",
                    "surname": "Banerjee",
                    "motivation": "\"for their experimental approach to alleviating global poverty\"",
                    "share": "3"
                },
                {
                    "id": "983",
                    "firstname": "Esther",
                    "surname": "Duflo",
                    "motivation": "\"for their experimental approach to alleviating global poverty\"",
                    "share": "3"
                },
                {
                    "id": "984",
                    "firstname": "Michael",
                    "surname": "Kremer",
                    "motivation": "\"for their experimental approach to alleviating global poverty\"",
                    "share": "3"
                }
            ]
        },
```
I wasn't able to use pandas to read this in the proper order, which i believe is something like this:
```
 id firstname surname motivation share category year
```
This can be generalized by a function, which gets its input as the `main column keys` ( id firstname surname motivation share) and the `seconday column keys` (category year) which are obtained from parent keys of the `main column keys`

**Comment by DumbMachine** [comment]
@henrykironde let me know which route we are taking on this one.

**Comment by henrykironde** [comment]
Let us create generic function that does that.

**Comment by veb7vmehra** [comment]
@henrykironde and @DumbMachine I guess for any complex data like mentioned above we can use numeric notation to specify the generation(like the main key will be 1 and its first child will be 1.1 and so on). We can continue this for any complex JSON data and once it is converted to CSV we can also easily clear the data if we want before sending it for further processing. Or maybe we can also use tabs to place a child exactly below the parent but it can be clumsy in some cases. Tell me your views on this and I will work accordingly.

**Comment by henrykironde** [comment]
I guess that would work too

**Comment by DumbMachine** [comment]
> @henrykironde and @DumbMachine I guess for any complex data like mentioned above we can use numeric notation to specify the generation(like the main key will be 1 and its first child will be 1.1 and so on). We can continue this for any complex JSON data and once it is converted to CSV we can also easily clear the data if we want before sending it for further processing. Or maybe we can also use tabs to place a child exactly below the parent but it can be clumsy in some cases. Tell me your views on this and I will work accordingly.

Pandas's `json_normalize` already does what you have mentioned. Also using the numeric notation
of each sub_entity would create columns with id as parents_0, parents_1 and so on. Consider the "laureates" column, we need each of the sub-entity to be a row of the dataset. So I believe the best bet would be saving the required columns in the `scripts/<dataset>.json` and then using that information we write a function to unwrap the children into rows.

**Comment by DumbMachine** [comment]
Considering the nobel prize example, we can just do the following:
```python
from pandas.io.json import json_normalize
prize = json['prizes'][0]
df = json_normalize(prize, 'laureates')
for key in prize.keys():
      if key != 'laureates':
           df[key] = prize[key
```
This could be looped for all the prizes, giving output similar to:
```bash
    id   firstname      surname                                      motivation share  year   category
0  976        John   Goodenough  "for the development of lithium-ion batteries"     3  2019  chemistry
1  977  M. Stanley  Whittingham  "for the development of lithium-ion batteries"     3  2019  chemistry
2  978       Akira      Yoshino  "for the development of lithium-ion batteries"     3  2019  chemistry


```

**Comment by henrykironde** [comment]
Thanks @DumbMachine. Now let us all get some code working and then we all contribute to sample jsons that would test the edge cases. And we can all work on this as a PR.

**Comment by DumbMachine** [comment]
@henrykironde I got children, parent row representation working, wherein row is made from data from two dicts, one having the columns which are unique to each dict and another which are common to them (["years", "category"]) in this case. This worked very well for the nobel prize dataset but fail at the example you had given. This makes me think if we should consider cases like those (employee example) where the data is not structured well. If you are fine with these results then we will go with this:
- try using json_normalize, if it doesn't work then use the custom implementation to convert json to pandas
```python
import pandas as pd

file = "json_tests/nobel_prize.json"
dictionary = json.load(open(file, "r"))

columns = ["id", "firstname", "surname", "motivation", "share"]
parents = ["year", "category"]
def walk(dix, columns, data, parents):
    if type(dix) == dict:
        if columns == list(dix.keys()):
            return(dix)
        else:
            for _, item in dix.items():
                if type(item) == list:
                    for ls in item:
                        row = walk(ls, columns, data, parents)
                        if row:
                            if all(par for par in parents if par in list(dix.keys())):
                                for col in parents:
                                    row[col] = dix[col]
                            data.append(row)

data = []
walk(dictionary, columns, data, parents)
pd.DataFrame(data).head()

Out[85]: 
    id   firstname      surname                                         motivation share  year   category
0  976        John   Goodenough     "for the development of lithium-ion batteries"     3  2019  chemistry
1  977  M. Stanley  Whittingham     "for the development of lithium-ion batteries"     3  2019  chemistry
2  978       Akira      Yoshino     "for the development of lithium-ion batteries"     3  2019  chemistry
3  982     Abhijit     Banerjee  "for their experimental approach to alleviatin...     3  2019  economics
4  983      Esther        Duflo  "for their experimental approach to alleviatin...     3  2019  economics
----------------------------------------------------------------------------------------------------------------------------------------------------
file = {
  "employee_details": [
    {
      "employee_name": "James",
      "email": "james@gmail.com",
      "job_profile": [
        "Sr. Developer",
        "Team Lead"
      ]
    },
    {
      "employee_name": "Smith",
      "email": "Smith@gmail.com",
      "job_profile": [
        {
          "Project Lead": "Managing Project"
        }
      ]
    }
  ]
}
columns = file['employee_details'][0].keys()
data = []
walk(file, columns, data, [])
pd.DataFrame(data).head()

Out[18]: 
  employee_name            email                             job_profile
0         James  james@gmail.com              [Sr. Developer, Team Lead]
1         Smith  Smith@gmail.com  [{'Project Lead': 'Managing Project'}]

```

[nobel_prize.txt](https://github.com/weecology/retriever/files/4099707/nobel_prize.txt)

**Comment by henrykironde** [comment]
Can we do it without prior knowledge of the `columns`, `parents`

**Comment by veb7vmehra** [comment]
@henrykironde there is a library named flatten_json which is easily able to flatten all kind of json data sets. I have checked both noble prize problem and employees problem on that and both are pandas data frame easily which in turn can be easily converted to csv files. The example is shown below:
[flatten2.txt](https://github.com/weecology/retriever/files/4101312/flatten2.txt)
I request you to check this for other edge cases(I personally have checked it for some) or maybe tell me and I will do that for you.

**Comment by henrykironde** [comment]
Well both methods look like they are getting us to where we want to be headed to.
Let us replace the code in here
https://github.com/weecology/retriever/blob/647441104d87979738104fe0dab9048f0c85c5be/retriever/lib/engine_tools.py#L104.

And we can add all the test cases here.
https://github.com/weecology/retriever/blob/master/retriever/lib/engine_tools.py#L104

**Comment by DumbMachine** [comment]
@veb7vmehra your result returns:
```bash
   year   category laureates_0_firstname laureates_0_surname laureates_1_firstname laureates_1_surname
0  2019  chemistry                  John          Goodenough                 Akira             Yoshino
1  2019  economics              Abhijeet            Banarjee                Esther               Duflo
```
It gives a row for each year, but it would make more sense to have each laureate to have a row, something like what I had presented earlier 
```bash
Out[85]: 
    id   firstname      surname                                         motivation share  year   category
0  976        John   Goodenough     "for the development of lithium-ion batteries"     3  2019  chemistry
1  977  M. Stanley  Whittingham     "for the development of lithium-ion batteries"     3  2019  chemistry
2  978       Akira      Yoshino     "for the development of lithium-ion batteries"     3  2019  chemistry
3  982     Abhijit     Banerjee  "for their experimental approach to alleviatin...     3  2019  economics
4  983      Esther        Duflo  "for their experimental approach to alleviatin...     3  2019  economics
```

**Comment by DumbMachine** [comment]
> Can we do it without prior knowledge of the `columns`, `parents`.

We would have that information available in the script for the dataset, right? This ensures the proper structure. Either we use json_normalize as it works well when we know which key has the rows. Or we can use the `walk` function for cases like that of `nobel_prize`. 

For starters we could start by supporting only those cases where simple or json_normalize works. And then iteratively adding more options for json datasets.

**Comment by henrykironde** [comment]
Sounds good, and about the comment

> Can we do it without prior knowledge of the columns, parents.

I think we can forget about that and we see what we have when the Pr is in

**Comment by veb7vmehra** [comment]
@henrykironde Sir is there any other file format also which needs such conversion?

**Comment by henrykironde** [comment]
Yes we do have more thats part of the Gsoc project like convert from xml to csv.

**Comment by coolalexzb** [comment]
As for problem such as allowing consuming JSON data, or XML data, what is the real need? I noticed that engines such as jsonengine, xmlengine only support read json file or xml file into a string format. 
I have two thoughts about the actual needs for the problems mentioned above:
1  Convert xml or json file to csv file or dataframe type in Pandas, and then we can operate the converted csv file or dataframe
2  Like tabular data, we now use Table class to store this type of data. We also need to find a class in Python, that can support json or xml dataset
Thank you! @henrykironde

**Comment by henrykironde** [comment]
Yes and I think many have talked about this, that would be a good start.

**Comment by coolalexzb** [comment]
Yeah, since I read the discussion in this issue and the solution to HDF5 engine in #79 , I am a little bit confused about method 1 and method 2 which is better. @henrykironde

**Comment by henrykironde** [comment]
Added
