### ISSUE TITLE
Update Biotime

### ISSUE THREAD

**Issue by gmyenni** [weecology/retriever#1340]
The latest version is here: https://zenodo.org/record/2602708#.XPazU9NKjOQ

Complete data are in the .sql, but there are also metadata and citations separately in .csv.

**Comment by henrykironde** [comment]
@gmyenni thanks for the request. Update, I am almost done. I will use an extra day for validating this dataset.

**Comment by henrykironde** [comment]
@gmyenni, @diazrenata, @ha0ye In case you use `Biotime`, we have added the data from the sql file as `biotimesql`.

**Comment by gmyenni** [comment]
Thank you @henrykironde !!
