### ISSUE TITLE
Travis builds are failing

### ISSUE THREAD

**Issue by apoorvaeternity** [weecology/retriever#1361]
We are using `python==3.5.2` on Travis and `python==3.5.4` on AppVeyor. The AppVeyor builds are passing. 
If we look at the logs on Travis the issue seems to be with `pandas`.
Possibly related to https://github.com/pandas-dev/pandas/issues/27247

**Comment by apoorvaeternity** [comment]
We can either pin the dependency down to a lower version of pandas or move to a higher python version( will require more checks to see how it affects other things)

**Comment by ethanwhite** [comment]
I think we should move to the higher Python version since otherwise things could be breaking with up-to-date installs of Pandas.
