### ISSUE TITLE
Add Python interface

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#137]
In some cases it would be useful to load a dataset directly into a Python analysis script instead of first installing it and then importing it. This would be most useful for single table datasets. It could also be useful for combined datasets once they are implemented.

I'm envisioning something like:

``` python
import retriever
lh_data = retriever.fetch('MammalLH')
...
```

This is basically just a convenience function that first runs `install` and then imports the data into a default data structure like a Pandas dataframe. We would probably want to implement caching to avoid the download and processing having to run every time the script is run. We could use either csv or sqlite by default and allow the use of a different DBMS via optional arguments. This same functionality could also be mirrored in https://github.com/ropensci/rEcoData if that is ever developed further.

**Comment by ethanwhite** [comment]
Model this roughly on the R interface:
https://github.com/ropensci/ecoretriever

**Comment by kapilkd13** [comment]
Hi @ethanwhite In R interface https://github.com/ropensci/ecoretriever of Data Retriever, In case of a fetch command, we download our Dataset to a .csv file(only) and import that to data.frame.  So in Python Native Interface do we want a similar behavior, or we should allow users to specify which database they want to use to fetch, and then further import data from that database into pandas Dataframe. We can use SQLAlchemy  to do so. 
I am envisioning a `python_interface.py` module that would use our current modules to install datasets and put them into a Pandas Dataframe object/s and return that. Other functionality like List_scripts, Install and Download would also be included in this module.
Regarding Julia Interface, present R interface has given me clear understanding of what all functionality we want from Julia wrapper of CLI retriever.

**Comment by ethanwhite** [comment]
@kapilkd13 - There's a bunch of good thinking in here. Nice work!

1. I would love to have the option of using different databases/file formats with csv as the default. So the interface would work something like `retriever.fetch('iris)`, retriever.fetch('iris', backend='postgres').

2. Yes, to fetching into a pandas data frame and `pandas.read_sql_table` should help make that easy.

3. The key thing for where we put this functionality is that it will need to be loadable as `retriever.install`, retriever.fetch`, etc.

**Comment by kapilkd13** [comment]
Hi @ethanwhite  I was going through Technical details of implementing python interface for retriever. I am little stuck at caching point. When we say we should use cache to save downloading and processing time, what I understood is When we load data into a `pandas Dataframe`. we should save it in cache using `pickle` or `HDF5`.   we should allow user to provide a option `use_cache`. If it is set then look for cache present and if present load that data into dataframe and return that Dataframe object. Is this correct approach. Also what do you think would be better, using `pickle` for dataframes or saving it to a `HDF5` file.

**Comment by ethanwhite** [comment]
Caching is actually built in already and happens by default so none of that needs to be built. There is a CLI flag that allows the cache to be overwritten and we would want that to be an optional names argument in any function that downloads data (download, install, fetch).

**Comment by ethanwhite** [comment]
@ShivamNegi is currently working on this as part of his GSoC project.

**Comment by ethanwhite** [comment]
It only took 3.5 years, but @ShivamNegi added this during this GSOC project and it was just released in 2.1. @ShivamNegi - you win the prize for closing the oldest issue I can ever remember closing!
