### ISSUE TITLE
Rebuild docs

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1383]
It looks like that docs haven't been building on readthedocs for the last few months. Since we just merged the two GSOC projects we'll want to get the docs updated so that folks can read the very nice documentation that's been generated as part of those changes.

**Comment by henrykironde** [comment]
I will check what is happening with that. I know they did change some rules based on their advertisement business model but I didn't expect it to affect our builds. Locally they are building fine

**Comment by henrykironde** [comment]
They are building fine https://readthedocs.org/projects/retriever/
