### ISSUE TITLE
Provenance install commit dataset not working

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1391]
The provenance install commit dataset feature was not added during the merge.
I remember testing the same and may have not merged the PR or we cleaned it up by mistake. 
@apoorvaeternity do you have time to check this out, thanks

**Comment by apoorvaeternity** [comment]
@henrykironde Is this issue still present? I think we can close this one.

**Comment by henrykironde** [comment]
Thanks @apoorvaeternity, this has been fixed
