### ISSUE TITLE
Re-add eBird EOD

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1396]
We previously support eBird EOD before it was removed from DataONE. It's back now so it would be good to re-add that support: https://search.dataone.org/view/EOD_CLO_2016.eml

**Comment by henrykironde** [comment]
Notes:
This is `11.4 gb` of compressed data and `103 gb` of data uncompressed.
File name for zip `EOD_CLO_2016.csv.gz.gz` with two `.gz` and the unziped file is `EOD_CLO_2016.csv.gz` with one `.gz`

**Comment by henrykironde** [comment]
ref: 8c58a4de -> https://github.com/weecology/retriever-recipes/pull/49

**Comment by henrykironde** [comment]
Added to #1575
