### ISSUE TITLE
List of Public Data sources to add

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1402]
- http://www.samhsa.gov/data/report/2015-2016-nsduh-state-estimates-individual-excel-and-csv-files-outcome
- https://world.openfoodfacts.org/data
- https://github.com/turalus/encycloDB/tree/master/Countries
- https://www.kaggle.com/mylesoneill/world-university-rankings/download
- https://uclspp.github.io/datasets/
- https://corgis-edu.github.io/corgis/csv/
- http://www.ncaa.org/about/resources/research/shared-ncaa-research-data
- (https://www.nsf.gov/statistics/data.cfm,
- https://nsf.gov/statistics/herd/pub_data.cfm)

- https://github.com/emorisse/FBI-Hate-Crime-Statistics/tree/master/2013
    `There are two files, table13.csv and  table14.csv`

- https://www.epa.gov/enviroatlas/forms/enviroatlas-data-download

#GIS 
- [The Multi-Resolution Land Characteristics (MRLC) consortium ](https://www.mrlc.gov/ )

**Comment by mauwazahmed** [comment]
google public datasets
https://datasetsearch.research.google.com/

**Comment by mauwazahmed** [comment]
FiveThirtyEight https://data.fivethirtyeight.com/ - datasets related to news and sports
https://github.com/BuzzFeedNews
https://opendata.socrata.com/
http://archive.ics.uci.edu/ml/index.php
http://academictorrents.com/browse.php

**Comment by mauwazahmed** [comment]
https://github.com/caesar0301/awesome-public-datasets

**Comment by asarmakeeva** [comment]
housing data:
https://www.zillow.com/research/data/ 
data from world bank:
https://datacatalog.worldbank.org/
climat data:
https://www.ncdc.noaa.gov/cdo-web/datasets

**Comment by patdumandan** [comment]
is this a good example of a publicly available dataset that we can work on @henrykironde  : https://www.srs.fs.usda.gov/sustain/data/fia/ewplot/index.htm?  (FIA plot-level)

**Comment by henrykironde** [comment]
https://github.com/datasets/world-cities

**Comment by henrykironde** [comment]
https://open.canada.ca/en/open-data Canada open data

**Comment by henrykironde** [comment]
Thanks everyone for contributing to the list, we are adding the data to ref # 1575
