### ISSUE TITLE
Improve retriever autocreate 

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1403]
Some features of `retriever autocreate` do need some improvements

I have some changes already, feel free to take over and  create a new PR with the needed changes 
ref : https://github.com/henrykironde/retriever/pull/127/files

**Comment by henrykironde** [comment]
More issues discovered:

- The json file created should have `_` and not `-`.

- The resource `name`  (`resource_dict["name"]`) should be cleaned up and no "dots", space and not `-`

**Comment by pathak-mayurdeep** [comment]
I have cleaned up the resource name and path. 
But regarding other issue with json file name with `-`, I'm little confused. Should I clean up the file name at `def write_out_scripts` or did you meant something else? @henrykironde

**Comment by pathak-mayurdeep** [comment]
@henrykironde I added a line that should remove any `white-space` and `-` in the json file name.
I am not sure if this is what you meant.

**Comment by henrykironde** [comment]
@pathak-mayurdeep, create a PR and I will test it.

**Comment by pathak-mayurdeep** [comment]
Ok... I have created a clean branch from master and corrected all the changes. I am creating another PR.
