### ISSUE TITLE
Add Jornada and Shortgrass Steppe Rodent Time-Series Data

### ISSUE THREAD

**Issue by bleds22e** [weecology/retriever#1416]
Link to Jornada rodent data: https://portal.lternet.edu/nis/mapbrowse?packageid=knb-lter-jrn.210086009.74

Link to Shortgrass Steppe data: https://portal.lternet.edu/nis/mapbrowse?packageid=knb-lter-sgs.137.17

**Comment by henrykironde** [comment]
Do you also want the data referenced in the [Link to Shortgrass Steppe data](https://portal.lternet.edu/nis/mapbrowse?packageid=knb-lter-sgs.137.17)


> Provenance:
> This data package is a source for the following data packages:
> SGS-LTER Long-Term Monitoring Project: Small Mammals on Trapping Webs on the Central Plains Experimental Range, Nunn, Colorado, USA 1994 -2006, ARS Study Number 118 (Reformatted to ecocomDP Design Pattern)
