### ISSUE TITLE
Implement citation lookup in Python interface

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1419]
At the moment this appears to only be present in the command line interface. This change would involving moving the core code from this section of `__main__.py`: 

https://github.com/weecology/retriever/blob/0d9c16c4c874b366e6a0a64875bb4fc026187cc5/retriever/__main__.py#L64

Into a Python interface function and then calling that function from inside of `__main__.py`. The new function should return the string representation of the citation not (just) print it out.

**Comment by ANURADHAJHA99** [comment]
@ethanwhite I will like to work on this issue. KIndly assign it to me

**Comment by henrykironde** [comment]
@ANURADHAJHA99  thank you for the interest to get this issue solved. I had started part of it.
The PR is https://github.com/weecology/retriever/pull/1422/files.
However the [CLI here](https://github.com/weecology/retriever/blob/0d9c16c4c874b366e6a0a64875bb4fc026187cc5/retriever/__main__.py#L64) should also use the interface. You can add that to the PR.

Also something that may be needed is creating a function(interface) to return the license just like we have done with the citation(in a separate PR).

**Comment by ANURADHAJHA99** [comment]
@henrykironde  so, basically i will add the citation function in the CLI Module and call it?

**Comment by henrykironde** [comment]
Import it https://github.com/weecology/retriever/blob/0d9c16c4c874b366e6a0a64875bb4fc026187cc5/retriever/__main__.py#L15

**Comment by ANURADHAJHA99** [comment]
@henrykironde the function return for licence is already there, where am i following wrong, kindly guide me.

`if args.command == 'license':
            if args.dataset is None:
                print(LICENSE)
            else:
                dataset_license = license(args.dataset)
                if dataset_license:
                    print(dataset_license)
                else:
                    print("There is no license information for {}".format(args.dataset))
            return`

**Comment by henrykironde** [comment]
Ok first finish up the citation pr and we can move on to the license
