### ISSUE TITLE
Add azure

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1429]
We should add azure to have more tests since travis has been failing and almost has always needed restarts.
I believe travis is going through some improvement at the moment.

**Comment by coolalexzb** [comment]
Hi, it seems that I found the same problem yesterday and mentioned in #1433. What is the next step for us new contributors to solve or avoid the problem? Thank you! @henrykironde

**Comment by henrykironde** [comment]
We are currently testing on Azure
