### ISSUE TITLE
Is there any problem with the The Travis CI build

### ISSUE THREAD

**Issue by coolalexzb** [weecology/retriever#1433]
Hi, is there any problem with The Travis CI build? When I debug for #1428 after serval times, I mainly meet two problems with different changes. I also find that pull requests dealing with other problems by other programmers have similar error information. Following is the error information: 
1 
<img width="969" alt="屏幕快照 2020-02-27 上午1 59 19" src="https://user-images.githubusercontent.com/19755247/75423688-d4041500-5904-11ea-813e-e370529cd49f.png">
2
<img width="993" alt="屏幕快照 2020-02-27 上午1 49 57" src="https://user-images.githubusercontent.com/19755247/75423703-dbc3b980-5904-11ea-9b1a-42b3cf82abf7.png">

Thanks for the help!

**Comment by henrykironde** [comment]
Yes currently there is something wrong with travis and docker. We may be doing something wrong or something changed. I will try to be debug this later.

**Comment by coolalexzb** [comment]
I want to how can I continue to make new change if my previous pull request does not pass the test online. Do I need to make a new branch in my repository if I want to make a new pr? Thank you! @henrykironde

**Comment by henrykironde** [comment]
Good question.
For every issue, you should make a new PR at least. 
 In your repo checkout a new branch. 
Usually, I name the branches in relation to the issue.  eg. `git checkout -b repair-iris-dataset` 
`git checkout -b issue-11433`. 

When creating a new branch, I always checkout master and update it, then I branch off from master.

Please read through the docs here:
https://retriever.readthedocs.io/en/latest/developer.html#collaborative-workflows-with-github

**Comment by coolalexzb** [comment]
Ok, I will go ahead. Thank you! @henrykironde
