### ISSUE TITLE
Add bump version

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1434]
When we make a release, bump version should automatically update the places where we should up date the version numbers

This is a new feature and easy to add if you look at some examples online.

Places to update :https://github.com/weecology/retriever/commit/a82905671aa59407f51ff5aa2264539917fe4d11

**Comment by ashishpriyadarshiCIC** [comment]
@henrykironde  I would like to work on it

**Comment by henrykironde** [comment]
Please go ahead @ashishpriyadarshiCIC

**Comment by coolalexzb** [comment]
I think it easy to change bump version in setup.py, _version.py and version.txt automatically if we follow the creating release steps metioned in developer documentation.

But, how does file retriever_installer.iss generate? Is it generated manually before? If so, is it better to add a new function to update retriever_installer.iss in setup.py?

Another question is that when I want make change in setup.py, it seems that I cannot use the command like `python setup.py 2.4.2` to pass a new version to the __version__ in setup.py.

Thanks for your guide @henrykironde

**Comment by mauwazahmed** [comment]
we can change the major,minor and patch in the version
[bumpversion]
current_version = 0.0.0
commit = True
tag = False
parse = (?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(\-(?P<release>[a-z]+)(?P<build>\d+))?
serialize =
    {major}.{minor}.{patch}-{release}{build}
    {major}.{minor}.{patch}

[bumpversion:part:release]
optional_value = prod
first_value = dev
values =
    dev
    prod

[bumpversion:part:build]

[bumpversion:file:VERSION]

[bumpversion:file:./api/__version__.py]

[bumpversion:file:./api/swagger.yaml]
search = version: {current_version}
replace = {new_version}

**Comment by mauwazahmed** [comment]
we run it as
$ bumpversion major/minor/patch; cat version
and the output results in an increment in the mentioned element

**Comment by henrykironde** [comment]
Thanks @mauwazahmed for the input on this

**Comment by mauwazahmed** [comment]
You're welcomed Henry!! Wish you safety and goodwill.
