### ISSUE TITLE
Correction to setup.py

### ISSUE THREAD

**Issue by DumbMachine** [weecology/retriever#1440]
The current `setup.py` gives errors when installing `python-argcomplete`. 
![image](https://user-images.githubusercontent.com/23381512/75762315-7aff0b80-5d60-11ea-8951-63d4733446ea.png)
-  ```bash
   usage: activate-global-python-argcomplete [-h] [--dest DEST] [--user]
                                          [--no-defaults]
                                          [--complete-arguments ...]
   activate-global-python-argcomplete: error: [Errno 13] Permission denied: 
   '/etc/bash_completion.d/python-argcomplete'
   Please try --user to install into a user directory, or --dest to specify the bash completion modules directory```

 This error, to my knowledge occurs only for `zsh`.  Remedy for this is to change:
 ` activate-global-python-argcomplete` ---> `activate-global-python-argcomplete --user`
 https://github.com/weecology/retriever/blob/be301cf9b0643fec8c26d67a3852c7d47f036d18/setup.py#L131

---
-    ```bash
      sh: 18: eval: Syntax error: "(" unexpected (expecting "}")```
   This can be corrected by replace `()` with `{}`  https://github.com/weecology/retriever/blob/be301cf9b0643fec8c26d67a3852c7d47f036d18/setup.py#L123

**Comment by coolalexzb** [comment]
I want to help solve this error. What is the command you use will give such error? Thank you! @DumbMachine

**Comment by Jay-Iam** [comment]
I found that changing 
`argcomplete_command = 'eval "$(register-python-argcomplete retriever)"'`
to `argcomplete_command = "eval $(register-python-argcomplete retriever)"`
solves the problem. But, I tried it only on Ubuntu and Linux Mint

**Comment by pathak-mayurdeep** [comment]
@Jay-Iam I tested the changes you suggested and it seems to fix the issue.
 I tested it on WSL (win10) with multiple distros, and it works fine. It works fine for both `bash` and `zsh`.

Issue -
![image](https://user-images.githubusercontent.com/35169218/76168197-691fcd00-6193-11ea-942b-831ca46313f8.png)
after edits -
(zsh)
![image](https://user-images.githubusercontent.com/35169218/76168198-6cb35400-6193-11ea-81ab-2f7410073aff.png)
(bash)
![image](https://user-images.githubusercontent.com/35169218/76168204-7d63ca00-6193-11ea-9d3e-e6b83e65a66c.png)

**Comment by henrykironde** [comment]
Thanks @Jay-Iam, Could you put in a PR for this.
@pathak-mayurdeep thanks for the tests

**Comment by Jay-Iam** [comment]
@henrykironde Sorry, but does PR means pull request.

**Comment by apoorvaeternity** [comment]
@Jay-Iam Yes.

**Comment by henrykironde** [comment]
Thanks @DumbMachine for the input and everyone who contributed to this
