### ISSUE TITLE
Failed test in test_postgres_spatial

### ISSUE THREAD

**Issue by coolalexzb** [weecology/retriever#1448]
When I build and test retriever on Mac, there are three failed  tests, which are all related to datasets(testschema_retriever.raster_bio1, testschema_retriever.raster_bio2 ,testschema_retriever.us_eco). The error information is following:
<img width="791" alt="Ping-Mu-Kuai-Zhao-2020-02-25-Xia-Wu5 39 34" src="https://user-images.githubusercontent.com/19755247/76695443-733b4300-664d-11ea-9221-c76fc960adbe.png">

Then I use command `retriever install postgres test-raster-bio1`, it shows that "raster_bio1" table does not exist. I download
 raster_bio1 dataset on github, but it does not contain the "raster_bio1" table. What is the possible solution to solve this problem? Thank you!
<img width="623" alt="屏幕快照 2020-03-14 下午11 42 01" src="https://user-images.githubusercontent.com/19755247/76695446-79312400-664d-11ea-8578-35fe33d02785.png">
<img width="292" alt="屏幕快照 2020-03-14 下午11 43 55" src="https://user-images.githubusercontent.com/19755247/76695463-b85f7500-664d-11ea-8268-53a15150cde6.png">

**Comment by ashishpriyadarshiCIC** [comment]
@coolalexzb I think I got a similar issue a while back. I dropped my database, created it again and then ran the following queries:
```
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
```
It worked for me.

**Comment by coolalexzb** [comment]
Ok, Thanks and I will try for this. @ashishpriyadarshiCIC

**Comment by henrykironde** [comment]
Solved
