### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by DumbMachine** [weecology/retriever#1450]
Currently the following link seem to be broken:
- [Adding datasets to the Data Retriever](https://retriever.readthedocs.io/en/latest/scripts.html)

The link is found on https://www.data-retriever.org/.
I think the link should refer to : https://retriever.readthedocs.io/en/latest/recipes.html

**Comment by henrykironde** [comment]
I guess we have more of these like http://specs.frictionlessdata.io/data-packages/

**Comment by ethanwhite** [comment]
The data-retriever.org domain now redirects to readthedocs.
