### ISSUE TITLE
Add instructions to update scripts to quick start guides.

### ISSUE THREAD

**Issue by ha0ye** [weecology/retriever#1456]
After installation of retriever for the first time, the scripts need to be updated. This step seems to be missing from the "Quick Start" guide for `retriever` ( https://www.data-retriever.org/#quickstart ), as well as the landing page for `rdataretriever`.

In these cases, I think the commands to be added (in between the installation step and before the first example for installing/downloading a dataset) are:

## Command line interface
```bash
retriever update
```

## Python interface
```python
rt.check_for_updates()
```

## R interface (`rdataretriever`)
```r
rdataretriever::get_updates()
```

## Addendum
As an added usability feature, it would also be nice to check the return value for `retriever ls` / `rt.dataset_names()` / `rdataretriever::datasets()` for an empty list, and remind the user to update their scripts first.

There might need to be some added checking within `rdataretriever::datasets()` so that the user receives the correct fix using `rdataretriever`, and not the python fix.

**Comment by Mohitkumar6122** [comment]
@henrykironde ,@ha0ye whenever i open [https://www.data-retriever.org/#quickstart](https://www.data-retriever.org/#quickstart) it is showing me site not found could provide an alternative link for this.
Thanks.

**Comment by ha0ye** [comment]
I guess it should be https://retriever.readthedocs.io/en/latest/quickstart.html now?

**Comment by henrykironde** [comment]
@Mohitkumar6122 which page are you getting this error?

**Comment by Mohitkumar6122** [comment]
> I guess it should be https://retriever.readthedocs.io/en/latest/quickstart.html now?

Thanks now the link is working fine .

**Comment by Mohitkumar6122** [comment]
> @Mohitkumar6122 which page are you getting this error?

I was getting the error in the link provided at the issue description but thanks to @ha0ye now it is working fine.

**Comment by Mohitkumar6122** [comment]
Can you tell me how to update the documentation and whether do we need to update this in README too ?

**Comment by henrykironde** [comment]
This has been fixed. In case of any new problem, create an issue and I will see which part of the docs you have to change in the docs folder
