### ISSUE TITLE
Redirect websites to Read The Docs?

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1478]
I think we might want to get rid of the https://www.data-retriever.org/ website and redirect everything to Read The Docs so that we only need to maintain docs in one location. See https://github.com/weecology/retriever/issues/1476#issuecomment-644202239 for an example of link breaking resulting from having docs in two locations. Thoughts?

**Comment by ethanwhite** [comment]
I can take care of this if we decide to make this change.

**Comment by henrykironde** [comment]
Sounds good to me

**Comment by ethanwhite** [comment]
OK, I've made this change. I think we want to add a `Quick Start` page. Will open a new issue for that.
