### ISSUE TITLE
Add a Getting Started/Quick Start page to the docs

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1481]
We've gotten rid of the separate website to make maintaining the docs easier, but I think that means we need something similar in on Read The Docs, which is like the one page Quick Start guide that contains the information in https://github.com/weecology/retriever-site/blob/master/_posts/2016-02-27-quickstart.md.

**Comment by ethanwhite** [comment]
I'm going to work on this for a bit this morning if no one else has picked it up already.

**Comment by henrykironde** [comment]
Go for it, thanks
