### ISSUE TITLE
Results from `datasets` and `dataset_names` do not reflect changes in session

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#1483]
To reproduce:
1. Run `datasets` or `dataset_names`
2. If it returns an empty list run `check_for_updates`, if it returns a list of datasets run `reset`
3. Rerun `datasets` or `dataset_names` and see that it hasn't changed

This is problematic because it means that an initial install requires the user to install everything, run `check_for_updates`, and then restart. It will also cause reproducibility issues because including `check_for_updates` in code will not ensure that the scripts are actually available.

Solution:
Reload the dataset lists at the end of `check_for_updates` and `reset`.

I remember us having this issue before. I couldn't find an open issue. Will see if I can track the old instance down.

**Comment by ethanwhite** [comment]
OK, looks like we discussed this here: https://github.com/weecology/retriever/pull/1231

I think we underestimated the issues with installs at the time so I think we need to improve the logic to make sure that we have up-to-date lists of datasets within a session.

**Comment by ethanwhite** [comment]
And now I'm remembering that it's a circular import issue that makes this so hard. @zhangcandrew or @henrykironde do either you remember the details of what is happening with the circular import to help point me in the right direction for working on this.

I'm trying to run `reload_scripts` in both `repository.py` and `engine_tools.py`, which would allow us to update the script list at the end of `check_for_updates` and `reset` but running into our old friend:

```
ImportError: cannot import name 'reload_scripts' from partially initialized module 'retriever.lib.scripts' (most likely due to a circular import) (/home/ethan/Dropbox/Informatics/Retriever/src/retriever/lib/scripts.py)
```

**Comment by henrykironde** [comment]
I think after testing this we should emphasize that `check_for_updates` should be followed by `reload_scripts`. I think that was something I came up with, but we  can improve it. Lets try this same issue commands followed by `reload_scripts` and wee if that works

**Comment by ethanwhite** [comment]
You mean adding this to the documentation as a solution?

**Comment by ethanwhite** [comment]
> Lets try this same issue commands followed by `reload_scripts`

This does work properly and I agree that at a minimum we should improve the documentation on this. Interestingly, because of the way this works it means we can easily address the issue in the R & Julia wrappers by having the wrapping function call both functions.

I think it's still a little fragile to not automatically reload the scripts in Python, but I'm OK with the documentation change and silently doing that reload in the wrappers. I'm going to try to implement it in the R wrapper and will open a PR in `rdataretriever` for you to take a look at.

**Comment by ethanwhite** [comment]
After a little more exploring I'm :+1: for just updating the docs. The new online/offline functionality addresses a lot of this because the behavior is the same regardless of whether a script is present locally or not.

**Comment by henrykironde** [comment]
Reload takes care of this. More emphasis may be done on revising all the documentation before the release.
