### ISSUE TITLE
Log errors and other issues

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#151]
We should use the `logging` module to log anything that gets caught in an except statement during a Retriever session. This can then be used to help with debugging errors, in particular those that we can't replicate locally.

**Comment by kapilkd13** [comment]
Hi @henrykironde As we were talking about using `logging` module. I would like to add [logging](https://docs.python.org/3/library/logging.html) to our tool. I have gone through the steps involved and what I am thinking is:
1. We can create two handler, for `file` and `stdout`.
2. Our logger object will be set at `debug` by default and will send all logs to both handlers.
3. `file` handler will be set to `debug` and would log everything in a retriever.log file.
4. For each session this log file will be cleared and rewritten.
5. we will put this file's name in `.gitignore`. So whoever files a issue can be requested to upload log file for better understanding.
6. `stdout` handler will be set to `info` or `warning` level which can be changed as per user specified `debug` flag.
What are your thoughts on it @ethanwhite @henrykironde

**Comment by ethanwhite** [comment]
The general plan sounds good to me :+1:

**Comment by adhaamehab** [comment]
@ethanwhite @henrykironde 
I'm working on this issue as discussed on gitter with @henrykironde

**Comment by piyushchauhan** [comment]
Can I take up this issue? and if possible along with #1265  @henrykironde @ethanwhite

**Comment by henrykironde** [comment]
Sure

**Comment by henrykironde** [comment]
I do not think we still need this feature. In case it is needed later, we shall reopen the issue
