### ISSUE TITLE
XML not able to read special symbols in test

### ISSUE THREAD

**Issue by ashishpriyadarshiCIC** [weecology/retriever#1510]
These special characters are not recognized by xml
```
"   &quot;
'   &apos;
<   &lt;
>   &gt;
&   &amp;
```
This is causing issues for tests in #1507 

https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents

Note: We can come up with a solution and add this to test data

**Comment by ethanwhite** [comment]
Looks like this got address since #1507 was successfully merged.
