### ISSUE TITLE
North american breeding bird survey 

### ISSUE THREAD

**Issue by trashbirdecology** [weecology/retriever#1516]
Few things here. 
1. [NABBS is now on USGS ScienceBase](https://www.sciencebase.gov/catalog/item/52b1dfa8e4b0d9b325230cd9)
1.  [This link](https://catalog.data.gov/dataset/breeding-bird-survey-route-locations-for-lower-48-states-direct-download ), as provided in the [this webpage,](https://ecologicaldata.org/wiki/breeding-bird-survey-north-america) is 404. 
1. FYI -- [USGS Sciencebase has an api](https://www.sciencebase.gov/confluence/display/sciencebase/ScienceBase+Item+Services) you can hit to grab bbs, and any other data stored there.

**Comment by henrykironde** [comment]
Thanks @trashbirdecology we have updated these code however before we merge, was the region_codes data changed to `Migrants` and `MigrantSummary` data present in `MigrantNonBreeder.zip`

**Comment by trashbirdecology** [comment]
@henrykironde I am not sure

**Comment by henrykironde** [comment]
Since we do not have the regions codes data and this dataset is failing I will go ahead and update it with the current version.
We can update incase regions codes is not the migrant data

**Comment by henrykironde** [comment]
Thanks @trashbirdecology

**Comment by trashbirdecology** [comment]
Yeah, the region codes are currently buried in the metadata file.
