### ISSUE TITLE
PanTHERIA dataset

### ISSUE THREAD

**Issue by patdumandan** [weecology/retriever#1543]
PanTHERIA: a species-level database of life history, ecology, and geography of extant and recently extinct mammals: https://doi.org/10.6084/m9.figshare.c.3301274.v1

Dataset details:

PanTHERIA_1-0_WR93_Aug2008.txt -- 4629 records, not including the header row, ASCII text, tab-delimited, no compression scheme was used.

PanTHERIA_1-0_WR05_Aug2008.txt -- 5416 records, not including the header row, ASCII text, tab-delimited, no compression scheme was used.

**Comment by henrykironde** [comment]
Thanks you @patdumandan. The dataset  is now in the data retriever 👍
