### ISSUE TITLE
Add Soil db from canada

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1546]
https://open.canada.ca/data/en/dataset/6457fad6-b6f5-47a3-9bd1-ad14aea4b9e0

Pre-packaged CSV files | Dataset | CSV
Licence: Open Government Licence - Canada

has .gdb files too

**Comment by Sohan022** [comment]
@henrykironde 
I downloaded the pre-packaged CSV or XLS files through the above link, that file downloaded into zip format. There are 7 datasets inside the zip file. Can I create scripts using the command `retriever-recipes new_json`? I have no idea how to create scripts for the datasets inside zip file?

**Comment by henrykironde** [comment]
This has been solved. https://github.com/weecology/retriever-recipes/commit/b377df7ecde93db81f77c6acfda0f32ee101293a
For future reference, When the file has a zip, you unzip it and use retriever auto-create.
I have given an example https://github.com/weecology/retriever/issues/1555
