### ISSUE TITLE
Compare copy vs insert for raster2pgsql

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1553]
https://github.com/weecology/retriever/blob/e277c74281092cb79efdc974cd6dd78e7754e740/retriever/engines/postgres.py#L169
```python
        raster_sql = ('raster2pgsql -Y -M -d -I -s {SRID} "{path}"'
        raster_sql = ('raster2pgsql -M -d -I -s {SRID} "{path}"'
```

-Y  Use COPY statements instead of INSERT statements.

**Comment by Mohitkumar6122** [comment]
@henrykironde  Could you elaborate on what we have to do in this issue?

**Comment by henrykironde** [comment]
This is a performance test to compare what the better command is

**Comment by henrykironde** [comment]
We have moved on with Y `Copy`.
