### ISSUE TITLE
Solving issues labeled dataset request 

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1555]
For Folks asking about how to handle the dataset request issues, the retriever has a tool to enable you do the heavy lifting by creating for you a template. The `autocreate` tool can be used to create a starting script (template) for both tabular data and spacial data.

Sample example using the [airport script](https://github.com/weecology/retriever-recipes/blob/main/scripts/airports.json)(recipe) found in the retriever-recipes :
- To create the airport.json script, download the data into a directory with the name of the target dataset name . https://ourairports.com/data/
- The directory name cannot have `-` but you can use `_`
-Since this is tabular dataset(csv), we run retriever `autocreate` -dt tabular -d path_To_Directory/airports/
- This will create an `airports.json` script that you can populates and add it to the retriever through the [retriever recipe repo](https://github.com/weecology/retriever-recipes/blob/main/scripts)
- Compare you airport script with what is already in the retriever and read the docs on creating the scripts https://retriever.readthedocs.io/en/latest/recipes.html#script-creation
- In case you find anything in the docs that is not clear or needs editing, let the team know by creating an issue.

Note: for Zipped/Compressed files, extract them. In the script, you will have to define the type of extension/compression (zip, gz, ....etc)

**Comment by Mohitkumar6122** [comment]
@henrykironde  can you recheck the link [https://ourairports.com/data/](https://ourairports.com/data/) in the issue as on my side it is not reachable :(

**Comment by henrykironde** [comment]
Some more notes
Three types of datatypes -dt
- tabular -> csv 
- vector -> Shapefile, Geojson etc
- Raster -> Basically images

1) Run `retriever autocreate` using the right datatype and obtain the json file.
2) Populate the Json file as the description in the [developer docs](https://retriever.readthedocs.io/en/latest/recipes.html#script-creation)
3) Add the script into the [retriever-recipe](https://github.com/weecology/retriever-recipes/tree/main/scripts) repo and create a PR

**Comment by henrykironde** [comment]
@Mohitkumar6122 let me know if this is clear to you as well.

**Comment by Sohan022** [comment]
> Some more notes
> Three types of datatypes -dt
> 
> * tabular -> csv
> * vector -> Shapefile, Geojson etc
> * Raster -> Basically images
> 
> 1. Run `retriever autocreate` using the right datatype and obtain the json file.
> 2. Populate the Json file as the description in the [developer docs](https://retriever.readthedocs.io/en/latest/recipes.html#script-creation)
> 3. Add the script into the [retriever-recipe](https://github.com/weecology/retriever-recipes/tree/main/scripts) repo and create a PR

I have doubts regarding 3rd point. Do we not need to add scripts into [retriever](https://github.com/weecology/retriever/tree/main/scripts) repo or we have to add scripts into both repo  [retriever](https://github.com/weecology/retriever/tree/main/scripts) and  [retriever-recipe](https://github.com/weecology/retriever-recipes/tree/main/scripts)

**Comment by henrykironde** [comment]
Add the scripts in the retriever-recipe. Initially we used to keep scripts in the retriever repo but due to the increase in size and other factors, we now host the scripts separately.

**Comment by Mohitkumar6122** [comment]
> @Mohitkumar6122 let me know if this is clear to you as well.

Yeah, it is clear now.
Thanks 😄!

**Comment by henrykironde** [comment]
## How to test a newly created script.

We assume you are in the retriever-recipe repo and you have checked out the branch you want to work on.

- Check the created template after running retriever autocreate to see if the information looks correct.
    i.e 
```
Do the names of the fields in the template match the fields in the csv files (Or even look cleaned up but similar to the fields in the csv) - If dealing with tabular data

Do the fields look like they have been given the right data type. A field with  values like `20.00000` should not be of type char but double
```
  
- When you create a script, you should test if it actually works.  Some commands that I can run are:

Check if the new script name shows up in the list

`retriever ls`
 `retriver citation name-new-script`

Install the data into any engine
`retriver install csv name-of-new-scrpt`

**Comment by Mohitkumar6122** [comment]
> ## How to test a newly created script.
> We assume you are in the retriever-recipe repo and you have checked out the branch you want to work on.
> 
> * Check the created template after running retriever autocreate to see if the information looks correct.
>   i.e
> 
> ```
> Do the names of the fields in the template match the fields in the csv files (Or even look cleaned up but similar to the fields in the csv) - If dealing with tabular data
> 
> Do the fields look like they have been given the right data type. A field with  values like `20.00000` should not be of type char but double
> ```
> 
> * When you create a script, you should test if it actually works.  Some commands that I can run are:
> 
> Check if the new script name shows up in the list
> 
> `retriever ls`
> `retriver citation name-new-script`
> 
> Install the data into any engine
> `retriver install csv name-of-new-script`
@henrykironde I think we should add this to the documentation of retriever-recipes 
What are your suggestions ?

**Comment by henrykironde** [comment]
## When `retriever ls` does not show the name of the new script 

1) Make sure the working directory where you run `retriever ls` has the path `./script/new-script.json.` Meaning you should be in the retriever-recipes directory as your working directory.

2) The name of the file should always use `_`, the "name" key in the file should be the same as the file name but with` -` not `_`. 

3) The content of the file could have no ascii text or HEX like text  
```python
          {
            "name": "\ufeffsymbol",
            "size": "7",
            "type": "char"
          },
```
The encoding could be wrong  for example here we need "encoding": "latin-1" not "encoding": "utf-8",
```python
          {
            "name": "šàåmplë",
            "size": "7",
            "type": "char"
          },
```

**Comment by henrykironde** [comment]
Fixed in https://github.com/weecology/retriever/pull/1577
