### ISSUE TITLE
Link Broken of the 'Read The Docs'.

### ISSUE THREAD

**Issue by Mohitkumar6122** [weecology/retriever#1557]
Link of the **Read the Docs** section under **Running tests locally**  section in the [https://retriever.readthedocs.io/en/latest/developer.html#setting-up-servers](https://retriever.readthedocs.io/en/latest/developer.html#setting-up-servers) is broken.
<br>
Here is the broken link **MARKED IN RED**. <br>
![Image](https://i.ibb.co/D1J9yhb/Screenshot-2021-03-13-033600.png). 
<br> After visiting link<br>  
![Uploading image.png…](https://i.ibb.co/WWWsj02/Screenshot-2021-03-13-022353.png)

Kindly fix it .
Thanks.

**Comment by henrykironde** [comment]
This is kind of strange, the page loads fine on my end. Anyone else can’t see the docs?

**Comment by ethanwhite** [comment]
Opens fine for me. Maybe just a brief outage?

**Comment by Mohitkumar6122** [comment]
> This is kind of strange, the page loads fine on my end. Anyone else can’t see the docs?

It is still broken for my side. Can you check one more time .

**Comment by henrykironde** [comment]
Can you try to open the link in a private browser

**Comment by Sohan022** [comment]
No, it did not fix. Can I fix this issue?

**Comment by henrykironde** [comment]
Sure

**Comment by henrykironde** [comment]
@Mohitkumar6122 that you for reporting this. Let me know incase it is not solved
