### ISSUE TITLE
Confusion regarding Passwordless configuration in Postgresql.

### ISSUE THREAD

**Issue by Mohitkumar6122** [weecology/retriever#1562]
A lot of newcomers contributors gets confused with passwordless configuration and there is also not a lot of documentation reading this.
So I suggest that we should add a link to the official documentation of Postgresql on `The Password File` i.e [Password File](https://www.postgresql.org/docs/current/libpq-pgpass.html)  which will not only clear their doubts and also help them to learn more about Postgresql.
@henrykironde  What's your thought about/on this?.
Thanks.

**Comment by henrykironde** [comment]
This is good. Go for it
