### ISSUE TITLE
retriever ls -v command does not work 

### ISSUE THREAD

**Issue by Aakash3101** [weecology/retriever#1570]
While executing the ```retriever ls -v``` command, output is incorrect due to ```IndexError: list index out of range```.
Possible reasons are that some dataset json files have no license field or the license field is empty.
```
aakash01@aakash01-G3-3579:~/Desktop/gsoc/retriever (main)$ retriever ls -v
Offline datasets : 251

1. Abalone Age and Size Data
 abalone-age
[]
Database to aid in the prediction of the age of an Abalone given physical measurements
None
Lichman, M. (2013). UCI Machine Learning Repository [http://archive.ics.uci.edu/ml]. Irvine, CA: University of California, School of Information and Computer Science.

2. Long term limnological measures in Acton Lake, database, 1992-2017
 acton-lake
['lake', 'stream', 'nutrients', 'nitrogen', 'phosphorus', 'chlorophyll', 'LTREB', 'long-term', 'ecosystem', 'ammonium-nitrogen', 'nitrate-N', 'oxygen', 'carbon']
Long-term data collected from Acton Lake and its inflow streams, on a suite of physical, chemical and biological variables investigating how Acton Lake, responds to changes in ecosystem subsidies of detritus (sediments) and nutrients.
None
Michael J Vanni, Maria J Gonzalez, and William H Renwick. 2019. Long term limnological measures in Acton Lake, a southwest Ohio reservoir, and its inflow streams: 1992-2017. Environmental Data Initiative.

Traceback (most recent call last):
  File "/home/aakash01/anaconda3/envs/gsoc-dev/bin/retriever", line 8, in <module>
    sys.exit(main())
  File "/home/aakash01/anaconda3/envs/gsoc-dev/lib/python3.7/site-packages/retriever/__main__.py", line 150, in main
    licenses=str(script.licenses[0]['name']),
IndexError: list index out of range
```

**Comment by henrykironde** [comment]
@Aakash3101, thanks for reporting this issue. You may be having a script that is malfunctioning locally. Try to clean your repo. In case you have any changes, commit them and probably
1)  run `retriever reset scripts` and 
2) run `git clean -f` in both your working directory and the /script directory. Or `git clean -fd` if you do not have any project IDE setting that you don't mind removing.

**Comment by Aakash3101** [comment]
> @Aakash3101, thanks for reporting this issue. You may be having a script that is malfunctioning locally. Try to clean your repo. In case you have any changes, commit them and probably
> 
> 1. run `retriever reset scripts` and
> 2. run `git clean -f` in both your working directory and the /script directory. Or `git clean -fd` if you do not have any project IDE setting that you don't mind removing.

I was just too early for making the pull request. I will check this and let you know

**Comment by henrykironde** [comment]
@Aakash3101 you care correct, that is a bug

**Comment by Aakash3101** [comment]
Okay, it seems my exploration did help me find a bug!

**Comment by henrykironde** [comment]
Okey after a look at this, There may be some changes that we can test. 
I have noticed that with the python interface, we use the function [def datasets(keywords=None, licenses=None):](https://github.com/weecology/retriever/blob/bb06180a030d34eafa2e1ea13b74a3719df827e1/retriever/lib/datasets.py#L5).
This should be able to return what we are doing in the main (CLI interface) at [line](https://github.com/weecology/retriever/blob/main/retriever/__main__.py#L105).
 and the results can be printed

**Comment by henrykironde** [comment]
@Aakash3101 
Check the file lib/get_opts 
the way retriever `retriever ls -v ` works should be the same  as `retriever ls -k`

**Comment by henrykironde** [comment]
<img width="918" alt="Screen Shot 2021-03-30 at 4 47 55 PM" src="https://user-images.githubusercontent.com/5192965/113054652-af1d4980-9177-11eb-81ab-8400b85c7105.png">

**Comment by Aakash3101** [comment]
Okay I will have a look at this, and let you know about any further updates

**Comment by henrykironde** [comment]
Fixed
