### ISSUE TITLE
Update Docker file for the retriever

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1573]
We should update the docker file with a goal to have Python 3+

And/or  Postgres/Mysql installation(optional)

**Comment by Alt-Shivam** [comment]
Hey @henrykironde 
I want to work on this issue.
But a bit confused.
can you guide me on how should I get started.

Thanks

**Comment by dassaniansh** [comment]
Thank you @Alt-Shivam, this issue has already been completed, can you go through some other open issues,

**Comment by Alt-Shivam** [comment]
Thanks for the Clarification @dassaniansh.
