### ISSUE TITLE
Improve script creation platform to detect already existing data packages before we duplicate them

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1576]
**Easy:**

Before a user/developer spends time on the data, we should be able to tell if we already have that data in the retriever. 
Once the user gets the exact url of the data source. We should run a command to check all the urls in the scripts instance if the url exists.

**How to solve:**
User has a url of a data source, i,e. `new-data-source-url`
Use already available functions like 
[def SCRIPT_LIST(): ](https://github.com/weecology/retriever/blob/bb06180a030d34eafa2e1ea13b74a3719df827e1/retriever/lib/scripts.py#L108)
```
 for script in SCRIPT_LIST()
      check if the script resource url equals new-data-source-url
      if so, register any match
tell the user that we have found some matches in script name
or data not in the retriever yet
```

Sample usage should be something like
`retriever autocreate --check "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/bezdekIris.data" `
Data package Iris exist already

Note: Use [get opts](https://github.com/weecology/retriever/blob/main/retriever/lib/get_opts.py) to add the `--check`  for `retriever autocreate --check`

**Comment by dassaniansh** [comment]
I have tried working on this issue, how do I check if my implementation is correct?

**Comment by henrykironde** [comment]
Could you open a pull request. I could look through what you have done.

**Comment by henrykironde** [comment]
The design of the solution is almost as you have done but instead of checking for the `script ==dataset`, we want to check if the script object has an attribute 'url` and if that url is the same as what we have passed.

**Comment by dassaniansh** [comment]
@henrykironde sir, can you please look into this?

**Comment by henrykironde** [comment]
@dassaniansh, I commented on the Pull request. I need to seem some commands that you used to test this.
