### ISSUE TITLE
`retriever download` command throwing error.

### ISSUE THREAD

**Issue by Mohitkumar6122** [weecology/retriever#1583]
After running `retriever download iris`, I am getting this error : 
![image](https://files.gitter.im/606462c26da037398478bdfb/LB3L/image.png)

**Comment by ethanwhite** [comment]
I can confirm this as a general error with `download` from the CLI in the current `main`. The issue is not present in the current release and is also does not appear to be present in the Python interface for current `main` (which is why the tests aren't catching it).

```python
In [11]: rt.download('iris')
=> Downloading iris
Copying bezdekIris.data from /home/ethan/.retriever/raw_data/iris
Out[11]: <retriever.engines.download_only.engine at 0x7fd615759790>
```

**Comment by ethanwhite** [comment]
Thanks for reporting this @Mohitkumar6122! Can you check #1584 to see if that fixes things for you?

**Comment by Mohitkumar6122** [comment]
Thanks @ethanwhite, but when i run `rt.download('_dataset_name_')` it is working fine.
But when I run `retriever download '_dataset_name_'` it is still showing error.
![image](https://user-images.githubusercontent.com/47894634/114337564-ef64ca80-9b6e-11eb-96b9-9c715b592e83.png)
<br>
![image](https://user-images.githubusercontent.com/47894634/114339750-9481a200-9b73-11eb-9fff-999bd2237780.png)

**Comment by henrykironde** [comment]
@Mohitkumar6122 did actually fetch #1584 and run a pip install

**Comment by Mohitkumar6122** [comment]
> @Mohitkumar6122 did actually fetch #1584 and run a pip install

I didn't get it, what do you mean @henrykironde ?

**Comment by Aakash3101** [comment]
@Mohitkumar6122 He wants you to fetch the `upstream` and then checkout to branch `pr/1584`, and then run pip install

**Comment by ethanwhite** [comment]
Thanks for the clarification @Aakash3101!

@Mohitkumar6122 - you can fetch that PR using `git fetch upstream pull/1585/head:ethansPR`. `1585` is the number of the pull request and `ethansPR` is whatever you want to name it locally. You can then check it out using `git checkout ethansPR` and install using `pip install .` and see if it fixes your issues.
