### ISSUE TITLE
Add  nytimes covid data 

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1586]
https://github.com/nytimes/covid-19-data
Has about 5 files related to covid

**Comment by dassaniansh** [comment]
Hey @henrykironde , I would like to work on this issue. I have gone through the repository you mentioned. There are many dataset's present in that repository, which of them I need to add?

**Comment by henrykironde** [comment]
You need to go the readme page https://github.com/nytimes/covid-19-data#readme
They describe the data. When I skimmed through, the first files I saw were 

[Prisons:](https://github.com/nytimes/covid-19-data/blob/master/prisons) Cases in prisons
[Colleges:](https://github.com/nytimes/covid-19-data/blob/master/colleges) Cases on college and university campuses.
[Excess deaths:](https://github.com/nytimes/covid-19-data/blob/master/excess-deaths) The elevated overall number of deaths during the pandemic.
[Mask use:](https://github.com/nytimes/covid-19-data/blob/master/mask-use) A July 2020 survey of how regularly people in each county wore masks.
[Averages and anomalies:](https://github.com/nytimes/covid-19-data/blob/master/rolling-averages) A set of pre-computed rolling averages of cases and deaths for ease of analysis or


As you continue to read they point users to other files. So we shall need all these files.

Let me know if am clear

**Comment by henrykironde** [comment]
@dassaniansh, We needed this data so I went a head and created the script.
You can use this as a reference when creating the next package
