### ISSUE TITLE
Enable subsetting / clipping the spatial dataset to smaller extents

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1592]
Users may need just a small part of the raster or vector

For raster, we have come to a conclusion that Rasterio could be the better solution ,https://rasterio.readthedocs.io/en/latest/cli.html

@MarconiS 

ref :
https://mountcreo.com/article/gdal-translate-basics-functionality-and-examples/
https://joeyklee.github.io/broc-cli-geo/guide/XX_raster_cropping_and_clipping.html
https://duncanjg.wordpress.com/2012/11/20/the-basics-of-postgis-raster/

**Comment by henrykironde** [comment]
We can use this sample data https://zenodo.org/record/3355007#.YJrngH1Ki3A

**Comment by Nageshbansal** [comment]
@henrykironde, is it already implemented, if it isn't then can I work on this?

**Comment by henrykironde** [comment]
This has been handled. Thank you @Nageshbansal for the reminder.
