### ISSUE TITLE
Tidycensus dataset doesn't work with the download and install csv commands. 

### ISSUE THREAD

**Issue by kkothari2001** [weecology/retriever#1616]
https://github.com/weecology/retriever/pull/1606 introduced the tidycensus dataset. Since it uses the rpy2 library, it had to be made as a Python script instead of the usual JSON script.

On testing it on my local computer, I realised the commands `retriever download tidycensus --path PATH` and `retriever install csv tidycensus` do not seem to be working as expected. The dataset gets downloaded into the `.retriever/raw_data` folder, but no copying occurs to the given file path.

It seems to be an issue with the `WRITE_DATA_PATH` in the script and can be amended easily.

Can I work on this? @henrykironde

**Comment by henrykironde** [comment]
Thanks for catching this @kkothari2001, Please go ahead. I believe this is related to the issue #1617.

**Comment by kkothari2001** [comment]
Yes, I believe so @henrykironde.

I have found the error, the `engine.final_cleanup()` function wasn't working properly as the `data_path` property wasn't working properly. I solved it by setting the `data_path` and then calling the `engine.create_raw_data_dir()` function for the CSV and the Download engines.

**Comment by henrykironde** [comment]
Thanks @kkothari2001 for solving this issue
