### ISSUE TITLE
Excel xlsx file; not supported

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1628]
`xlrd` does not currently support `xlsx`
We can use `panda` and `openpyxl`

```python
import pandas as pd
df = pd.read_excel('sample.xlsx')
df_sheet_multi = pd.read_excel('sample.xlsx', sheet_name=[0, 'sheet2'])
# pandas_to_excel.csv
df.to_excel('pandas_to_excel.xlsx', sheet_name='new_sheet_name')
```

Repair:
https://github.com/weecology/retriever/blob/f9f435b848df167259aa9fb35612aa3da6c7fd12/retriever/lib/tools.py#L11
short term solution set `xlrd>=1.2.0`
https://github.com/weecology/retriever/blob/f9f435b848df167259aa9fb35612aa3da6c7fd12/requirements.txt#L2

**Comment by Nageshbansal** [comment]
@henrykironde, can you please tell me how to proceed with this issue .

**Comment by Nageshbansal** [comment]
@henrykironde, can you please tell me how to proceed with this issue?

**Comment by henrykironde** [comment]
It is not solved, Change the implementation of def excel_csv to use something like this

import pandas as pd
df = pd.read_excel('sample.xlsx')
df_sheet_multi = pd.read_excel('sample.xlsx', sheet_name=[0, 'sheet2'])
# pandas_to_excel.csv
df.to_excel('pandas_to_excel.xlsx', sheet_name='new_sheet_name')

**Comment by Nageshbansal** [comment]
okay , Thanks

**Comment by Nageshbansal** [comment]
@henrykironde, in excel_csv we want to convert a  file from excel to csv , then why we're calling to_excel method
```
df.to_excel('pandas_to_excel.xlsx', sheet_name='new_sheet_name')
```

**Comment by Nageshbansal** [comment]
@henrykironde, excel_csv should be like this right?
```
def excel_csv(src_path, path_to_csv, excel_info=None, encoding=ENCODING):
        df = pd.read_excel(src_path,sheet_name=excel_info[1])
        df_sheet_multi = pd.read_excel(src_path,sheet_name=excel_info[1])
        df.to_excel(path_to_csv, sheet_name='new_sheet_name')
  ```

**Comment by henrykironde** [comment]
I think this should work

**Comment by Nageshbansal** [comment]
okay, should i create a PR for this issue now ?

**Comment by henrykironde** [comment]
Sure

**Comment by Nageshbansal** [comment]
can you please check my PR #1640 first , so that I can make a new PR .

**Comment by Nageshbansal** [comment]
can you please check my PR #1640 first , so that I can make a new PR .

**Comment by henrykironde** [comment]
You can make a new PR using a different branch. Since those two PR have different changes, we shall have no issues. #1640 is still under review.

**Comment by Nageshbansal** [comment]
@henrykironde, we can close this issue now as we've already resolved this issue.
