### ISSUE TITLE
not able to use gdal==3.3.2 while working with ".shp" files

### ISSUE THREAD

**Issue by Nageshbansal** [weecology/retriever#1633]
## Expected behavior and actual behavior.
While I am having gdal 3.2.2, if I try to import ogr in a script dealing with ".shp" files, it doesn't import,
but if I downgrade my gdal to 3.0.2 I'm able to import ogr and script run successfully

 ### ogr_not_working
![ogr_not_defined](https://user-images.githubusercontent.com/76246968/149594012-9fb4e909-a9e9-45d6-8e07-cd3c1b1556c6.jpg)
### ogr_working
![ogr_working](https://user-images.githubusercontent.com/76246968/149594015-42a3bde7-5cbd-4ea1-949e-ba4cb529bfeb.jpg)

## Operating system
 Ubuntu 20.04 bit

## GDAL version and provenance
GDAL 3.3.2 version from ubuntugis-unstable PPA

**Comment by ayeankit** [comment]
Hey @henrykironde , is this still open? I would like to work on this.

**Comment by henrykironde** [comment]
Thank you @ayeankit but this should be closed since it was version specific. I have not been able to replicate the error. Feel free to open it if your gdal does not work as expected.
