### ISSUE TITLE
Improve test coverage 

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1637]
Currently Codecov code coverage is at 60%. Let us aim for 75%+

**Comment by Nageshbansal** [comment]
@henrykironde, I have to increase the number of tests so that test coverage can improve?

**Comment by henrykironde** [comment]
Some lines of code are not tested, so we need to identify them and try to create tests to cover those lines.

**Comment by Nageshbansal** [comment]
@henrykironde , i have made  65% code coverage , should I make PR now ?

**Comment by henrykironde** [comment]
Yes make a PR so that I can review the changes.

**Comment by Nageshbansal** [comment]
@henrykironde can you please assign this issue to me , I'm working on this and I already increased coverage up to to 65% by adding tests for socrata_create_dataset.

**Comment by Nageshbansal** [comment]
@henrykironde, I came to know about [SEDAC](https://sedac.ciesin.columbia.edu/) data source, it contains raster, vector datasets etc. We can add these datasets.
