### ISSUE TITLE
Create breeding bird survey for all releases.

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1644]
Currently we keep the latest version of` breeding bird survey` and `breed bird survey 50stop`. It would be nice to have all the four versions.
ie.
breed-bird-survey: 
https://github.com/weecology/retriever/blob/main/scripts/breed_bird_survey.py

breed-bird-survey-50stop:
https://github.com/weecology/retriever/blob/main/scripts/breed_bird_survey_50stop.py 

We can create copies of each for all the 4 versions.
->>

```j
breed-bird-survey-50stop-2001-2016 
breed-bird-survey-50stop-2017
breed-bird-survey-50stop-2018
breed-bird-survey-50stop-2019
```

```j
breed-bird-survey-50stop-2001-2016 
breed-bird-survey-50stop-2017
breed-bird-survey-50stop-2018
breed-bird-survey-50stop-2019

```

Child Items [(4)](https://www.sciencebase.gov/catalog/items?parentId=5af45ecee4b0da30c1b448db)[](https://www.sciencebase.gov/catalog/item/5af45ecee4b0da30c1b448db#)   
 [ 2001-2016 Releases (legacy format) - North American Breeding Bird Survey Dataset](https://www.sciencebase.gov/catalog/item/5d00efafe4b0573a18f5e03a)[](https://www.sciencebase.gov/catalog/item/5af45ecee4b0da30c1b448db#)
 [ 2017 Release - North American Breeding Bird Survey Dataset (1966-2016)](https://www.sciencebase.gov/catalog/item/5cf7d4d5e4b07f02a7046479)[](https://www.sciencebase.gov/catalog/item/5af45ecee4b0da30c1b448db#)
 [ 2018 Release - North American Breeding Bird Survey Dataset (1966-2017)](https://www.sciencebase.gov/catalog/item/5af45ebce4b0da30c1b448ca)[](https://www.sciencebase.gov/catalog/item/5af45ecee4b0da30c1b448db#)
 [ 2019 Release - North American Breeding Bird Survey Dataset (1966-2018)](https://www.sciencebase.gov/catalog/item/5d65256ae4b09b198a26c1d7)

**Comment by Lalitmohansharma1** [comment]
hello @henrykironde  what to do in this issue

**Comment by ethanwhite** [comment]
I wondering whether or not we want to support the change through time this way or whether we should be leaving that to users using the provenance functionality.

**Comment by henrykironde** [comment]
Yes nice catch, Provenance can enable users do that.

**Comment by henrykironde** [comment]
@Lalitmohansharma1 one of the users wanted historical version of the data, I was of the view to add all historical versions but the provenance tool can support storing those artifacts in time. I will close the issue.
