### ISSUE TITLE
JSON engine appends extra ] if multiple datasets are installed through GUI

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#165]
If in a single session of the GUI multiple datasets are installed using the JSON engine, all but the last installed dataset gets and extra `]` appended at the end. This is related to the use of `disconnect` to close out the JSON file.

I'm going to remove the engine from the build for 1.6 so that I can finish the release. Hopefully it can be cleaned up and added back in fairly quickly afterwards.

**Comment by rajat503** [comment]
Hi @ethanwhite ,
I was looking into this issue when I found that there is a circular dependency in csv.py and Engine.
When I tried running jsonengine.py, it tries to import the class Engine from retriever.lib.models which imports csv.py that again tries to import Engine hence resulting into an error "ImportError: cannot import name Engine".
Can you tell me how to fix this so that I can actually work on the JSON issue?

**Comment by ethanwhite** [comment]
Interest, I hadn't seen that come up before with `csv`, but I did run into something similar when writing the JSON engine. I suspect the issue is that we are trying to import the official `csv` Python module, but that because we have an engine named `csv.py` it is getting imported instead.

Try changing the name of `csv.py` to `csvengine.py` and also changing the appropriate line in `engines/__init__.py` from `csv` to `csvengine`.

**Comment by rajat503** [comment]
Thanks @ethanwhite , that fixed it. I can now run jsonengine.py without errors. 
As I am new to retriever, it would be great if you could tell me how can I see the JSON that gets generated and also the from where is it picking up the input/data?

**Comment by ethanwhite** [comment]
@rajat503 - the information on where the data is coming from is stored in the files in the `scripts` directory. The simplest ones to look at the any of the files ending in `.script`. To see what json gets generated you'll need to run the retriever. E.g.,

`retriever install json MoM2003`

You'll want to run both single table datasets like the command above and multi-table datasets, e.g.,

`retriever install DelMoral2010`

You'll also need to install datasets using the GUI, but running just

`retriever`

telling it to use JSON for the output, and then clicking on individual datasets to run them. It looks like the original bug report is for multi-table datasets run using the GUI.

You can then look at the contents of the resulting file(s), which will be in the same directory that you ran the retriever from. For this to work you'll need to enable the JSON engine by adding `jsonengine` to the list of engines in `engines/__init__.py`.

**Comment by rajat503** [comment]
@ethanwhite I have fixed this bug. Shall I send in the pull request?

**Comment by ethanwhite** [comment]
This is close in 640a2cfa0b750b9b5f60b9f21003fb68e3d08635.

There are still other issues with the JSON engine to be worked on.
