### ISSUE TITLE
Change scripts format to JSON

### ISSUE THREAD

**Issue by hlapp** [weecology/retriever#167]
Based on what I've seen so far, there seems to be nothing in scripts that couldn't be expressed in a straightforward manner in JSON. With JSON format you'd get a formal grammar and a parser for free, users can validate syntactic correctness easily in many environments, and you also get out-of-the-box interoperability with lots of stuff.

In contrast, `.script` looks like an invented format (of which of course we have far too few in bioinformatics), with no formal grammar, that requires a custom parser.

**Comment by ethanwhite** [comment]
YAML might be another good option here.

**Comment by ethanwhite** [comment]
Consider using http://dataprotocols.org/data-packages/#descriptor-datapackagejson. We aren't providing data packages in quite the way they are envisioning them (i.e., including data), but that doesn't mean that we couldn't mirror the meta data files and add some extra fields.

**Comment by hlapp** [comment]
:+1:

**Comment by ethanwhite** [comment]
We have a GSoC student applying to lead this change. A quick thought on implementation:

By moving to JSON we are going to make it more difficult for the average scientist to write a script, so we should give them a simple tool to make this easier. At the most basic I'm envisioning a command like tool with syntax like `retriever add datasetname` which then pops up a CLI that asks for each of the relevant values. We could also consider adding `retriever edit datasetname`, which does the same thing but prepopulates the values with with those in an existing JSON script. We could also add `retriever test datasetname` which tries to run a script with debug turned on to help folks figure out what's breaking. This functionality would also be useful to us for our plans to automatically test downloads on a regular basis to make sure the data hasn't changed under our feet.

**Comment by henrykironde** [comment]
Closing because it is covered in issue #487
