### ISSUE TITLE
SQL INSERT statements use custom quoting rather than parameter binding 

### ISSUE THREAD

**Issue by hlapp** [weecology/retriever#168]
Any reason you can't use parameter binding for binding values to SQL statements such as  `INSERT (...) VALUES (...)`? For most SQL engines, it's both faster and safer than using custom quoting and direct interpolation of values. It's certainly a lot less code (because the SQL engine does most of the type conversion and quoting).

**Comment by goelakash** [comment]
Does this mean that we should use a database wrapper with ORM instead? Because currently we do have parameter binding (Using `?` in `INSERT` statements instead of python's `.format{}` formatting).

**Comment by ethanwhite** [comment]
I think @hlapp is talking about this:
https://stackoverflow.com/questions/775296/python-mysql-parameterized-queries

We currently do the first version.

**Comment by henrykironde** [comment]
I guess after we have created the table with the right data types we just pass all data to the database as strings  %s in the[ insert statement function](https://github.com/weecology/retriever/blob/master/lib/engine.py#L608) 
from a quick look I think we need to change the lines from here to give the database  the %s  and then values .https://github.com/weecology/retriever/blob/master/lib/engine.py#L617.


```
cursor.execute ("""
            INSERT INTO Songs (SongName, SongArtist, SongAlbum, SongGenre, SongLength, SongLocation)
            VALUES
                (%s, %s, %s, %s, %s, %s)

        """, (var1, var2, var3, var4, var5, var6))
```

**Comment by Deborah-Digges** [comment]
@ethanwhite @henrykironde I'd like to take this up if nobody else is working on it.

**Comment by henrykironde** [comment]
@Deborah-Digges, Please do no one is working on it.
:+1:

**Comment by goelakash** [comment]
@ethanwhite That is completely dependent on the API of the database wrappers that we use (whether they take a single `str` argument or multiple). 
I am also of the opinion that since none of the data that retriever uses is hosted separately or sensitive in nature, we would not a 'safer' method to insert data in the DBs. But anything that @Deborah-Digges suggests or can improve upon should be valuable.

**Comment by Deborah-Digges** [comment]
@goelakash @ethanwhite @henrykironde based on @goelakash's observation, do you think that these changes would add value to the project?

**Comment by ethanwhite** [comment]
In general the database API wrappers all behave the roughly same way in Python. This makes it relatively easy to switch between database management systems and means that this should work. Examples for all three database APIs we interact with [1, 2, 3] show that the all take and prefer the:

`cursor.execute("SOME SQL WITH ? MISSING", ("SOMETHING", ))`

format, so I definitely think we should go for it.

[1] http://initd.org/psycopg/docs/usage.html#passing-parameters-to-sql-queries
[2] http://pymysql.readthedocs.io/en/latest/user/examples.html
[3] https://docs.python.org/2/library/sqlite3.html
