### ISSUE TITLE
GSoC 2024 - Getting started.

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#1680]
Thank you for your interest in our projects! To get started, simply refer to the developer documents. Begin by reading the README file for the project, followed by the Developers doc or developer guide. This will help you set up a functional development environment. Ensure you run tests on your environment, and check for a "getting started" or sample examples in the documentation. Go through these examples to confirm that your environment is ready for development.

Once you're set up, move on to the issues. We use tags/labels on the issues, and you can start by looking for labels like "good first issue." If anything doesn't work as expected, feel free to create new issues. We appreciate your contributions!

**Comment by Mu-Magdy** [comment]
Hi @henrykironde 

Hope you are fine, I am trying to reach you and other mentors but I didn't get any response. 
Can you tell me what is the main channel of communication to reach you?

**Comment by ethanwhite** [comment]
Congrats to the GSOC students joining us this year!
