### ISSUE TITLE
North American Amphibian Monitoring Program

### ISSUE THREAD

**Issue by davharris** [weecology/retriever#170]
The North American Amphibian Monitoring Program data is interesting, but it looks like it would be be a pain to get.  I thought I'd mention it here and see if anyone had ideas.

[It looks like](https://www.pwrc.usgs.gov/naamp/index.cfm?fuseaction=app.dataDownload) you have to specify one state at a time.  Then you enter your email address, and they send you a link where you can get it from their FTP server.  Then they query their database.  Then they upload it to their FTP server ~15 minutes later.  Then you can download it.  Then you repeat the process for the other 49 states.

I don't even know where I'd begin to write a workflow for this, but I thought I'd post it and see what people thought.

**Comment by ethanwhite** [comment]
I followed up with NAAMP and apparently their budget has been cut and this is in a huge To Do pile that is contingent on additional funding. I've offered to help consult on getting this done, but I think in reality this isn't going to happen any time in the foreseeable future. Given the one-off links to the FTP server this database can't really be supported at this time, so I'm going to go ahead and close this.
