### ISSUE TITLE
Add ability to encode supplemental information in scripts

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#172]
This is just a proposal for discussion at the moment.
### Issue

Many datasets contain metadata that is necessary for their use that isn't included in tables, but really should be. For example, the [Sevilleta small mammal data](http://sev.lternet.edu/data/sev-8) only includes species codes in the main data file. If you want the actual latin binomial you need to be it from this [web page](http://sev.lternet.edu/data/sev-008/4786).
### Proposed solution

For small amounts of data like this the most efficient way to access it might be encode it in the script as a separate table. e.g., 

```
ExtraTable: season,
                  {code,season
                  1,spring
                  2,summer
                  3,fall}
```
### Downsides
1. We are redistributing metadata, though it's hard to see anyone being too upset about that.
2. If the metadata changes how do we know about it?

**Comment by henrykironde** [comment]
Covered with the new json packaging system.
