### ISSUE TITLE
Add GloBI interaction data

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#182]
https://github.com/jhpoelen/eol-globi-data/wiki

**Comment by ethanwhite** [comment]
The single table tsv version of this data is available here:
https://depot.globalbioticinteractions.org/snapshot/target/data/tsv/interactions.tsv.gz

**Comment by shreyneil** [comment]
Sir, i am unable to access this data as whenever i try to access it through a reader ,the software itself gets hanged due to the huge size, any other way on how to access  the data, that you might have in your mind?

**Comment by ethanwhite** [comment]
To figure out the basic structure I would start by using the command line to grab a small piece of the data. E.g.,

```bash
head -200 interactions.tsv > small_interactions.tsv
```

would give you the first 200 lines of the file in `small_interactions.tsv`, which you could then easily open in the usual way. That will let you figure out the basic structure, which should let you write the `json` script. Since database management systems can work with data larger than RAM once it's loaded into a database it will be easier to work with.
