### ISSUE TITLE
Gentry line numbers inconsistent with plot area

### ISSUE THREAD

**Issue by dmcglinn** [weecology/retriever#186]
Each raw data file in the [Gentry dataset](http://www.wlbcenter.org/gentry_data.htm) contains a field called "Line" which indicates which transect line a particular species was recorded. The typical sampling regime for the dataset was to sample ten 100 m^2 samples; however, exactly 10 transects were not always collected. The published reference for the Gentry dataset is Philips and Miller (2002) which indicates the sampled area of each site.  In practice the following should hold: 

number_or_lines \* 100 = area_sampled

However, several of the sites have stems recorded in as many as 11 transect lines and Phillips and Miller (2002) indicate these sites should have a total area of 1000 m^2 not an area of 1100 m^2. 

site_id abbreviation
  28      POTOMAC
  37      SIERRARO
  96      ARARACUA
118      RIOMANSO
187      LIESJVAR
218      NEWCALDO

Additionally there are the following  two sites in which the number of lines is less than 11 (which is good) but the total area as recorded by Philips and Miller (2002) still does not match up.

site_id   abbreviation   notes
193        NDAKANNI     area is recorded as 800 sq m but it has 10 transect lines
194        BELINGA        area is recorded as 500 sq m but it has 6 transect lines

I have contacted the dataset contact Alyse Kuhlman (Alyse.Kuhlman@mobot.org) to see if she can inform me what is the best way to treat these inconsistencies. 

References:
Philips, O. and J.S. Miller. 2002. Global Patterns of Plant Diversity: Alwyn H. Gentry's Forest Transect Data Set. Missouri Botanical Garden Press.

**Comment by ethanwhite** [comment]
Closing since we haven't heard back. Not much to do about this one.
