### ISSUE TITLE
Allow indication of existing primary key in .json files w/o full column list

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#188]
Many existing datasets have a primary key and it would be nice to be able to indicate this in a .json file without having to list out all of the columns and their types. The frictionless data schema calls for

```
"primaryKey": "a"
```

or 

```
"primaryKey": ["a", "c"]
```

So we should use that and process it properly.

**Comment by ethanwhite** [comment]
I've updated this issue to reflect the new JSON script approach.

**Comment by henrykironde** [comment]
I think we need to update this issue or close it.
Scripts can have more information added, but we are currently not processing this information. We shall need specific reasons or goals to process such information.

**Comment by ethanwhite** [comment]
I'm fine with closing this.
