### ISSUE TITLE
Support for BIOM format (biological observation matrix)

### ISSUE THREAD

**Issue by davidelliott** [weecology/retriever#195]
The BIOM format is described at http://biom-format.org as "a general-use format for representing biological sample by observation contingency tables. BIOM is a recognized standard for the Earth Microbiome Project and is a Genomics Standards Consortium supported project."

The format is used by many microbial ecology tools like QIIME, Phyloseq, and MG-RAST which is also a repository. Support for this format might therefore help bring microbial data into the retriever. 

Just a suggestion.
Regards

David

**Comment by ethanwhite** [comment]
Closing since this is really stale and is the kind of special format that we'd need an expert to help support.
