### ISSUE TITLE
Clean install from source leads to unwriteable .retriever directories

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#206]
If you install the retriever from source and there are not an existing `~/.retriever/raw_data/` and `~/.retriever/scripts/` directories, these directories are created on install. Since the source install requires the use of `sudo` these directories are owned by `root` and when the retriever is run (typically using non-elevated privileges) it cannot write to those directories.

Removing the directories or changing their ownerships solves the problem, but this should be avoided.

**Comment by lyttonhao** [comment]
Hi, I've install the Retriever and see this problem. I'm a little confused about why it is not appropriate to change the ownership of these directories to the user who installs the Retriever.

**Comment by ethanwhite** [comment]
Hi @lyttonhao - Sorry about that. You're right that the correct behavior is definitely to have the ownership of these directories be the user who does the install. The problem is that by default when installing as a super user ownership ends up getting set to `root`. This definitely needs to be fixed, we just haven't had time to do it yet.

**Comment by lyttonhao** [comment]
Thank you for the response @ethanwhite. I will try to fix it by changing the ownerships in the code and see if it works.
