### ISSUE TITLE
Gentry counts table ELCORAZO site has different data structure than all other sites

### ISSUE THREAD

**Issue by dmcglinn** [weecology/retriever#217]
This issue was imported from https://github.com/weecology/retriever/issues/185#issuecomment-41485628 via @ethanwhite 

In the `counts` table of the Gentry dataset the site with `site_code` ELCORAZO has a different data structure than the other sites. Specifically, it stores one stem/row with count=1 instead of one species-transect combo/row with a count of the number of individuals. This means two things:
1. Most problematic, if there are any instances of multiple-stems/individual then we lack reliable counts of individuals for this site. We only have information on the number of stems. Dan McGlinn checked the data book and did not find any multiple stems at this site so this may be a non-issue in theory. 
2. It's possible that some query's will get tripped up by this site. Most of the queries I can think of should be OK, because typically one would either sum over transects to get species-level counts for the site (which should work fine with the current structure) or work at the transect level in which case this site would get nulled-out anyway, but I am still a bit concerned about including this differently structured data. We could probably clean this up if my first point turns out not to be an issue, but I'd be curious to hear folks thinking on what that should look like (since we don't have transect information).

**Comment by ethanwhite** [comment]
Given the lack of interaction from the data providers I'm not sure that any cleanup here will reach the top of our To Do list, so I'm going to go ahead and close this. If someone working with Gentry wants to do some more work here it would be welcome. Feel free to reopen.
