### ISSUE TITLE
Robert: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by rrbm823** [weecology/retriever#219]
Hello my names robert! I'm interested in helping this project mostly because I want to get into ecology. But also I have background in writing Web scrapes in R and java, and I'd like to try out writing software with python. <p><br><blockquote>This issue was created by @rrbm823 via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by ethanwhite** [comment]
I'm going to go ahead and close this since it's served it's purpose. Open another issue any time if you're interested in working on things and have any questions.
