### ISSUE TITLE
Cross-tab restructuring only works when adding primary key

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#241]
Scripts for handling cross-tab data are only currently working if an auto-number primary key is added by the Retriever. To replicate:

1. Create a new script for handling cross-tab data
2. Don't including a `pk-auto` column

This will result in an index out of range error.

The source of the issue is probably related to Line 62 of `lib/engine.py`.

**Comment by henrykironde** [comment]
validation and closing needed for this issue

**Comment by henrykironde** [comment]
closing fixed in 	27f02f2
