### ISSUE TITLE
Auto-numbered primary keys should start from 1 for each table

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#246]
In some cases when generating auto-numbered primary keys for more than one table the auto-numbers continue to advanced from one table to the next. e.g., the first tables primary key will end at 35455 and the next tables primary key will start at 35456. Every tables auto-numbered primary key should start at 1.

**Comment by henrykironde** [comment]
@ethanwhite any dataset to replicate this case

**Comment by ethanwhite** [comment]
The Portal dataset is where I'd seen it before, but as you can see in #528 the whole dataset is actually erroring at the moment.

**Comment by henrykironde** [comment]
validation and closing needed for this issue

**Comment by henrykironde** [comment]
closing fixed in #546 8766cd9
