### ISSUE TITLE
Use sqlalchemy to reduce customization for SQL engines

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#251]
http://www.sqlalchemy.org/ is designed to making interacting with different SQL database management systems more seamless. Using it should reduce our need to make customizations for each DBMS that we support.

**Comment by mbjones** [comment]
@ethanwhite This being one of those theory versus practice things :)  Good luck with the ORM, but in my experience it tends to just introduce different complications.  And restricts what you can do with the data.  And causes scaling headaches by preventing query optimization or making it convoluted. `EXPLAIN` is a dear friend.

Instead, I have usually tried to be assiduous at sticking to true SQL-compliant SQL. If you are dealing with other people's data and it has all sorts of non-standard stuff in it (like db-specific data types, mysql enums, etc.), then maybe sql alchemy will make sense.  Would love to hear how this goes for you.

**Comment by bendmorris** [comment]
I'm split on this - @mbjones makes a good point and doing everything in SQL as we are now allows us to be explicit about what we're doing and exactly what we want the output to look like.

Also, I'm curious whether this would decrease or increase our code size. From a quick look back, the SQL engines actually have very little platform-specific code in them. Some of this we'd still want to keep - MySQL's "LOAD DATA LOCAL INFILE" and MS Access's custom data file loading method, for example. On balance, if the code size is roughly the same, I'd vote against introducing an extra dependency.

**Comment by bendmorris** [comment]
Also for the record, sqlalchemy's MS Access support is not guaranteed to work:

http://docs.sqlalchemy.org/en/rel_0_9/dialects/

**Comment by ethanwhite** [comment]
Thanks for the feedback @mbjones and @bendmorris. It's good to know that the ORM comes with it's own set of challenges. Add in Ben's point that we don't have a ton of DBMS specific customizations beyond the bulk imports, which the sqlalchemy probably won't handle, and the fact that there are lots of other things to be done, and I'm going to go ahead and close this.
