### ISSUE TITLE
add eBird Reference Datasets

### ISSUE THREAD

**Issue by brymz** [weecology/retriever#252]
This conversation started with Issue #90 (github.com/weecology/retriever/issues/90).

The eBird Reference Data is located for public access at http://ebird.org/downloads/erd/.

The data are two complete catalogs of 'checklists' at the nested spatial extents of 'Western Hemisphere' and 'lower 48 United States'. The data are archived as .tar.gz files. 

The 48US data is broken up in a directory by year. There is a directory for each year from 2002-2013 and one for pre-2002. The pre-2002 has records as early as the late 1800s. In each year's directory are 3 files checklists.csv, core-covariates.csv, and extended-covariates.csv. Each record in the data corresponds to a sampling event or 'checklist'. checklists.csv contain all of the 'checklists' for the directory's year. There are 17 fields of sampling event details and then 1,767 columns of species names for species count. 

Other important details about the data:
- Missing / unknown variable = '?', with correspoding covariate measurement error = NA.
- Species count reported as present without a count = 'X'.
- Group submissions replicate checklists present in the data set. Use PRIMARY_CHECKLIST_FLAG for set of unique checklists.

Further information regarding the contents of the data files and additional information about the data is included in document files in the 'doc' directory. The 'doc' directory includes .name files that list all of the species in the crosstab columns and the covariates.  For instance checklists.names includes a list of all 1700+ species names that are included as columns for each checklist. From a glance at the first 50 or so it appears the .names file shares the order of the columns. 

The WestHem is smaller than the US48 file on download, but it certainly opens up to be larger. I was not able to decompress the WestHem data because it grew larger than the 70 GB of space I have available on my machine. From the document file, the WestHem is similar to the 48US in format and contents except with a larger spacial extent and no core-covariates.csv table. The extended-covariate.csv table might also be slightly different.

**Comment by ethanwhite** [comment]
My initial thought is to restructure the existing data as follows:

1. Create a checklist table that includes the first 17 fields of the checklists table, and an added indication of whether a checklist is count or presence/absence (assuming that entire checklists either use numbers or Xs - need to check this).
2. A surveys table that includes the de-cross-tabbed, version of the other 1700 columns, dropping the zeros, and replacing Xs with ones (again, assuming that entire checklists either have all Xs or none).
3. Join these on SAMPLING_EVENT_ID assuming that this is a unique field and doesn't have duplicates due to the replicate checklist issues.

**Comment by ethanwhite** [comment]
The assumption that entire checklists were either counts or presence/absence is not correct.

**Comment by brymz** [comment]
Go figure. I'd say two tables are still a good idea (counts,
presence/absence). Though, the process will have to be broken up into three
(counts, `x`s, both), with the 'both' appended to the counts and
presence/absence tables.

On a similar note, I'll say I'm skeptical of the idea that absence can be
confidently generated from this data. eBird strongly encourages use of
their data in that way, but from what I've seen in the metadata and methods
I don't agree. I mention this now because removing the zeros may (or may
not) help this process.

**Comment by ethanwhite** [comment]
@brymz I think you're probably right, but we'll have to use something other than 0 and 1 to indicate presence/absence. Possibly -1 for presence. I'm looking into what they do the in EOD for this now.

**Comment by ethanwhite** [comment]
Since  it seems that eBird is basically stepping back from keeping any of it's data public I don't think this is a priority for us anymore. If they become more open we can reopen this and reconsider.
