### ISSUE TITLE
add eBird Stratified Random Design Datasets

### ISSUE THREAD

**Issue by brymz** [weecology/retriever#253]
This conversation started with Issue #90 (github.com/weecology/retriever/issues/90) and continues with the 'add eBird Reference Datasets' (Issue #252.) 

The eBird Stratified Random Design data is located for public access at http://ebird.org/downloads/erd/.

The data are three companion datasets to the Reference Data (#252) at various spatial extents and resolution. The data are archived as .zip files that decompress to a single .csv file. The spatial extent and resolution for each file is as follows: lower 48 US at 30km; lower 48 US at 3km; Western Hemisphere at 1.5km. The file naming convention is: srd_point_data_EXTENT_VERSION.csv, where EXTENT is a value (30km, 3km, 1.5km) and VERSION is a value (v1.0, v3.0). 

Each file contains 'predictor variables' that are intended for use in ecological models to generate maps and predictor surfaces. The 'predictor variable' appear similar to the core covariates and extended covariates from the Reference Data (#252). I did not find any documentation directly related to this data other than a comment in the Reference Data documentation that acknowledges the version of the extended covariates program that is used in the Stratified Random Design data.

**Comment by ethanwhite** [comment]
Since  it seems that eBird is basically stepping back from keeping any of it's data public I don't think this is a priority for us anymore. If they become more open we can reopen this and reconsider.
