### ISSUE TITLE
add eBird Observational Dataset

### ISSUE THREAD

**Issue by brymz** [weecology/retriever#254]
This conversation started with Issue #90 (github.com/weecology/retriever/issues/90) and continues with the 'add eBird Reference Datasets' (Issue #252) and 'add eBird Stratified Random Design Data' (Issue #253) 

The eBird Observational Dataset is located for public access at  https://dataone.ornith.cornell.edu/metacat/d1/mn/v1/object/CLOEODDATA.05192014.1

The data downloads as CLOEODDATA.05192014.1.gz, though the website suggests it could also be named eBird_Observation_Dataset_2013.csv.gz.

I don't remember if we checked a line count for this one or the Basic Dataset, but my counter has it at 150,000,000.

The table format seems to be ready for the retriever. Column names are: 
BASISOFRECORD, INSTITUTIONCODE, COLLECTIONCODE, CATALOGNUMBER, OCCURRENCEID, RECORDEDBY, YEAR, MONTH, DAY, COUNTRY, STATEPROVINCE, COUNTY, DECIMALLATITUDE, DECIMALLONGITUDE, LOCALITY, KINGDOM, PHYLUM, CLASS, ORDER, FAMILY, GENUS, SPECIFICEPITHET, SCIENTIFICNAME, VERNACULARNAME, INDIVIDUALCOUNT

**Comment by ethanwhite** [comment]
This is in progress in #286.

**Comment by ethanwhite** [comment]
Add in #286.
