### ISSUE TITLE
Automate Oceanic Biogeographical Information System Dataset Downloads

### ISSUE THREAD

**Issue by brymz** [weecology/retriever#256]
The OBIS mapper (http://iobis.org/mapper/) contains a large number of datasets some with a high spatial extent or time span. OBIS catalogs the Census of Marine Life (http://www.coml.org/) and openly supports open access and widespread use of its data. 

However, accessing the data requires interaction with the OBIS mapper and a GUI browse and download process that seems to be incompatible with automation.

There are a number of datasets from the core-transient group on OBIS that would benefit from working out a solution around the GUI. An example is listed on the EcoData Wiki: http://ecologicaldata.org/wiki/bahamas-marine-mammal-research-organization

**Comment by ethanwhite** [comment]
I'm going to go ahead and say that we won't support this dataset until direct bulk downloads are possible.
