### ISSUE TITLE
Baldridge 2012 citations import

### ISSUE THREAD

**Issue by embaldridge** [weecology/retriever#260]
Title field of the citations table sometimes splits a single record into multiple records.

**Comment by embaldridge** [comment]
It's in the dataset.  I opened up the raw file using Calc, and Excel and the viewer on figshare were hiding some problems.  I'll fix the file, upload it to figshare, and send a pull request with the updated script.

**Comment by ethanwhite** [comment]
Perfect. Thanks!!
