### ISSUE TITLE
Reserved keyword 'order' not being properly replaced

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#292]
`clean_column_name()` in `table.py` should replace the column name `order` with `sporder`. It does not appear to be doing this in #286.

**Comment by ethanwhite** [comment]
Looks like `clean_column_name()` is only called in `auto_get_columns()`, so it only gets triggered when reading columns from a header row of a file. I suspect that it won't be uncommon that someone writing a script that requires providing column names will accidentally include either bad characters or reserved keywords, so we should probably always run `clean_column_name()`.

**Comment by panks** [comment]
This should be as easy as just calling clean_cloumn_name() every time we manually set columns, right? or you have something else in mind?

**Comment by ethanwhite** [comment]
At first glance it looks like, in `tables.py`, maybe adding something like Line 39 in `auto_get_columns` to `get_insert_columns` might be the simplest and most robust solution.

**Comment by panks** [comment]
I was thinking maybe we could do something like override __setattr__ for table class, that way every time **column** is updated/assigned we just clean it up before adding to dictionary. But I guess as you said, cleaning them up in get_insert_columns, seems simpler.

**Comment by ethanwhite** [comment]
Feel free to try it either way and we can discuss it more when we have a PR
to look at.
