### ISSUE TITLE
BBS50 column names off by one due to change in raw data

### ISSUE THREAD

**Issue by davharris** [weecology/retriever#297]
I tried downloading the BBS50 data using the GUI (version 1.7.0 on a Mac running version 10.10.2 of the OS) and exported it to an SQLite database.  The results of the "count" table are shown below.

![](https://cloud.githubusercontent.com/assets/843017/7014630/133d9648-dc7c-11e4-8d01-20d9a05a34a5.png)

Everything seems to be off by one column (e.g. RPIDs in the "year" column, years in the "AOU" column, AOU numbers in the "Stop1" column...).

The other tables seem not to have this problem.  I get the same off-by-one problem whether I read the saved database into Firefox's SQLite manager or into R via RSQLite.

Just in case this is relevant, I should also note that I included the Avian body size table in the same database.

Any thoughts on what might be going on? I'd be happy to send checksums or other diagnostic information if you'd like.

Thanks

**Comment by ethanwhite** [comment]
At a first glance it looks like the data structure of the raw files changed. I'm installing it now to take a closer look.

**Comment by ethanwhite** [comment]
Yep, they added a new column. Keeping up with BBS's data structures is a full time job :)

One of these days I'm going to get a full test server set up that sends us a warning every time the hash of any of the installed versions of any of the databases changes so that we can catch these kinds of changes more proactively.

I'm running a full test now just to make sure there aren't any additional hiccups and then I'll get a fix pushed.

Thanks a lot of reporting this @davharris! It's people like you that help us all have nicer things.

**Comment by akshayah3** [comment]
> One of these days I'm going to get a full test server set up that sends
us a warning every time the hash of any of the installed versions of any of
the databases changes so that we can catch these kinds of changes more
proactively.

Sounds great!

**Comment by ethanwhite** [comment]
I know have this working fine in Postgres:
https://github.com/ethanwhite/retriever/tree/bbs50-fix

But for some reason the last column is coming up null in SQLite.

**Comment by ethanwhite** [comment]
Sorry for the delay. This is fixed by #299.

If you just replace `bbs50stop.py` in `~/.retriever/scripts/` with the version now in `master` everything should work as expected.

I'm also planning on getting a new release out the door in a next week or two.

**Comment by davharris** [comment]
>If you just replace bbs50stop.py in ~/.retriever/scripts/ with the version now in master everything should work as expected.

Thanks Ethan.  I'm confused, though.  I thought retriever automatically updated its scripts via `retriever --update`?

**Comment by ethanwhite** [comment]
> I thought retriever automatically updated its scripts via retriever update?

Yeah, that's how it is intended to work, but the system to handling scripts and releases is not working properly at the moment. Scripts can be patched manually, but it has to be done for each previous release. The truth is that that entire system needs a few days worth of thought and work and I just haven't had the time to get it all cleaned up and working optimally. This is definitely high on the list as soon as I have time or get someone hired who can take care of it.

**Comment by ethanwhite** [comment]
Are you running 1.7? If so let me know and I'll get it patched so that you can use `--update`.

**Comment by davharris** [comment]
Yes I’m on 1.7. Thanks!

Maybe the long-term solution is just to have retriever do something like “git pull”, i.e. to call some existing software which figures out what’s already up-to-date and what needs to be updated, then downloads it.

Dave

**Comment by ethanwhite** [comment]
> Maybe the long-term solution is just to have retriever do something like “git pull”, i.e. to call some existing software which figures out what’s already up-to-date and what needs to be updated, then downloads it.

Yes, that's exactly how it's *supposed* to work :)

**Comment by ethanwhite** [comment]
> Are you running 1.7? If so let me know and I'll get it patched so that you can use --update.

Actually, now I remember why I hadn't done this already and it's part of the larger issue with reworking how we're handling this. So, I can't get this to work with `--update` for you in `1.7`. Apologies. I'm hoping to get `1.8` in the next few weeks at which point the script will work without patching.
