### ISSUE TITLE
Utility of try/except in table.values_from_line

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#298]
In `table.values_from_line()` there is the following for loop with a try/except:

```
for value in self.extract_values(line):
    column += 1
    try:
        this_column = self.columns[column][1][0]
        ...
    except:
        # too many values for columns; ignore
        pass
```

The `except` allows the retriever to keep running even if there are too many values in the row to fit in the designated fields/columns. At first glance this seems like it might be dangerous since it may allow data that isn't properly matched up with the description of that data to run by simply dropping the extra columns. I recently debugged a case where the primary key wasn't being handled properly that should have errored, but instead silently made the last column of data null.

@bendmorris - do you have any thoughts on this or remember why it was included originally? Thanks.

**Comment by bendmorris** [comment]
I don't remember why this was being ignored, but there was probably a reason. I think there were instances of badly formatted datasets with extra whitespace after the correct number of columns. Shouldn't hurt to take it out and run the tests to see if there are any obvious culprits.

**Comment by ethanwhite** [comment]
Turns out that some datasets have extra trailing delimiters (you know, just for fun) and this is handling them. E.g., `bird-size` has a bunch of extra trailing tabs on every line. There may be a cleaner way to handle this, but the code is definitely needed until that is found, so closing.
