### ISSUE TITLE
Should "ref" or "url" be a default tag 

### ISSUE THREAD

**Issue by dmcglinn** [weecology/retriever#301]
The new script generation approach creates a generic file that lacks the ref or url tag. I think this tag should be included on the generic script because all of the datasets are coming from someplace online. Examining some of the script files suggests to me that the tags "ref" and "url" can be used interchangeably. Essentially this tag ensures that when browsing for datasets using the retriever you also see a hyperlink to the dataset.

**Comment by ethanwhite** [comment]
Sounds good to me. Do you want to give adding it a go?
