### ISSUE TITLE
Overhaul script updating system

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#318]
The script updating system needs some attention so I'm creating this issue to house high level discussion and planning for this update.
#### 1. Do we want to have separate software releases and script updates?

The current design is intended to let us updating scripts without a new software release.

The nice thing about this is that it's relatively easy to add or update a script, so we might not want to have to roll a new release every time we get a few of these. Perhaps more importantly users may not update the retriever with every release and so if we fix a bug in a script we want them to get the update without any extra work.

The downsides are two fold. First, this makes provenance and reproducibility a little trickier. You need to know both what version of the retriever was used, but also what version of the scripts. Second, it means that the core code is more complicated because it has to handle checking for new scripts and downloading them. We've had a number of issues over the last year related to complexities in this system and as a result it isn't currently accomplishing the goal of actually letting us update scripts.

If we want to keep this separation then there are a number of things below that we need to think about. If we don't then we would just start distributing the scripts with each release.
#### 2. Scripts should not be tied to a release (or be so tied in a more sophisticated way)

Currently the scripts being downloaded are tied to an individual release. When the retriever grabs scripts it looks for them under the tag for that release. This sort of worked a while back when releases were in separate branches, because you could go update the branch for each release with the new script. This wasn't a great solution, but it worked. Now that we are using tags for releases this doesn't work any more because tags are intended to be immutable.

The challenge is doing this in such a way that it allows for changes or additions. In the past we accidentally broke older versions of the retriever by adding scripts for new (just developed) database engines that the older versions of the retriever didn't know about. It tried to load the scripts and errored. We've fixed this in a718c8d798903f1e096c4fb5ca0da9354a1dd536 so that at least things will keep working, and maybe that's enough. We may also just want to view anything that would cause challenges to the script system as a major version upgrade.
#### 3. Improve checking of scripts for updates

The current implementation is intended to check to see if updated scripts exist by comparing hashes of the existing scripts with published hashes of the currently available scripts. If the hashes don't match then the script is supposed to be updated. This has caused issues with development versions resulting in 495d88dda5cdae17e1067759c16080e21f6c3d41, but this means that leads to an error prone flag change with releases to indicate whether the retriever is running as a release or development version.

**Comment by ethanwhite** [comment]
#### Initial thoughts

1. I like @bendmorris's original design of allowing updating scripts without a full release and so I'd like to keep it.
2. We could have scripts releases where we have a structured tag that indicates a scripts release. This would be as easy as tagging master when we want to update one or more scripts and we could potentially design it in such a way that different major releases of the retriever use different sets of tags. e.g., if the following tags exists: `scripts1.0`, `scripts1.1`, `scripts2.0`, `scripts2.1`, `scripts2.2` then retriever 1.x will use `scripts1.1` and inform the user that a new major release is available and they should upgrade and retriever 2.x will use `scripts2.2`.
3. If we do something like this scripts release system then we should make it possible to pass an optional scripts release to the retriever so that with a specific version of the retriever installed you can use a specific version of the scripts, e.g., `retriever install sqlite MoM2003 --scripts-version 2.1`. In combination with some functionality to report the scripts release being used this should allow a fully reproducible workflow.

This is all just off the top of my head and I'd love to hear other thoughts and ideas about how to improve this.

**Comment by ethanwhite** [comment]
Another idea for how to implement separate software and scripts updates:

Split the scripts out into their own separate repo. We don't currently package them anyway, they are always downloaded, so this isn't any more difficult for users. However it would potentially make setting up a development environment more complicated.

**Comment by ethanwhite** [comment]
See also #388, which will be superseded by this decision.

**Comment by ethanwhite** [comment]
The plan for handling this is to move towards a system where:

* Scripts are always updated from `master`
* Scripts have their own version number for tracking provenance
* Scripts have a 'minimum retriever version' to prevent conflicts with new features. Only scripts that have minimum retriever versions <= the running version of the retriever will be loaded. Users will be notified that a new version of the retriever is available if a script has a minimum retriever version > than the current retriever version.

Implementing these changes and cleaning up old issues will involved:

- [ ] Add a script version to each individual script, starting all scripts at 1.0.
- [ ] Add minimum retriever version to each individual script, starting at 2.0.
- [ ] Update `version.py` to make `version.txt` with script version numbers (and possibly minimum retriever versions) and removes hashes.
- [ ] Update `version.py` to check scripts that have been changed (i.e., that have diffs) to see if the script version numbers have been changed, and if not, increment them
- [ ] Add a pre-commit hook that checks if there are changes in `./scripts/` and if so runs `version.py` and runs `git add version.txt`
- [ ] Update the code that handles checking for scripts changes (currently using hashes) to check based on script version numbers and then only download scripts where the script version number of the local version is less than the script version number in `version.txt`. This code may also need to be fixed more generally as it wasn't working on some recent releases.
- [ ] For installs via `pip` and our installers add all scripts to `.retriever/scripts/` on install. (just automatically running `retriever update` at the end of the installation process)
- [ ] Remove code related to `MASTER = TRUE`

**Comment by henrykironde** [comment]
script [MammalSuperTree](https://github.com/weecology/retriever/blob/master/scripts/MammalSuperTree.py) has some issues that we need to address #208. Any comments

**Comment by ethanwhite** [comment]
> script MammalSuperTree has some issues that we need to address #208. Any comments

I'm not sure what you're looking for here. Can you expand a little?

**Comment by henrykironde** [comment]
Do we still need to perform the check` if (VERSION == 'v1.6') or (VERSION == 'v1.6.0'):`

**Comment by ethanwhite** [comment]
I think we should remove that check at the same time that we remove the `.script` files from `master` since that will be the point we decide to permanently break `1.6` to let us move forward more smoothly.

**Comment by ethanwhite** [comment]
I have added a new issue to take care of the last two pieces of this task. We moved those last pieces to the 2.1 milestone. Closing this issue as complete.
