### ISSUE TITLE
Switch to an explicit retriever-gui for running the GUI

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#323]
Right now running `retriever` without any arguments runs the GUI. Typically for CLI programs this should print out the help instead. If you do this on a machine without `wxpython` installed it results in an error, which could be fairly confusing since the software will actually work just fine from the command line.

I think we should switch to a separate script for launching the GUI: `retriever-gui`. This is common practice for things like `shp2pgsql` (which has `shp2pgsql-gui`) and other dual GUI/CLI programs.

**Comment by Deborah-Digges** [comment]
https://github.com/weecology/retriever/pull/499 closes this issue as well. What do you think, @ethanwhite ?

**Comment by ethanwhite** [comment]
Definitely. Thanks!
