### ISSUE TITLE
Add ability to import spatial data to PostgreSQL/PostGIS

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#325]
PostgreSQL with the PostGIS extension allows spatial data to be stored in a way that allows spatially explicit querying. It would be nice to support this in two ways:
1. Allow importing of strictly spatial files (rasters, shapefiles, etc.). These kinds of files could only be imported into PostgreSQL.
2. Allow importing tabular data that has a spatially explicit component (e.g., site locations with latitudes and longitudes) as a spatially enabled table.

The later should be optional and both approaches would need to be constrained to PostgreSQL and any other formats (HDF5?) that support spatially explicit data.

**Comment by ethanwhite** [comment]
Also SQLite using http://www.gaia-gis.it/gaia-sins/

**Comment by jainamritanshu** [comment]
@ethanwhite @henrykironde I would like to work on this.

**Comment by ethanwhite** [comment]
Implemented in 7d84795b942e5bb99863a476cf0a00969614a1a4.
