### ISSUE TITLE
Retriever fails to open on Windows 7 Enterprise

### ISSUE THREAD

**Issue by ahhurlbert** [weecology/retriever#328]
EcoData Retriever only opens on my machine 50% of the time. The other 50%, I get the opening window and it displays the loading of all the dataset scripts but then both windows immediately close.

This happens on a Windows 7 Enterprise machine, but I cannot duplicate the problem on a regular Windows 7 machine (in addition to all the other environmental differences of course).

**Comment by ahhurlbert** [comment]
As of the latest installation downloaded today, Retriever fails to open 100% of the time (10 out of 10 tries) on the same Windows 7 Enterprise machine as above. System specs:

Windows 7 Enterprise, Service Pack 1
Processor: Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz  2.50GHz
Installed memory (RAM): 6.00 GB (5.83 GB usable)
System type: 64-bit Operating System

Let me know what other info might be useful for diagnosing.

**Comment by henrykironde** [comment]
@ahhurlbert could you send the error messages if any.

**Comment by ahhurlbert** [comment]
No error messages. When trying to run it, a window opens and I can see it is loading all of the retriever scripts, then both windows just close.

**Comment by henrykironde** [comment]
Hi @ahhurlbert, which installation files did you use, 
Could you also try to run the retriever using command line, so that we could figure out what is happening at your end.

**Comment by ethanwhite** [comment]
Hey Allen - thanks again for reporting. I thought I'd take a second and introduce you to Henry, who is the brand new software engineer in my group. He's in the process of learning about Retriever and starting to work on maintaining it. When he asks which installation files you used he wants to know if you used the Windows installer or installed it from the source files yourself.

**Comment by ahhurlbert** [comment]
Running it from the Command Window gives:

Traceback (most recent call last):
  File "__main__.py", line 127, in <module>
  File "__main__.py", line 31, in main
  File "retriever\lib\repository.pyo", line 74, in check_for_updates
  File "retriever\lib\repository.pyo", line 163, in run
  File "retriever\lib\repository.pyo", line 26, in download_from_repository
  File "urllib.pyo", line 94, in urlretrieve
  File "urllib.pyo", line 240, in retrieve
  File "urllib.pyo", line 208, in open
  File "urllib.pyo", line 451, in open_https
  File "urllib.pyo", line 372, in http_error
  File "urllib.pyo", line 665, in http_error_301
  File "urllib.pyo", line 635, in http_error_302
  File "urllib.pyo", line 661, in redirect_internal
  File "urllib.pyo", line 208, in open
  File "urllib.pyo", line 444, in open_https
IOError: ('http protocol error', 0, 'got a bad status line', None)

**Comment by ethanwhite** [comment]
This looks like a problem with the retriever not being able to download the scripts from Github. This definitely isn't a general problem, so it could be either something about the firewall settings or the network.

We've run into related issues before with proxies:
https://github.com/weecology/retriever/issues/268

**Comment by ethanwhite** [comment]
Closing for the moment since this appears to be an isolated incident. If anyone can replicate this error please feel free to reopen.
