### ISSUE TITLE
Potential issues with skipping (primary key) fields

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#331]
It is possible to skip fields when importing. In the text scripts this is done using `skip` as the type. In at least one case (PortalMammals; csv) this seems to have caused an issue where the field itself was not created, but the heading was (see #327, #330). This may also be related to #246, where auto-numbered primary key fields were not starting at the right number.

**Comment by henrykironde** [comment]
I can't get the exact problem set scenario. 
Since Auto-numbered is a field we create, a case in which we skip it is a little abstract to me.

**Comment by ethanwhite** [comment]
OK, let's go ahead and close this for now. There are also no current uses of `skip` in any of the scripts.
