### ISSUE TITLE
Home range size database

### ISSUE THREAD

**Issue by embaldridge** [weecology/retriever#332]
Dryad Description:
Database of mean species masses and corresponding empirically measured home range sizes for 569 vertebrate species from across the globe, including birds, mammals, reptiles, and fishes.

When using this data, please cite the original publication:
Tamburello N, Côté IM, Dulvy NK (2015) Energy and the scaling of animal space use. The American Naturalist 186(2): 196-211. http://dx.doi.org/10.1086/682070

Additionally, please cite the Dryad data package:
Tamburello N, Côté IM, Dulvy NK(2015) Data from: Energy and the scaling of animal space use. Dryad Digital Repository. http://dx.doi.org/10.5061/dryad.q5j65 http://datadryad.org/resource/doi:10.5061/dryad.q5j65/1

**Comment by ethanwhite** [comment]
Closed by #333.
