### ISSUE TITLE
Portal data: other data tables?

### ISSUE THREAD

**Issue by davharris** [weecology/retriever#345]
Right now, it looks like the portal script grabs the rodent abundances, plot information, and species information, but not the other data tables (including precipitation, which is what I was looking to use).

**Comment by ethanwhite** [comment]
Yeah, the other tables just never got added to the script. Adding the precip tables should just a couple of lines of text. Want to give it a go?

The other tables should all be doable in the plain text script as well, it just requires handling the crosstab data.

Instructions are available here for modifying the script if you want to give it a try:
http://www.ecodataretriever.org/scripting.html

**Comment by henrykironde** [comment]
New version of this data coming soon, so no need to update the current version.
