### ISSUE TITLE
Retriever does not recognize the command Line arguments.

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#348]
An example:

In case you run the command "retriever.exe install mysql  giving the options as illustrated by the help command below. 
[--user [USER]] [--password]
                                   [--host [HOST]] [--port [PORT]]
                                   [--database_name [DATABASE_NAME]]
                                   [--table_name [TABLE_NAME]]
                                   [dataset]
An error is created. 

For example 

C:\ retriever.exe install mysql
--user myuser --password passw --host localhost --port 8888  --database_name
 testdb MoM2003

**Comment by ethanwhite** [comment]
Fixed by a combination of b75b2f3b6be19c8c631465720d3a31b84a206dd5 and 8629ef7f97aeb68c081882149c7c1d472f955d4f
