### ISSUE TITLE
Unit tests failing on windows due to os.environ["HOME"]

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#352]
It appears that `os.environ["HOME"]` no longer works on Windows which is causing test errors. The below suggestion provides a supposedly OS agnostic approach to the problem:

http://stackoverflow.com/questions/14742064/python-os-environhome-works-on-idle-but-not-in-a-script

**Comment by henrykironde** [comment]
fixed in da7fc51d6735d7113edeab2e25075039b4dbe62b
