### ISSUE TITLE
Add Amniote Life History DB

### ISSUE THREAD

**Issue by embaldridge** [weecology/retriever#355]
Due to cognitive dysfunction, I cannot currently get this script from the Gargantobase repository to the Retriever repository.  In theory, I successfully updated the script with the appropriate URL and final variable names, and it should work, so long as some one can get it moved from there to here.

https://github.com/weecology/gargantobase/blob/master/AmnioteLH.script

**Comment by ethanwhite** [comment]
Thanks @embaldridge! I just opened a PR with this script and using some git-foo credited you for the commit.

**Comment by ethanwhite** [comment]
Done in #356.
