### ISSUE TITLE
Feature request: table stats to doublecheck successful import

### ISSUE THREAD

**Issue by fluby** [weecology/retriever#36]
I'm wondering if there would be a way to generate the number of rows per table that should show up in your completed database - perhaps to accompany the super-sweet 'download complete' graphic? I am just looking for a quick way to reassure myself that I have everything I should - rather than having to check against all the raw data files.Thanks!

**Comment by ethanwhite** [comment]
Closing since this clearly hasn't risen to the top of the list. We do have some plans for implementing checksums as mentioned above.
