### ISSUE TITLE
If expected tag not found fall back to master for scripts

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#388]
If the retriever expects a tag for downloading scripts (i.e., as part of a release) it should fall back to master if that tag doesn't exist.

**Comment by henrykironde** [comment]
@ethanwhite could you explain this case a little more?

**Comment by ethanwhite** [comment]
This is part of the larger discussion of how we handle updating scripts (#318). Right now, for a release, the scripts are downloaded from the tag of the same version number. This has occasionally resulted in an issue if the tag didn't precisely match the release somehow. This shouldn't happen, but I think it did with `v1.6` vs. `v1.6.0` or something like that.

Instead of (or at least before) fixing this I think we need to sort out how we're going to handle distributing and updating scripts in 2.0+.

**Comment by henrykironde** [comment]
That is correct, we can have some time this week or next to discus this. Let me first close all the bugs we have so far :)

**Comment by ethanwhite** [comment]
Sounds good. In fact let's go ahead and close this since it will almost certainly be superseded by the decisions we make there. I'll close it and then mention this in the other issue.
