### ISSUE TITLE
Mac: signed binaries

### ISSUE THREAD

**Issue by davharris** [weecology/retriever#390]
Copied from Slack:

dave.harris When I try to double-click the Retriever icon on my mac, I get a warning about the program having been compiled by an “unidentified developer”.  I know how to bypass this, but most users won’t (and they won’t be able to open the GUI).  Apple describes how to sign the code to avoid this error on this page: https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/DistributingApplicationsOutside/DistributingApplicationsOutside.html

**Comment by ethanwhite** [comment]
Replaced by #1028
