### ISSUE TITLE
wiki: Mac Gatekeeper instructions

### ISSUE THREAD

**Issue by davharris** [weecology/retriever#394]
Currently, [the Wiki page](https://github.com/weecology/retriever/wiki/Mac-OSX-Build) with instructions for building for OS X contains these instructions:

> If running OS X 10.8+ go to System Preferences -> Security & Privacy -> General and select Allow apps downloaded from Anywhere. This is necessary because GateKeeper will try to prevent this installation. You can return this setting to its previous state following the installation.

Could someone clarify the purpose of these instructions? Is it to prevent gatekeeper from complaining about dependencies? I don't think gatekeeper would complain about something that the user compiled for themselves, but that seems to be what the instructions are implying.

If it is necessary to bypass Gatekeeper, then we should probably recommend a different workaround: one can always open unsigned apps by right-clicking them and selecting "open" from the dropdown menu.  This process is less likely to end up with Gatekeeper turned off altogether at the end of the installation.

**Comment by ethanwhite** [comment]
The `wxpython` installer for OS X isn't signed, which is the reason for this instruction. I can't remember whether I'd tried it the other way and it didn't work for some reason or if I just didn't know enough about Mac's to do it the other way. If you can confirm that getting `wxpython` installed via the installer from the website (we need 3.0, not 2.8, which is what gets installed via `pip`) works the other way then you're welcome to change the instructions.

**Comment by davharris** [comment]
On my machine, I get the following warning, but only when Gatekeeper is inactive:

>“wxPython3.0-osx-cocoa-py2.7.pkg” is damaged and can’t be opened. You should eject the disk image.

That isn't [a typical Gatekeeper warning](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/osx/macstore_dialog.png).  Apple says it means someone tampered with the binary after it was compiled. 

![image](https://cloud.githubusercontent.com/assets/843017/12835642/031bcd7c-cb80-11e5-82fe-0ba9be762fe5.png)

**Comment by ethanwhite** [comment]
From the wxpython website:

![screenshot from 2016-02-04 20 45 47](https://cloud.githubusercontent.com/assets/744427/12835683/5434a18e-cb80-11e5-9836-5c7167c35212.png)

which is why I solved it this way.

This is the only way I've found to successfully build a distributable using `wxpython` on OS X.

**Comment by ethanwhite** [comment]
Any more thoughts on this @davharris? If there's something wrong on our end we'd love to fix it, but at the moment this looks like an issue with `wxpython` that is beyond our control.

**Comment by davharris** [comment]
Yeah, I don’t see a way around it unless we wanted to compile `wxpython` ourselves---which I'm quite sure we don't.  I'll close the issue.

I’m still creeped out by it, though.  It’s one thing for a developer not to have an Apple account, but who (other than three-letter agencies) goes around modifying software after it's been compiled but before it's distributed?
