### ISSUE TITLE
Use status bar for script download progress

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#397]
Instead of printing out the name of each script being downloaded, use a status bar to indicate the progress of downloading all scripts.

**Comment by ghoshbishakh** [comment]
@ethanwhite I hope this is kind of what you meant? 
![screenshot from 2016-03-08 23-05-47](https://cloud.githubusercontent.com/assets/5156787/13610199/89b2f4b6-e582-11e5-8ab9-6c0175695433.png)
