### ISSUE TITLE
USDA plants - use Advanced Search Download option?

### ISSUE THREAD

**Issue by fluby** [weecology/retriever#41]
The Advanced Search produces a more usable format to the data, because you can opt to separate out the authority info from the scientific name, and it generates more information broken up into more fields, in general. The current state of the Retriever version has all variety and authority information included in the scientific_name which doesn't allow for easy joins with other data. Thanks!

**Comment by dlebauer** [comment]
See also new API by @sckott at https://plantsdb.xyz  code at https://github.com/sckott/usdaplantsapi

**Comment by ethanwhite** [comment]
Never heard back so closing this for now.
