### ISSUE TITLE
Gentry site CEDRAL has data entry error

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#415]
On line 130 of the CEDRAL data there is an extra `'` in the `voucher1` column. This is related to a parsing error in the raw Excel file that makes all following columns off by one, which results in the `Counts` column containing non-integer values (because the first size ends up in the counts column) and the stems table will be missing a single, 2.5, value.

**Comment by henrykironde** [comment]
@ethanwhite does this still hold? #416

**Comment by ethanwhite** [comment]
Yes. It happens for the following line:

```
count_id,line,species_id,site_code...
18681,4,4224,CEDRAL...
```

I'll submit a PR to fix this shortly.
