### ISSUE TITLE
Check MySQL and Postgres credential files

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#421]
In addition to allowing users to directly provide their MySQL and PostgreSQL credentials, it should also be possible for them to store these credentials in the usual places.

We should check information given by the user to the retriever first, and then fall back on the configuration files for usernames and passwords if they are not provided.

For PostgreSQL this is `~/.pgpass` with the format:

```
hostname:port:database:username:password 
```

See: https://wiki.postgresql.org/wiki/Pgpass. `*`s can be used in place of any of the `:` separated values.

For MySQL this is `~/.my.cnf` with the format:

```
[client]
user = root
password = yourpassword
```

See: https://dev.mysql.com/doc/refman/5.5/en/option-files.html. `.my.cnf` can contain a lot of additional configuration information so we'll need to look explicitly for `user =` and `password =`.

**Comment by jainamritanshu** [comment]
@ethanwhite @henrykironde I would like to work on this issue if it is still open

**Comment by henrykironde** [comment]
Go for it, I  will PR you a branch that i was working on, you can start from there

**Comment by henrykironde** [comment]
@jainamritanshu, the system with the branch is not with me but in case you need any clarification let me know

**Comment by jainamritanshu** [comment]
Sure I will start working on the issue right away
