### ISSUE TITLE
Rebrand as Data Retriever

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#432]
Nothing we do is specifically limited to ecological data. With the 2.0 release we should rebrand to Data Retriever. Doing so would benefit from getting some non-ecology folks involved in developing scripts for non-ecology datasets.

**Comment by raj-maurya** [comment]
@ethanwhite  
Re-branding to "Data Retriever" would be a good idea for 2.0 release, surely it would attract others to contribute in.

**Comment by ethanwhite** [comment]
Just adding a note hear about a possible tag line:

> A package manager for other peoples data

**Comment by ethanwhite** [comment]
Finished (hopefully) in e14fd39d05bd1c80be8b1100208aa15593b3c560.
