### ISSUE TITLE
retriever update gives error when a http proxy is set in the environment variables

### ISSUE THREAD

**Issue by ghoshbishakh** [weecology/retriever#438]
`retriever===1.9.0-de', 'console_scripts', 'retriever')()
  File "/usr/lib/python2.7/site-packages/retriever-1.9.0_de-py2.7.egg/retriever/__main__.py", line 53, in main
    check_for_updates(graphical=False)
  File "/usr/lib/python2.7/site-packages/retriever-1.9.0_de-py2.7.egg/retriever/lib/repository.py", line 79, in check_for_updates
    init.run()
  File "/usr/lib/python2.7/site-packages/retriever-1.9.0_de-py2.7.egg/retriever/lib/repository.py", line 180, in run
    os.path.normpath(os.path.join(SCRIPT_WRITE_PATH, script_name)))
  File "/usr/lib/python2.7/site-packages/retriever-1.9.0_de-py2.7.egg/retriever/lib/repository.py", line 28, in download_from_repository
    urllib.urlretrieve(repo + filepath, newpath, reporthook=reporthook)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 249, in retrieve
    tfp = open(filename, 'wb')
IOError: [Errno 2] No such file or directory: '/home/bishakh/.retriever/scripts/<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">'

However it works fine if no proxy is set. Apparently some wierd file name is being used that causes this exception.
`

**Comment by ghoshbishakh** [comment]
How is the file name dependent on whether proxy is used or not?

**Comment by ghoshbishakh** [comment]
So proxy server is returning some error page when retrieving [https://raw.githubusercontent.com/weecology/retriever/master/version.txt](https://raw.githubusercontent.com/weecology/retriever/master/version.txt)

But it is opening fine with wget and firefox with proxy set.
Some weird behaviour with urllib.urlopen

**Comment by ethanwhite** [comment]
Hi @ghoshbishakh - Thanks for reporting this!

We ran into a similar problem last year (see #277, #278, and associated issues) and thought we'd fixed it, but apparently there's still some sort of issue here.

The first thing to do is figure out whether python is failing to see the proxy, or is seeing it and failing anyway. Can you try running the following code in Python with the proxy set and post the output?

```python
proxies = ["http_proxy","https_proxy","ftp_proxy","HTTP_PROXY","HTTPS_PROXY","FTP_PROXY"]
for proxy in proxies:
    print("Proxy: {}. getenv output: {}.".format(proxy, os.getenv(proxy)))
```

**Comment by ghoshbishakh** [comment]
```
Proxy: http_proxy. getenv output: http://172.16.1.12:3128.
Proxy: https_proxy. getenv output: http://172.16.1.12:3128.
Proxy: ftp_proxy. getenv output: None.
Proxy: HTTP_PROXY. getenv output: None.
Proxy: HTTPS_PROXY. getenv output: None.
Proxy: FTP_PROXY. getenv output: None.

```


So are HTTP_PROXY and HTTPS_PROXY required?

**Comment by ethanwhite** [comment]
No, that output looks fine. The [code on staring on Line 112 of `__init__.py`](https://github.com/weecology/retriever/blob/master/__init__.py#L112) should copy that proxy to all 6 proxy environmental variables when it encounters the first proxy that isn't `None`.

If you run the `set_proxy()` function in Python and then try to download the file directly using `urllib.urlopen` does it work?

**Comment by ghoshbishakh** [comment]
No something is wrong with either urllib or my proxy. It is working with http but not with https
However I can open the file from firefox or download it with wget using the https proxy.
I am trying to figure it out.

**Comment by henrykironde** [comment]
try to install python2.7 again,

Regards

Henry S.

**Comment by ethanwhite** [comment]
Closing this based on inactivity since we can't replicate it. Feel free to reopen if there's new information. Thanks again for reporting.

**Comment by ethanwhite** [comment]
Closing this based on inactivity since we can't replicate it. Feel free to reopen if there's new information. Thanks again for reporting.
