### ISSUE TITLE
Add documentation for making bulk inserts work

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#440]
Many users won't be familiar with how to set up their environments to all bulk inserts in MySQL and Postgres. Providing instructions for how to do this would provide significant improvements in experience when working with large clean datasets.

If we can improve basic performance significantly (see #312, #424) then this may be less important.

**Comment by mshahriarinia** [comment]
After importing FIA to mysql I noticed that the table schemas are correct but primary keys/ foreign keys are not set. is there a way to set these before importing data? Where are the sql create, import statements being generated?

**Comment by ethanwhite** [comment]
The `pk` optional argument for the `Table` class allows you to set primary keys. We don't currently support setting foreign keys.

**Comment by kvnamipara** [comment]
@ethanwhite @henrykironde 
I assume, Bulk insert means addition of file in the database if there is no need of cleaning of file.
What we want to add in documentation about this?

**Comment by ethanwhite** [comment]
@kvnamipara - yes, that's basically right. Several database management systems have bulk insert functionality that allows one to very quickly import large amounts of clean data. These bulk insert approaches are stored in the `insert_data_from_file` functions in the individual engines.

This issue is a documentation task to help users make sure that MySQL and PostgreSQL are properly configured to allow bulk inserting. My recollection is that we created this issue because the default installs of MySQL and I believe Postgres on some operating systems didn't actually allow these bulk insert commands to be executed without changing the database configuration.

**Comment by henrykironde** [comment]
Bulk insert is covered and is auto prioritized. Retriever will automatically try to bulk insert and falls back to normal insert
