### ISSUE TITLE
Removing the GUI

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#441]
As we start preparing to move to 2.0 it's time to consider removing the GUI.

In 2010 when we started this @bendmorris and I both felt it was pretty important, because many scientists were still doing a lot of data related work by hand in graphical environments. In 2016, thanks to cultural changes driven by increased amounts of data and interest in reproducibility, there has been a major move towards most data analysis being done in scripts in R, Python, Julia, etc.

Maintaining the GUI, and in particular our ability to distribute it across operating systems, has taken up a lot of time, certainly well into the 100s of development hours. Even after solving all the major challenges, issues still pop up with OS upgrades. At this point in time my opinion is that most people who will benefit from the kinds of data package management that we do will be doing scripted data analysis and will therefore benefit more from having this time spent on improving core functionality and maintaining wrappers for other languages.

I'm opening this issue for discussion prior to @henrykironde and I making any final decisions.

**Comment by goelakash** [comment]
I think the only thing that the GUI does good is categorizing data, which is a quick and easy way to _find_ datasets.

**Comment by ethanwhite** [comment]
That's a good point @goelakash. It would be good for us to add that functionality to the `retriever ls` command. On it's own `retriever ls` already shows the names of the groups, but it would be good to be able to use it on just a particular group or combination of groups, e.g.,

```
retriever ls animals
retriever ls animals and timeseries
```

**Comment by davharris** [comment]
It should also be reasonably straightforward to make a web page for viewing/filtering the data sets, I think.

**Comment by Deborah-Digges** [comment]
+1 to removing the GUI and adding a web interface.

**Comment by goelakash** [comment]
What's the advantage of a web page over a desktop client?

**Comment by davharris** [comment]
If all the web site does is categorize the data, it wouldn't need a python interpreter, etc. It would also be much more portable than the current GUI.

**Comment by ethanwhite** [comment]
Thanks for the feedback everyone.

This is now officially planned. I'm not sure if @henrykironde is working on this already, but it should be a fairly straightforward, if rather extensive, change. I test ran this a while ago and it basically came down to removing the `app` directory and cleaning up any references to it. This will include cleaning up the docs as well as the code.

#497 should go in before this, but after that I don't see any need to wait further. If @henrykironde isn't working on it and someone else wants to feel free to let us know and we can assign it. @henrykironde if you are working on this already go ahead and assign yourself to the issue.

**Comment by Deborah-Digges** [comment]
If @henrykironde isn't working on it, I'd be happy to take this up.

**Comment by henrykironde** [comment]
@Deborah-Digges, thank you for the efforts. Please go ahead and remove that Gui :tada:

**Comment by Deborah-Digges** [comment]
I'll send in a PR soon with changes including
- [ ] Removing the app folder
- [ ] Removing the docs for the UI
- [ ] Removing relates dependencies
