### ISSUE TITLE
Check for failed data downloads and fail explicitly

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#456]
Data downloads sometimes fail and the resulting error messages are confusing. In particular, when data locations change (e.g., #455), the download 404s, and we end up with a data file that is actually an html 404 page.

We should check for 404s on downloading data and then report an explicit error that the retriever can't find the data on the web and to check the internet connection and then open an issue.

**Comment by henrykironde** [comment]
I am working on it and there is an issue for this #389

**Comment by ethanwhite** [comment]
Ah great. Thanks. I'll close this as a duplicate.
