### ISSUE TITLE
BBS fails

### ISSUE THREAD

**Issue by davharris** [weecology/retriever#458]
This is what I get when I type `retriever install csv BBS` on my mac.  I get similar results if I use postgres instead.  I tried deleting my local retriever data and still get the same result, so I think it might be a new format from USGS, but haven't checked yet.  

```
=> Installing USGS North American Breeding Bird Survey
Inserting rows to ./BBS_species.csv: 749 / 749
Inserting rows to ./BBS_routes.csv: 5627 / 5627
"There is no item named 'weather.csv' in the archive"
Done!

```

**Comment by ethanwhite** [comment]
Thanks. Looks like BBS changed probably changed their file locations/names like they do every time they release new data. I'll take a look and see what's going on.

**Comment by davharris** [comment]
I think they capitalized the W in `Weather.csv` this time.

**Comment by davharris** [comment]
(but not in the .zip file, because that would be too consistent)

Also, thanks for looking into it.

**Comment by ethanwhite** [comment]
Yep, that's the first problem, but fixing it triggers another bug. Looking into that one now.

**Comment by ethanwhite** [comment]
Never mind. Looks like I changed one too many `weather`s to `Weather`s.

Did you want to PR this fix or would you prefer that I take care of it?

**Comment by henrykironde** [comment]
its just the W

**Comment by davharris** [comment]
I can do it.  Thanks both!

**Comment by ethanwhite** [comment]
Thanks for reporting and taking care of the fix! :+1:

**Comment by henrykironde** [comment]
@davharris wondering if  bbs50 is fine?.

**Comment by davharris** [comment]
@henrykironde looks like it's also broken.  I'll confirm that capitalization is the issue and add it to the PR

**Comment by henrykironde** [comment]
yes, Its the same I checked.
