### ISSUE TITLE
Retriever binary not working on 32-bit Windows 7

### ISSUE THREAD

**Issue by ahhurlbert** [weecology/retriever#463]
I had a slightly older version (1.8.0?) working fine on my Windows 7 machine (32-bit), but yesterday installed the latest version.

The installation worked fine but the program won't load. 

From the command line, calling `retriever` gives "cannot execute binary file: Exec format error"

and double-clicking on 'retriever.exe' gives "This version is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher."

But there aren't separate 32-bit and 64-bit versions of Retriever, right?

I restarted my computer, tried re-downloading and re-installing, but got the same result.

**Comment by ethanwhite** [comment]
Thanks for reporting this Allen.

I'm not sure whether or not we'll have a quick fix for this. We'll probably need to set up a 32-bit Windows machine to build the next release on to deal with this.

For the moment I'd recommend installing from source, which given that BBS and FIA just updated, changed their file structures, and broke everything, is probably a good idea anyway. You'll need Python installed (I recommend using https://www.continuum.io/downloads) and then from the shell run:

```
pip install git+https://github.com/weecology/retriever.git
retriever reset all
retriever update
```

Let us know if you have any questions or problems along the way.

**Comment by ethanwhite** [comment]
FYI, we're going to try to do a new release on Monday that will include 32-bit Windows support.

**Comment by goelakash** [comment]
Is this issue resolved @ahhurlbert ?

**Comment by ethanwhite** [comment]
@goelakash - I don't think it is yet because I don't think the planned release ended up happening. We do plan to make a 32-bit build with the next release.

**Comment by ethanwhite** [comment]
I'm going to go ahead and close this since we now have plans in place for supporting 32-bit builds with the next release.
