### ISSUE TITLE
BBS50 dataset incomplete using ecoretriever in R

### ISSUE THREAD

**Issue by ahhurlbert** [weecology/retriever#464]
Maybe this problem will disappear once I get #463 resolved, but I noticed yesterday that loading the BBS50 dataset using ecoretriever in R yielded only 'species' and 'routes' tables, but no 'counts' or other tables.

In contrast, 'BBS' seemed to load fine with all of the requisite tables. For now, I can't replicate this until I get my Retriever install fixed, but presumably someone else can check this quickly.

**Comment by henrykironde** [comment]
@ahhurlbert  we are working our way round to resolve that. give us 3 hours.
we shall have that resolved.

**Comment by henrykironde** [comment]
closing because we have fixed BBS datasets.
