### ISSUE TITLE
Designing (SQLite) multiple-processes writing to the database  of  EcoData Retriever.

### ISSUE THREAD

**Issue by raj-maurya** [weecology/retriever#468]
Hi,

@henrykironde  I have gone through the current database design for the ( SQLite )  EcoData Retriever.
I am currently working on designing and analyzing the database for multiple-processes writing to the database as our current database ( SQLite )  only supports the single user writing at a time.

Please, let me know your thoughts, will this be good idea as of now to start working on implementation for the same.

**Comment by henrykironde** [comment]
@raj-maurya could we have a phone meeting, please set you the time based on your time zone.
we can then discus further the details.

**Comment by raj-maurya** [comment]
@henrykironde 

It would be good, to have the phone meeting to discuss further details. My time zone is
India Time Zone
UTC+05:30

**Comment by henrykironde** [comment]
I sent you an email. but you can call me on hangouts any time before your sleeping time or early in the morning before 10 am (UTC+05:30)

**Comment by raj-maurya** [comment]
Great...! I will do asap.

Thanks
