### ISSUE TITLE
negative latitudes in bbs

### ISSUE THREAD

**Issue by davharris** [weecology/retriever#469]
It took me a while to track this down.  I was sure I was going insane at first.

Longitude [was conditionally getting multiplied by -1 in bbs.py](https://github.com/ethanwhite/retriever/blob/fc8c143f95fa690365637fa628bda1fa61d39fc7/scripts/bbs.py#L72), but changes to the data set seem to have caused latitude to get flipped instead.  Now my maps are upside-down  ಠ_ಠ

What's the most sensible fix? Should we just change the index, or should we try to dynamically figure out which column is longitude?

**Comment by henrykironde** [comment]
@davharris do you have the sample old file before the new change in the data.
I could look at it and indentify which index changed

**Comment by ethanwhite** [comment]
Working on this now. Should have a PR shortly.

**Comment by ethanwhite** [comment]
PR in #470. Always nice to see a data provider cleaning up something messy and letting us dump a bunch of custom cleaning code.
