### ISSUE TITLE
Add Gillooly et al 2016 dataset on size, body temp, metabolic rates of vertebrates

### ISSUE THREAD

**Issue by ahhurlbert** [weecology/retriever#486]
http://www.pnas.org/content/113/19/5340.abstract.html?etoc

Data in pdf SI

**Comment by henrykironde** [comment]
Hi @ahhurlbert, thanks for the request. It will be good to have this data supported by the retriever.
Could you please write to the author requesting them to put the data in text or csv format. In that way, retriever will be able to get all that data for you very fast. At the moment retriever does not support pdf

**Comment by ahhurlbert** [comment]
Sure. And where should I tell the authors to send the data file?
Alternatively, it can be copied out of the pdf into a text file without too much effort.

**Comment by henrykironde** [comment]
@ahhurlbert that is nice, however there are rights concerning the distribution of data.  I would suggest coping file and sending it to the author to upload the files somewhere. Usually the authors have these datasets and if you contact them, they can upload them and send me the link. I will include them in the retriever as soon as possible

**Comment by henrykironde** [comment]
for the moment, I will close this and you can reopen a new issue when the links are ready, I will be more than happy to get this data integrated into the retriever

**Comment by mbjones** [comment]
In the US there are rights associated with the distribution of the pdf file, but not the data per se.  In the US, a particular formatting and presentation of data can be copyrighted, but the data themselves can not be.  Plus, these data were published to distribute them to the science community. So, I think it would be completely legal and reasonable to extract the data (e.g., into a .csv file) for the purpose of reuse, then document and upload that to a repository like the [KNB](https://knb.ecoinformatics.org), and give proper attribution to the original authors in the metadata.  Then, the CSV files would be available in a reliable archive and accessible to retriever.

**Comment by henrykironde** [comment]
@mbjones thank you for the clarification. @ahhurlbert once the data is uploaded as .csv or any other form on KNB, please open a new issue as seen on the issue with your comment, [Add vertnet data ](https://github.com/weecology/retriever/issues/357).
