### ISSUE TITLE
Improve provenance tracking 

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#49]
One thing the Retriever doesn't really accomplish is helping the user with tracking when they downloaded the data (in case the source changes) and what version of the Retriever a particular database was built with (in case the Retriever changes). Many DBMSs allow metadata to be included as part of the database and including key provenance information in this metadata would be useful. An alternative would be to create a separate Retriever table that stores this information for all datasets installed using the Retriever (e.g., fields could include Dataset, Table, Date Created, Retriever Version). The advantage of this alternative is that it is probably less DBMS specific. This information could be stored as comments in .csv files.

**Comment by ethanwhite** [comment]
Possible provenance modules to use:
* https://pythonhosted.org/Sumatra/
* https://github.com/recipy/recipy

Discussion of this as part of GSoC applications:
* https://github.com/numfocus/gsoc/issues/2

**Comment by henrykironde** [comment]
Added https://github.com/weecology/retriever/pull/1369
