### ISSUE TITLE
Allow multi-file table specifications in Retriever scripts

### ISSUE THREAD

**Issue by bendmorris** [weecology/retriever#50]
It would be nice to be able to create a single data table out of multiple data files, i.e.:

```
# tables
table: counts, count_*.csv
```

would create table "counts" out of files count_1.csv, count_2.csv, etc.

**Comment by henrykironde** [comment]
We have moved to new specifications and new designs, I think the current design of the specification and that of the tables specifications makes this out dated. Feel free to open a new issue
