### ISSUE TITLE
Install error due to missing `builtins` module

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#522]
From https://github.com/ropensci/ecoretriever/issues/66#issuecomment-225685553

```
$ pip install git+https://github.com/weecology/retriever --upgrade
Collecting git+https://github.com/weecology/retriever
  Cloning https://github.com/weecology/retriever to c:\users\hurlbert\appdata\local\temp\pip-xsdwwn-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\hurlbert\appdata\local\temp\pip-xsdwwn-build\setup.py", line 25, in <module>
        from __init__ import VERSION
      File "__init__.py", line 8, in <module>
        from builtins import str
    ImportError: No module named builtins
```

I'm guessing this means we missed adding `builtins` as a requirement somewhere in the Python 2/3 compatibility work. @goelakash can you take a look at this?

**Comment by goelakash** [comment]
It requires the `future` package to be already installed.
We could add these lines before the import from `__init__`:
```
import pip
pip.main(['install', 'future'])
```

**Comment by ethanwhite** [comment]
I think it probably just needs to get added to `install_requires` in `setup.py` so that `pip` installs it automatically. We should probably also add it to the `includes` list to make sure that it gets added to the installers.

**Comment by goelakash** [comment]
Because I import `VERSION` before the setup function is invoked, that won't work, because `__init__` gets imported before anything is installed.
If we move `VERSION` to a separate file, then it will be ok to add those packages to the required lists.

**Comment by ethanwhite** [comment]
Ah, yes, you're totally right. I've done some looking around trying to find the standard place to store version info and apparently there really isn't one.

I kind of like what @jiffyclub has done in `snakeviz`:
https://github.com/jiffyclub/snakeviz/search?utf8=%E2%9C%93&q=version&type=Code

But since we already have a `version.py` that is doing something else we'd need to go with `_version.py` (which is standard name for a file storing this information (see http://stackoverflow.com/a/7071358/133513).

So, this would move `VERSION` into `setup.py` so we wouldn't need to import `__init__` there. `setup.py` would generate `_version.py` and `__init__` would import `_version.py` to get the version number. If we go this route then we should honor the standard and use `__version__` for the import into `version.py`.

What do you think?

**Comment by goelakash** [comment]
Yes, generating a `__version__.py` module via `setup.py` seems to be a good idea. I will send a PR shortly.

**Comment by ethanwhite** [comment]
#529 should finish closing this issue.
