### ISSUE TITLE
Install errors if installed csv files are in working directory & share names w/raw data

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#532]
For some datasets (at least MCDB) the csv files created by `retriever install csv DATABASE` share the same filenames as the raw data files downloaded from the web. This will be rare, but when it happens it causes errors if the `csv` files are currently installed into the working directory. The general search path checks the working directory early, discovers what looks like the raw data files, and then loads them. If these files differ from the formats described in the script this will cause errors. In the case of MCDB this happens because a `record_id` column gets added to the data, the script is expecting `n` columns but finds `n + 1` instead.

Example to reproduce:

```
retriever reset all
retriever update
retriever install csv MCDB
retriever install csv MCDB
```

If you remove the MCDB files then everything works again:

```
rm MCDB_*
retriever install csv MCDB
```

Original error reported by @henrykironde.

**Comment by ethanwhite** [comment]
I can no longer replicate this error, but I also can't find where we would have fixed it.

@zhangcandrew and/or @goelakash can you see if this error is happening for you on the current master?

**Comment by goelakash** [comment]
Doesn't happen for me.

**Comment by ethanwhite** [comment]
Thanks @goelakash. Much appreciated.

I'm going to go ahead and close this since it doesn't seem to be an issue anymore. If it crops up for anyone else please feel free to reopen and provide details about the system and how the error was triggered.

**Comment by zhangcandrew** [comment]
Just wanted to affirm that it doesn't happen for me either.

**Comment by ethanwhite** [comment]
Thanks @zhangcandrew. Much appreciated.
