### ISSUE TITLE
Dataset install issues with SQL for some databases

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#537]
E.g., Adler2007 installs fine into csv (and other text file engines):

```
ethan@stice:~$ retriever install csv Adler2007
=> Installing Kansas plant quadrats (Ecological Archives 2007)
Downloading species_list.csv...ain.csv: 163400 / 16340000 41
Done!ting rows to ./Adler2007_species.csv: 151 / 151
```

But when install into the SQL engines consistently fails with `invalid literal for int() with base 10: '30,20'`:

```
ethan@stice:~$ retriever install sqlite Adler2007
=> Installing Kansas plant quadrats (Ecological Archives 2007)
Creating table Adler2007_quadrat_inventory...
Creating table Adler2007_monthly_temp...ntory: 41 / 41
Creating table Adler2007_quadrat_info...: 110 / 110
Creating table Adler2007_monthly_ppt...o: 51 / 51
Creating table Adler2007_main...hly_ppt: 110 / 110
invalid literal for int() with base 10: '30,20'
Done!
```
```
ethan@stice:~$ retriever install postgres Adler2007
=> Installing Kansas plant quadrats (Ecological Archives 2007)
Creating database Adler2007...
Couldn't create database (schema "adler2007" already exists
). Trying to continue anyway.
Creating table Adler2007.quadrat_inventory...
Creating table Adler2007.monthly_temp...ntory: 41 / 41
Creating table Adler2007.quadrat_info...: 110 / 110
Creating table Adler2007.monthly_ppt...o: 51 / 51
Creating table Adler2007.main...hly_ppt: 110 / 110
invalid literal for int() with base 10: '30,20'
Done!
```
```
ethan@stice:~$ retriever install mysql Adler2007 -u root -p bats1e
=> Installing Kansas plant quadrats (Ecological Archives 2007)
Creating database Adler2007...
Creating table Adler2007.quadrat_inventory...
Creating table Adler2007.monthly_temp...ntory: 41 / 41
Creating table Adler2007.quadrat_info...: 110 / 110
Creating table Adler2007.monthly_ppt...o: 51 / 51
Creating table Adler2007.main...hly_ppt: 110 / 110
invalid literal for int() with base 10: '30,20'
Done!
```

The same issue is also present for `ArticBreedBird`, `BAAD`, and probably others.

**Comment by ethanwhite** [comment]
This is being caused by the addition of a couple of `int()` wraps in `lib/engine` added in 6b52de0ff2f61b04200412c0eb1a7a1415328ea4. Specifically the two sets of

`if len(datatype) > 1 and int(datatype[1]) > 0:`

Given the way `datatype` was being treated here this change made reasonable sense, but there are currently values of `datatype[1]` that aren't integers. For the `Adler2007` `main` table the values of `datatype` at this point in the code are:

```
('char', 9)
('int',)
('char', 26)
('decimal', '30,20')
('decimal', '30,20')
('decimal', '30,20')
```

These are decimal values are indicating values for the left and right side of the decimal point, but they are either not being parsed properly or are valid and therefore we shouldn't be doing a conversion to `int()`.

`'30,20' > 0` evaluates to `True`.

**Comment by ethanwhite** [comment]
Ah  `'30,20' > 0` evaluates to `True` in Python 2 and errors in Python 3 (as does `'30' >0`), hence the addition of the `int()`s.

**Comment by goelakash** [comment]
I think we could remove the ints and make 0 -> "0" to get the old
functionality back.

**Comment by ethanwhite** [comment]
Looks like I should have checked this issue before getting back to work on this this morning :smile:. I just submitted a PR (#539) that actually gets rid of the check entirely because I can't see any reason why that value should be <0 and some fairly heavy testing doesn't show any datasets throwing errors
