### ISSUE TITLE
Add "dataset out of service" functionality

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#562]
## Current situation

Currently if a dataset that we have a script for stops working because of some change on the data providers end (e.g., #513) we have two choices. Keep the script, in which case the user tries to install the dataset and gets an error, or remove the script, in which case code that used to run the retriever for that dataset starts failing in a confusing way by saying "that dataset doesn't exist". Neither of these communicates to the user what has actually happened. The later also makes it harder to go back and fix the broken script later.
## Proposed solution

Add "dataset out of service" functionality. We would add an indicator of some kind to the script that triggers it to not try to install but instead report back to the user something like "This dataset is currently not available. Either the data is no longer openly available or the way in which it is provided has changed so that the Retriever doesn't know how to work with it".

We may also want to have the retriever return an error code (1 instead of 0) if this happens, but I'm not sure about the general thought on that for this sort of situation.

**Comment by ethanwhite** [comment]
As part of adding this we should apply it to NPN and eBird, both of which are broken at the moment due to these kinds of changes.

**Comment by henrykironde** [comment]
"This dataset is currently not available. Either the data is no longer openly available or the way in which it is provided has changed so that the Retriever doesn't know how to work with it". is perfect.

**Comment by ethanwhite** [comment]
Glad you liked it. In additional to a generic message, it might be useful to allow a custom message for a dataset. Then we could do things like.

"The eBird dataset is now longer available because it has been removed from DataOne"

or

"The AvianBodyMass dataset is only available via a CD that comes with the CRC Handbook of Avian Body Mass. If you wish to use this data you need to: 1. Obtain the CD; 2. Put the datafiles in `.retriever/raw_data/AvianBodyMass/`; and 3. Change line XX of the avianbodymass.py script to `unavailable = False`.

**Comment by ethanwhite** [comment]
As part of this change we should also remove the listing of these datasets from `retriever ls`.

**Comment by jainamritanshu** [comment]
I would like to work on this if its still open :smile:

**Comment by henrykironde** [comment]
Go for it

**Comment by ethanwhite** [comment]
I think the way we're failing when a dataset doesn't exist is sufficient for the time being.
