### ISSUE TITLE
Include log messages when testing all scripts for the dataset in the IGNORE list

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#566]
Currently `try_install_all.py` https://github.com/weecology/retriever/blob/master/try_install_all.py does not log any information for the datasets in the IGNORE list when testing. The goal of this script is to test ALL the retriever dataset and provide detailed information in case there is any error. The end goal of this issue is to be able to run `try_install_all.py`  with out ignoring any dataset. Reference #562

**Example:** Information that could be given incases where  data should not be downloaded are;

`The eBird dataset is now longer available because it has been removed from DataOne`
or

```
The AvianBodyMass dataset is only available via a CD that comes with the CRC Handbook of Avian Body Mass. If you wish to use this data you need to: 
1. Obtain the CD; 
2. Put the datafiles in .retriever/raw_data/AvianBodyMass/; 
3. Change line XX of the avianbodymass.py script to unavailable = False.
```

**Comment by goelakash** [comment]
I think we should drop AvianBodySize, as its no longer available freely, unless it is a very important dataset from an ecological/research POV.

**Comment by ethanwhite** [comment]
> I think we should drop AvianBodySize

Agreed. It is a cool dataset, but I don't think most folks will use it because of the difficulty and it goes against our focus of supporting the use of publicly available data.

Since it has existed before I think it should be handled as part #562 rather than silently removed.

**Comment by ethanwhite** [comment]
@goelakash - thanks for offering some very useful perspective on this!

**Comment by kapilkd13** [comment]
Hi, Do we want to entirely remove the IGNORELIST,or just keep it there but still test its dataset. Also how do we know which dataset is not to be downloaded and should rather show a message.
Thanks.

**Comment by henrykironde** [comment]
We have covered this.

**Comment by kapilkd13** [comment]
Great. :smiley:
