### ISSUE TITLE
Invasive species database

### ISSUE THREAD

**Issue by fluby** [weecology/retriever#57]
http://www.issg.org/database/welcome/

and/or

http://www.invasive.org

Thanks!
Kate

**Comment by ethanwhite** [comment]
@fluby - do you know if any of these databases provide access to the raw data files. At a quick clance I couldn't find access to the raw data for either of these.

**Comment by ethanwhite** [comment]
Closing due to lack to access to a direct download. Would love to add something like this. If someone finds meaningfully open data for this please reopen.
