### ISSUE TITLE
urllib.request.urlretrieve fails to download Gentry data

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#571]
[Gentry site data](https://github.com/weecology/retriever/blob/master/scripts/gentry.py#L28) is failing and it is because of `urllib.request.urlretrieve` in [Engine](https://github.com/weecology/retriever/blob/master/lib/engine.py) `def download_file(self, url, filename):` 

I have attached a small script.
```
url = 'http://www.ecologicaldata.org/sites/default/files/gentry_sites_data.txt'

urllib.request.urlretrieve(url, "fileout")
```
`AttributeError: '_fileobject' object has no attribute 'readinto'`

ref: #502

**Comment by ethanwhite** [comment]
This is the same as the missing table part of #528. We had created this table from a pdf and posted it to the Ecological Data Wiki. When we upgraded the wiki a month or two ago we didn't move this table. I'll try to put in a PR to fix this soon.

**Comment by ethanwhite** [comment]
PR is in: #573.
