### ISSUE TITLE
GWDD failing to install due to non-latin-1 character

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#577]
```
ethan@stice:~$ retriever install --debug csv GWDD
=> Installing Zanne et al. Global wood density database.
'latin-1' codec can't encode character u'\u2563' in position 157: ordinal not in range(256)
Traceback (most recent call last):
  File "/home/ethan/anaconda/bin/retriever", line 9, in <module>
    load_entry_point('retriever===1.9.0-de', 'console_scripts', 'retriever')()
  File "/home/ethan/anaconda/lib/python2.7/site-packages/retriever/__main__.py", line 135, in main
    dataset.download(engine, debug=debug)
  File "/home/ethan/.retriever/scripts/gwdd.py", line 99, in download
    this_line[label] = format_value(row[num])
  File "/home/ethan/.retriever/scripts/gwdd.py", line 96, in format_value
    s = Excel.cell_value(s)
  File "/home/ethan/anaconda/lib/python2.7/site-packages/retriever/lib/excel.py", line 26, in cell_value
    return (cell.value).encode().strip()
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2563' in position 157: ordinal not in range(256)

```

This dataset worked fine before the Python 3 upgrade even with the default `latin-1` encoding, so I suspect some change in the encoding decoding behavior.

@goelakash - is this something you have some time to look into?

**Comment by ethanwhite** [comment]
Just updated the original issue with the full `--debug` trace.

**Comment by goelakash** [comment]
@ethanwhite We could add an `error=ignore` for this case, as this is not a general issue (Most files decode well with `latin-1. What do you think?

**Comment by ethanwhite** [comment]
I'd rather not drop characters if at all possible. Would it be possible to change the encoding from the default on a per dataset level? So, by default we use `latin-1`, but if we need something else we set an `encoding` variable in the script such that encoding gets set like `encoding = 'utf8'` to whatever encoding is best.
