### ISSUE TITLE
Add XML engine

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#58]
I think ecology is finally getting to the point of being read to move into an XML world. It would be nice to be ready.

**Comment by akshayah3** [comment]
I think this would be very similar to the `JSON` engine. I have made a [Gist] (https://gist.github.com/akshayah3/f23d85dc726b85b0ee1c) with some changes to the json engine code. I have used `<params>` to mark the beginning of the xml file. And i have used the `xmlrpclib` module from the standard library to encode a xml file which is similar to `json.dump()`. Before I proceed any further, would appreciate a review.

**Comment by ethanwhite** [comment]
Thanks for looking into this @akshayah3! I don't know anything about the details of `xmlrpclib`, but it looks like a good translation from the JSON engine on a first read through. Have you tested it out? Can `xmlrpclib` read in the resulting XML?

I'd recommend going ahead and submitting this as a WIP pull request and we can continue the discussion there.

Ultimately that similarity between this, the JSON engine and the csv engine means that we should factor out the common functions behavior into a shared parent class for text based file formats, but that doesn't need to happen now.
