### ISSUE TITLE
Refactor `lib.engine.add_to_table`

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#584]
This is a core function that has gotten long and difficult to read. We should split out some of it's components into smaller functions and consider handing off some of the handling of handling of csv complexities to the `csv` module.

**Comment by ethanwhite** [comment]
This function is definitely a lot better than it was 6 months ago. @henrykironde - do you think we should leave this open for further improvements or call it good for now?

**Comment by henrykironde** [comment]
I am closing this. It is good for now
