### ISSUE TITLE
Remove `pyyaml` dependency.

### ISSUE THREAD

**Issue by goelakash** [weecology/retriever#595]
Currently affects `scripts-to-json` branch.

**Comment by henrykironde** [comment]
Could you give a few lines of code that I could run to see that problem we are having clearly. Pyyaml doesn't seem to be maintained and it is hard to install on Mac. We should indeed remove it. I think there is a way to tell json to return either Unicode, which looks like the default or to use the defined encoding to get the string equivalent.

**Comment by goelakash** [comment]
@henrykironde Currently there seems to be no way to return non-unicode strings using `json`. I am running into issues with Python 3 while implementing this solution - stackoverflow.com/questions/956867/how-to-get-string-objects-instead-of-aunicode-ones-from-json-in-python

**Comment by henrykironde** [comment]
Looking at [the solution](http://stackoverflow.com/questions/956867/how-to-get-string-objects-instead-of-unicode-ones-from-json-in-python)

could this be one solution to removing the dependency

```
import json
data = """{"name": "Masses of Mammals", "shortname": "MoM2003", "description": "A data set of compiled"}"""
script_contents = json.dumps(json.loads(data))

new_script = open('json_file.py', 'w')
new_script.write("import os\n")
new_script.write("os.getcwd()\n")
new_script.write(script_contents)
new_script.close()
```

**Comment by henrykironde** [comment]
@goelakash  another thing I tried

import json
original_list = ['a', 'b']
json_list = json.dumps(original_list)
json_string = json.dumps(json_list, ensure_ascii=False)
script_contents=json.loads(json_string)
print  json_list
new_script = open('json_file.py', 'w')
new_script.write("import os\n")
new_script.write("os.getcwd()\n")
new_script.write(script_contents)
new_script.close()

**Comment by henrykironde** [comment]
@goelakash in edit_json we still have yaml https://github.com/weecology/retriever/blob/data-package/lib/datapackage.py#L376

when we are trying to limit editing of scripts to only json files  in the try block, it looks like you are trying to open a file but passing the script name 
`retriever edit_json MammalLH` 

```
    try:
        contents = yaml.load(
            open(os.path.join(HOME_DIR, 'scripts', json_file), 'r'))
    except FileNotFoundError:
        print("Script not found.")
        return
```

I am assuming this should have been something like what you have in line 384-385 where you add a postfix `.json`

**Comment by goelakash** [comment]
@henrykironde The `yaml` dependency is removed, but now all the strings in python scripts have `u'` prepended to them.

**Comment by goelakash** [comment]
Currently resolved.
