### ISSUE TITLE
Add National Lakes Assessment Data

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#60]
This looks like an awesome and somewhat cumbersome dataset. Just the sort of stuff the Retriever is perfect for:
http://www.epa.gov/owow/LAKES/lakessurvey/web_data.html

**Comment by andrewdolman** [comment]
I'm about to start getting this into R for my own use. Was there ever any progress made here?

**Comment by ethanwhite** [comment]
No, we never got around to looking at it. I'd be happy to guide you through the process of writing a retriever script for this if you'd like to give it a go.

**Comment by andrewdolman** [comment]
Dear Ethan,

Thank you for the reply.

I've read through http://www.ecodataretriever.org/scripting.html and it
seems easy enough. I already have my own (non ecodataretriever) script that
I used to pull all the data tables. And I got some way to processing them,
but it might be worth it to restart and use retriever. I planned to have
all the data organised in an R package for my own use, but worried about
the implications of sharing this, I haven't managed to find any license
information about this data set, but maybe buried in one of the pdfs. I
guess retriever bypasses this problem of redistribution by having each user
download the data for themselves.

The data are fairly cleanly organised already, but each .csv has an
associated .txt file with additional information about each column of the
corresponding .csv. In my prior solution I have (for now) made a dataframe
from each .csv, and attached the info from the corresponding .txt as
attributes. Is there a standard retriever solution for this type of
structure?

Andrew.


andydolman@gmail.com

**Comment by ethanwhite** [comment]
>  I planned to have
> all the data organised in an R package for my own use, but worried about
> the implications of sharing this, I haven't managed to find any license
> information about this data set, but maybe buried in one of the pdfs. I
> guess retriever bypasses this problem of redistribution by having each user
> download the data for themselves.

Yes, without a clear license allow redistribution I think it's dangerous to post other folks' data in things like data packages, and that's what the Retriever is designed to work around since so much ecological data either lacks explicit licenses or explicitly excludes redistribution.

> The data are fairly cleanly organised already, but each .csv has an
> associated .txt file with additional information about each column of the
> corresponding .csv. In my prior solution I have (for now) made a dataframe
> from each .csv, and attached the info from the corresponding .txt as
> attributes. Is there a standard retriever solution for this type of
> structure?

We don't have a built-in system for attaching metadata in this way. The easiest way to attached metadata would probably be by creating a separate metadata table. This approach fairly standard in the database management system world and would generalize across platforms. A quick glance at what I think is one of the .txt files you mentioned suggests that it's already in tabular form and so would be easy to add this way.

**Comment by shreyneil** [comment]
@ethanwhite  sir, is there any direct link to download this dataset?

**Comment by ethanwhite** [comment]
@shreyneil - interesting. Looks like it was removed from the EPA website. Fortunately it's on the archive:

https://archive.epa.gov/water/archive/web/html/nla_data.html

**Comment by ethanwhite** [comment]
Actually it looks like the data itself is now completely missing, even from the archive. I'll look around a bit more.

**Comment by ethanwhite** [comment]
OK, it looks like there's still a copy in a snapshot (which I'm now backing up to local resources in case this disappears as well):

https://19january2017snapshot.epa.gov/national-aquatic-resource-surveys/data-national-aquatic-resource-surveys_.html

For 2007 we can get a full zip of all of the files:

https://19january2017snapshot.epa.gov/sites/production/files/2013-09/nla2007_alldata.zip

For 2012 it looks like we'll need to get them individually.

In general I'd love to have everything on this page packaged into packages based on shared names in the "Survey" column of the table on the website.

**Comment by shreyneil** [comment]
So do you suggest writing two different scripts for 2007 and 2012 as a single archive package is not available for both the years ?

**Comment by ethanwhite** [comment]
If the schema's match then a single package would be great. My impression from a first glance was that they might not line up perfectly.

**Comment by shreyneil** [comment]
okay will look into it and get back.
