### ISSUE TITLE
sphinx-build fails with python 3

### ISSUE THREAD

**Issue by goelakash** [weecology/retriever#600]

**Comment by henrykironde** [comment]
What are the Errors it gives

**Comment by goelakash** [comment]
Seems to be working now. Closing.

**Comment by goelakash** [comment]
This issue is only resolved in the data-package branch. Reopening.

**Comment by henrykironde** [comment]
@goelakash  can you provide a sample of the output

**Comment by henrykironde** [comment]
@goelakash it would be nice to know what was failing.
I noticed some errors where due to outdated `.rst` files and bad doc strings. 
So I tried to rectify that.

**Comment by goelakash** [comment]
The recent datapackage PR closed this issue (https://github.com/weecology/retriever/pull/615)
