### ISSUE TITLE
Retriever does not install using pip

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#617]
Using  python2 retriever fails to get installed. Only tested with Mac, will test on windows and Unix and update (also will test on python3)  

**Note:**  `python setup.py install` works fine for both systems on py2 and py3

To get this error, do a manual clean up first by removing the `dist`, `build` and `retriever.egg-info` in the retriever directory
If retriever is installed, reset using `retriever reset all`

**uninstall retriever**.
`sudo -H pip uninstall retriever` make sure no retriever files are available
Get the current copy of the retriever  (commit 85b707615) and install using pip

**Install retriever** (This will also uninstall the retriever if it is installed )
`sudo pip install --upgrade ./`

**Comment by ethanwhite** [comment]
Seems to be working on Ubuntu 16.04.

**Comment by goelakash** [comment]
I have been unable to test this, as I couldn't get my hands on a Mac. Does this still exist?

**Comment by henrykironde** [comment]
Thanks @goelakash, I will close this, the issue was due to rights configuration.
