### ISSUE TITLE
refactor checks of platform and python system,

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#646]
Since we are supporting python3, python2 systems running on Windows, IOS(mac) and Linux. we need to refactor some of these checks to one module of location. 

We can overwrite the underlying functions so that retriever has its own implementation of the same.
I which case, if we want to open a file we just use our own function rather than having multiple checks whenever we call open.

Examples of checks include:

In `lib/engine.py`

```
if sys.version_info[0] >= 3:
    from urllib.request import urlretrieve
else:
    from urllib import urlretrieve

```

In `lib/tools.py` 

```
    if os.name == 'nt':
        csv_writer = csv.writer(file_temp, dialect='excel', escapechar='\\', lineterminator='\n')
    else:
        csv_writer = csv.writer(file_temp, dialect='excel', escapechar='\\')
```

In  `lib/compile.py`

```
if sys.version_info[0] < 3:
    from codecs import open
```

**Comment by ethanwhite** [comment]
This is now complete. The primary work is in f657ee00d05c94f0b5a2b3560efdf79d5480b67d.
