### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#654]
I keep planning on doing this and not getting around to it so I'm opening an issue. As usual we can probably just copy @ctb: https://github.com/dib-lab/khmer/blob/master/CODE_OF_CONDUCT.rst

**Comment by henrykironde** [comment]
This is the latest version, http://contributor-covenant.org/version/1/4/  for comparison

**Comment by ethanwhite** [comment]
Let's go with the latest version then.
