### ISSUE TITLE
Error downloading FIA data

### ISSUE THREAD

**Issue by lauraantao** [weecology/retriever#662]
---- I was unable to download the FIA database using the R package ----

I have re-installed both the 'Retriever' and the R package ecoretriever (Windows installer; version v1.8.3).

Apparently everything works fine - get_updates() and datasets() worked, and I was able to download the Gentry and Adler2007 datasets into R.

However, I get this object when running
> newdata <- ecoretriever::fetch('FIA')

![image](https://cloud.githubusercontent.com/assets/12911566/19076774/08c4a7cc-8a42-11e6-95e6-798fea1185fc.png)

And I get this error message with
>download(dataset="FIA")
=> Installing Forest Inventory and Analysis
File is not a zip file
Done!

It creates the same file above as csv ("REF_SPECIES" - attached) and a zip file ("AL_SURVEY") which is empty/corrupted.

I hope this helps.

Thank you
Laura

[REF_SPECIES.txt](https://github.com/weecology/retriever/files/508621/REF_SPECIES.txt)

**Comment by ethanwhite** [comment]
Thanks for reporting this issues @lauraantao! We really appreciate it. We'll get into this and hopefully get a fix implemented quickly. From a first glance it looks like FIA changed the structure of it's data again and so we just need to adjust our code to accommodate those changes.

**Comment by ethanwhite** [comment]
Here's the debug output for `master`, which may be failing in a different place than `1.8.3` since the `FIA_species` looks OK on my system and almost all of the raw data files get downloaded :

```
=> Installing Forest Inventory and Analysis
Creating table FIA_species...
['spcd', 'common_name', 'genus', 'species', 'variety', 'subspecies', 'species_symbol', 'e_spgrpcd', 'w_spgrpcd', 'c_spgrpcd', 'p_spgrpcd', 'major_spgrpcd', 'stocking_spgrpcd', 'forest_type_spgrpcd', 'exists_in_ncrs', 'exists_in_ners', 'exists_in_pnwrs', 'exists_in_rmrs', 'exists_in_srs', 'sitetree', 'sftwd_hrdwd', 'st_exists_in_ncrs', 'st_exists_in_ners', 'st_exists_in_pnwrs', 'st_exists_in_rmrs', 'st_exists_in_srs', 'core', 'east', 'west', 'caribbean', 'pacific', 'woodland', 'manual_start', 'manual_end', 'jenkins_spgrpcd', 'jenkins_total_b1', 'jenkins_total_b2', 'jenkins_stem_wood_ratio_b1', 'jenkins_stem_wood_ratio_b2', 'jenkins_stem_bark_ratio_b1', 'jenkins_stem_bark_ratio_b2', 'jenkins_foliage_ratio_b1', 'jenkins_foliage_ratio_b2', 'jenkins_root_ratio_b1', 'jenkins_root_ratio_b2', 'jenkins_sapling_adjustment', 'wood_spgr_greenvol_drywt', 'wood_spgr_greenvol_drywt_cit', 'bark_spgr_greenvol_drywt', 'bark_spgr_greenvol_drywt_cit', 'mc_pct_green_bark', 'mc_pct_green_bark_cit', 'mc_pct_green_wood', 'mc_pct_green_wood_cit', 'wood_spgr_mc12vol_drywt', 'wood_spgr_mc12vol_drywt_cit', 'bark_vol_pct', 'bark_vol_pct_cit', 'raile_stump_dob_b1', 'raile_stump_dib_b1', 'raile_stump_dib_b2', 'cwd_decay_ratio1', 'cwd_decay_ratio2', 'cwd_decay_ratio3', 'cwd_decay_ratio4', 'cwd_decay_ratio5', 'dwm_carbon_ratio', 'standing_dead_decay_ratio1', 'standing_dead_decay_ratio2', 'standing_dead_decay_ratio3', 'standing_dead_decay_ratio4', 'standing_dead_decay_ratio5', 'created_by', 'created_date', 'created_in_instance', 'modified_by', 'modified_date', 'modified_in_instance']
CREATE TABLE FIA_species (spcd INTEGER, common_name TEXT(42), genus TEXT(16), species TEXT(25), variety TEXT(13), subspecies TEXT(12), species_symbol TEXT(7), e_spgrpcd INTEGER, w_spgrpcd INTEGER, c_spgrpcd INTEGER, p_spgrpcd INTEGER, major_spgrpcd INTEGER, stocking_spgrpcd INTEGER, forest_type_spgrpcd INTEGER, exists_in_ncrs TEXT(1), exists_in_ners TEXT(1), exists_in_pnwrs TEXT(1), exists_in_rmrs TEXT(1), exists_in_srs TEXT(1), sitetree TEXT(1), sftwd_hrdwd TEXT(1), st_exists_in_ncrs TEXT(1), st_exists_in_ners TEXT(1), st_exists_in_pnwrs TEXT(1), st_exists_in_rmrs TEXT(1), st_exists_in_srs TEXT(1), core TEXT(1), east TEXT(1), west TEXT(1), caribbean TEXT(1), pacific TEXT(1), woodland TEXT(1), manual_start REAL, manual_end INTEGER, jenkins_spgrpcd INTEGER, jenkins_total_b1 REAL, jenkins_total_b2 REAL, jenkins_stem_wood_ratio_b1 REAL, jenkins_stem_wood_ratio_b2 REAL, jenkins_stem_bark_ratio_b1 REAL, jenkins_stem_bark_ratio_b2 REAL, jenkins_foliage_ratio_b1 REAL, jenkins_foliage_ratio_b2 REAL, jenkins_root_ratio_b1 REAL, jenkins_root_ratio_b2 REAL, jenkins_sapling_adjustment REAL, wood_spgr_greenvol_drywt REAL, wood_spgr_greenvol_drywt_cit INTEGER, bark_spgr_greenvol_drywt REAL, bark_spgr_greenvol_drywt_cit INTEGER, mc_pct_green_bark REAL, mc_pct_green_bark_cit INTEGER, mc_pct_green_wood REAL, mc_pct_green_wood_cit INTEGER, wood_spgr_mc12vol_drywt REAL, wood_spgr_mc12vol_drywt_cit INTEGER, bark_vol_pct REAL, bark_vol_pct_cit INTEGER, raile_stump_dob_b1 REAL, raile_stump_dib_b1 REAL, raile_stump_dib_b2 REAL, cwd_decay_ratio1 REAL, cwd_decay_ratio2 REAL, cwd_decay_ratio3 REAL, cwd_decay_ratio4 REAL, cwd_decay_ratio5 REAL, dwm_carbon_ratio REAL, standing_dead_decay_ratio1 REAL, standing_dead_decay_ratio2 REAL, standing_dead_decay_ratio3 REAL, standing_dead_decay_ratio4 REAL, standing_dead_decay_ratio5 REAL, created_by INTEGER, created_date TEXT(10), created_in_instance INTEGER, modified_by INTEGER, modified_date TEXT(10), modified_in_instance INTEGER );
INSERT INTO FIA_species (spcd, common_name, genus, species, variety, subspecies, species_symbol, e_spgrpcd, w_spgrpcd, c_spgrpcd, p_spgrpcd, major_spgrpcd, stocking_spgrpcd, forest_type_spgrpcd, exists_in_ncrs, exists_in_ners, exists_in_pnwrs, exists_in_rmrs, exists_in_srs, sitetree, sftwd_hrdwd, st_exists_in_ncrs, st_exists_in_ners, st_exists_in_pnwrs, st_exists_in_rmrs, st_exists_in_srs, core, east, west, caribbean, pacific, woodland, manual_start, manual_end, jenkins_spgrpcd, jenkins_total_b1, jenkins_total_b2, jenkins_stem_wood_ratio_b1, jenkins_stem_wood_ratio_b2, jenkins_stem_bark_ratio_b1, jenkins_stem_bark_ratio_b2, jenkins_foliage_ratio_b1, jenkins_foliage_ratio_b2, jenkins_root_ratio_b1, jenkins_root_ratio_b2, jenkins_sapling_adjustment, wood_spgr_greenvol_drywt, wood_spgr_greenvol_drywt_cit, bark_spgr_greenvol_drywt, bark_spgr_greenvol_drywt_cit, mc_pct_green_bark, mc_pct_green_bark_cit, mc_pct_green_wood, mc_pct_green_wood_cit, wood_spgr_mc12vol_drywt, wood_spgr_mc12vol_drywt_cit, bark_vol_pct, bark_vol_pct_cit, raile_stump_dob_b1, raile_stump_dib_b1, raile_stump_dib_b2, cwd_decay_ratio1, cwd_decay_ratio2, cwd_decay_ratio3, cwd_decay_ratio4, cwd_decay_ratio5, dwm_carbon_ratio, standing_dead_decay_ratio1, standing_dead_decay_ratio2, standing_dead_decay_ratio3, standing_dead_decay_ratio4, standing_dead_decay_ratio5, created_by, created_date, created_in_instance, modified_by, modified_date, modified_in_instance) VALUES  (8313, 'Carolina poplar', 'Populus', 'x canadensis', '', '', 'POCA19', 55, 55, null, null, 3, 37, null, 'X', 'X', 'X', '', 'X', '', 'H', '', '', '', '', '', 'N', 'X', '', '', '', '', 6.0, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2014-05-01', 440, null, '2014-08-13', 440),
...
(6970, 'mamala', 'Dysoxylum', 'samoense', '', '', 'DYSA', 54, 54, null, 54, 3, 37, null, '', '', 'X', '', '', '', 'H', '', '', '', '', '', 'N', '', '', '', 'P', '', 5.0, null, 8, null, null, null, null, null, null, null, null, null, null, null, 0.52521, null, 0.52521, null, null, null, null, null, 0.52521, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2012-10-29', 440, null, '2014-08-13', 440);
Progress: 2591 / 2591 rows inserted into FIA_species:

Traceback (most recent call last):
  File "/home/ethan/anaconda/bin/retriever", line 9, in <module>
    load_entry_point('retriever===2.0.0-de', 'console_scripts', 'retriever')()
  File "/home/ethan/anaconda/lib/python2.7/site-packages/retriever/__main__.py", line 176, in main
    dataset.download(engine, debug=debug)
  File "/home/ethan/.retriever/scripts/fia.py", line 64, in download
    [state + "_" + table + ".csv"])
  File "/home/ethan/anaconda/lib/python2.7/site-packages/retriever/lib/engine.py", line 454, in download_files_from_archive
    archive = zipfile.ZipFile(archivename)
  File "/home/ethan/anaconda/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/home/ethan/anaconda/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file

File is not a zip file
```

**Comment by ethanwhite** [comment]
I tried this on my system at home last night and everything ran smoothly.

**Comment by ethanwhite** [comment]
Hi @lauraantao - The weird contents you see in the `REF_SPECIES` file happened because when the retriever went to download the data it didn't find the correct data and hit a 404 page. This can happen either because FIA has updated their data locations or file names or because the FIA server is having temporary issues.

The current development version of the retriever successfully installed FIA for me last night. I'm not sure why it failed on my office machine yesterday, but I'm guessing that the FIA server was being finicky.

It looks like what you need to do is upgrade to the development version of the retriever. FIA did change it's file structure shortly after the last release and we had to adjust to the new naming conventions. Unfortunately the last release doesn't have the ability to automatically get the updated scripts to you (though the development version does now).

One easy thing you could try first is downloading this file:
https://raw.githubusercontent.com/weecology/retriever/master/scripts/fia.py

And putting it in the `.retriever/scripts/` directory inside your home directory (it's hidden so let me know if you need help finding it.

If that doesn't work, or if you'd rather just install the newest version of the retriever then you'll need to:

1. Uninstall the current version of the retriever. You should be able to do this in the normal way on Windows.
2. Install Python. I recommend the Anaconda distribution: https://www.continuum.io/downloads if you don't have Python installed already. Choose the Python 2.7 version (the big blue button). If it asks you if you want to make it the default Python distribution or append something to your path say yes (assuming you don't have another Python installation in which case you don't need this anyway).
3. Open a command prompt (type `cmd` in the program search box), type

    `pip install git+https://github.com/weecology/retriever`

    and hit enter.
4. The try to install FIA again.

If you'd prefer we can also build you a Windows installer for the development version just like the one you used to install the retriever initially. It might just take a couple of days since my software engineer is traveling at the moment.

Let me know if you have any questions. We're happy to be of additional help as you go forward.

**Comment by lauraantao** [comment]
Thank you very much @ethanwhite 
Unfortunately, I could not make it work (I apologize in advance if these are beginner's mistakes!)

I tried replacing the py file in the .retriever/scripts folder (which was not hidden (?)), but then I get this error message:

newdata <- ecoretriever::fetch('FIA')
Failed to load script: fia (C:/Users/liha/Documents/.retriever/scripts/)

It "modified" both fia.py and fia.pyo in that folder (everything worked fine again for the Gentry data).

I also tried the pip install option following your instructions, but it seems that it does not recognize the command git, although I have Git installed and have used the shell before...
![image](https://cloud.githubusercontent.com/assets/12911566/19123377/534053e8-8b26-11e6-9ecc-aabcdb4f9e1c.png)

I tried installing GitPython also to see if this would help (http://gitpython.readthedocs.io/en/stable/intro.html), but had the same error message in the prompt.

Thank you again
Laura

**Comment by ethanwhite** [comment]
Hey @lauraantao - Terribly sorry about that. Totally my fault. I forgot an important step:

2b. Install Git for Windows: https://git-for-windows.github.io/ During the installation you can use all of the defaults except when asked select `"Use Git from the Windows Command Prompt"`.

Then try running the `pip` command again. If it works run:

```
retriever reset scripts
retriever update
```

and try things again.

Also, I forgot to mention earlier that you probably don't want to try to use `fetch` to bring FIA directly into R. It's ~10 GB so unless you have a lot of RAM you won't be able to load the entire thing. I'd recommend installing it into an SQLite database:

```
> ecoretriever::install('FIA', 'sqlite')
```

And then doing the initial work by interacting with the database through either `dplyr` or `RSQLite`.

**Comment by ethanwhite** [comment]
Hi @lauraantao - just wanted to check in and see if you got this working.

**Comment by lauraantao** [comment]
Hi @ethanwhite I'm sorry for the slow reply (been caught up in other datasets!)

Unfortunately, it did not work :/
I did re-install Git for Windows - I already had it anyway. When running the pip install commad I get this message: 

![image](https://cloud.githubusercontent.com/assets/12911566/19528215/088d0e4c-9623-11e6-937e-4836efbc21cf.png)

Thank you
Laura

**Comment by ethanwhite** [comment]
No problem, I imagine you've got a lot of datasets to juggle.

The current issue you're seeing is that you're computer can't find `pip` even though it's installed. The right way to fix this is to reinstall Anaconda and make sure to chose the option to make it your default Python. The last screen of the installer should look like:

![screenshot 2016-10-19 13 19 45](https://cloud.githubusercontent.com/assets/744427/19529663/eda52b60-95fe-11e6-8e44-a4cec4879aeb.png)

This will fix the new problem. Since you have Git for Windows installed I'd recommend running the commands from inside `Git Bash` instead of `cmd`. You can launch `Git Bash` hitting your Windows button and typing `git`. It should be one of your first few options. To use `git` from `cmd` you have to select the right (non-default) options when running the installer and using `Git Bash` helps avoid that possible issue.

The alternative is that we are in the process of finishing a new release so there should be a new installer available that will avoid all of this in less than a week.

Sorry for all of the difficulty. Hopefully we can get you up and running soon.

**Comment by lauraantao** [comment]
Thank you again @ethanwhite 

Ok, so this time some progress! I re-installed Anaconda/Python and ran the pip install using the git bash, and it worked! It installed retriever and updated the scripts.
But then when running "ecoretriever::install('FIA', 'sqlite')" in R, I get this error message:

Cannot open C:\Users\liha\ANACON~1\Scripts\RETRIE~1-script.py
Warning message:
running command 'retriever install sqlite FIA' had status 2 

I'm guessing this has something to do with the directories in which the different softwares are installed (?) In any case, if you think the new installer will soon be ready, maybe we can wait for next week, and hopefully it will work then.

Thank you again
Laura

**Comment by ethanwhite** [comment]
We're making progress. Yeah!

That's actually an issue that crops up with the R package sometimes and it appears to have returned (https://github.com/ropensci/ecoretriever/issues/73). Try running:

```
retriever install sqlite FIA -f fia.sqlite
```

from the command line and see if that works for you.

**Comment by lauraantao** [comment]
It has finally worked - or at least it seems it has downloaded most of the data (?) I get this message in the end
![image](https://cloud.githubusercontent.com/assets/12911566/19620361/d583978e-9873-11e6-9861-4b9d6ffcbf4c.png)

Now I just have to get working on figuring out the actual data and sqlite.
Thank you again @ethanwhite for walking me through all of the steps!

**Comment by ethanwhite** [comment]
Glad it's working! It looks to me like you got cut off mid download (probably due to a connection issue somewhere between you and FIA. The good news is that all of the data you successfully downloaded is cached locally so it won't have to download it again. I'd try rerunning to same command to get the rest and get it all installed.

**Comment by lauraantao** [comment]
Hi @ethanwhite 
Apparently it is giving the same error message that we started with...
I ran "retriever install sqlite FIA -f fia.sqlite again"

![image](https://cloud.githubusercontent.com/assets/12911566/19643957/003f5b12-99e5-11e6-84d3-3762cd046e62.png)



It did not download any additional files, but the .sqlite is modified.
...

**Comment by ethanwhite** [comment]
Ah, OK, you probably just have the old script cached. Try the following:

```
retriever reset scripts
```
Answer yes

```
retriever update
```

and then try again.

**Comment by lauraantao** [comment]
Thank you @ethanwhite 
I had run the retriever update but not the reset command. However, still got the same error message :/

![image](https://cloud.githubusercontent.com/assets/12911566/19645245/bc599096-99eb-11e6-8aa1-c5c9b9c4ee61.png)

**Comment by ethanwhite** [comment]
Hi @lauraantao - terrible sorry this is taking so long to figure out.

I can't seem to replicate this at the moment, and I'm also seeing a different number of rows in the `FIA_species` table, which is weird:

```
(retrieverpy2) ethan@gandalf:~$ retriever install sqlite FIA -f fia.sqlite
=> Installing Forest Inventory and Analysis
Creating table FIA_species...
Progress: 2605 / 2605 rows inserted into FIA_species: 

Scanning data for table SURVEY...
Creating table FIA_SURVEY...
Progress: 1009 / 1009 rows inserted into FIA_SURVEY: 

Scanning data for table PLOT...
Creating table FIA_PLOT...
Scanning data for table COND...
Creating table FIA_COND...
Scanning data for table SUBPLOT...
Creating table FIA_SUBPLOT...
Scanning data for table SUBP_COND...
Creating table FIA_SUBP_COND...
Scanning data for table TREE...
Creating table FIA_TREE...
Scanning data for table SEEDLING...
Creating table FIA_SEEDLING...
Done!
```

We'll keep working on this, but just wanted to post an update here before hopping on a plane.

**Comment by lauraantao** [comment]
No worries @ethanwhite Thank you for all your patience with this issue

**Comment by ethanwhite** [comment]
@lauraantao - based on the difference in the number of rows in the species table I'm wondering if you have some old data cached as well that is somehow messing things up. Would you mind running:

```
retriever reset all
```

Answering yes, and then trying to install FIA again in case that clears it up?

If that doesn't work then my only remaining guess is that there's a piece of an old version of the software somewhere and we'll have to track it down and get rid of it.

@zhangcandrew - if you get a chance could you try installing FIA (it will take quire a while and use a decent chunk of bandwidth) using the current master built using Python 2, just to check and see if this is happening elsewhere. If you could do it on Windows that would be great. Thanks.

**Comment by lauraantao** [comment]
@ethanwhite It has finally worked!

![image](https://cloud.githubusercontent.com/assets/12911566/19768382/29114b74-9c4f-11e6-805b-2815f44af7fa.png)

It took more than 12 hours to complete those final scanning/creating steps, but it has apparently worked, and the sqlite file has a respectable size now (6.81 GB).

Thank you once again for walking me through all the steps, and I hope this also helped.
Cheers
Laura

**Comment by ethanwhite** [comment]
Awesome! I'm super glad that we got it working for you!

FIA is definitely a big/slow one. Good luck digging into it now that you've gotten it up and running.

**Comment by zhangcandrew** [comment]
Just a small update on downloading the SQLite datasets. 

When I ran 
```
retriever install sqlite FIA -f fia.sqlite 
```

on Ubuntu (16.04) with Python3, the information was retrieved, but the following was also returned:
```
=> Installing Forest Inventory and Analysis
Downloading REF_SPECIES.csv...
Creating table FIA_species...
Progress: 2605 / 2605 rows inserted into FIA_species: 
......
......
Downloading /home/andy/.retriever/raw_data/FIA/PR_SEEDLING.ZIP...
Scanning data for table SURVEY...
a bytes-like object is required, not 'str'
Done!
``` 
I have not tested this on Windows with python3. Using python2, Windows and Ubuntu seem to work fine. Might just be a small translation error between 2 and 3.
