### ISSUE TITLE
Remove unnecessary warning when using `download`

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#667]
When running `retriever download` an unnecessary warning displays

```
ethan@gandalf:~$ retriever download Clark2006
Creating database Clark2006...
Couldn't create database ('NoneType' object has no attribute 'execute').
...
```

The command executes correctly, but this warning isn't really correct (there is no database to create since we're just downloading the raw data files) and could be distracting to users.

**Comment by henrykironde** [comment]
Could not replicate this error.

**Comment by ethanwhite** [comment]
To expand my report: I'm seeing this on Linux (Ubuntu 16.04) on both Python 2 and Python 3.
