### ISSUE TITLE
Python 3  `bytes` vs `str` errors for most `.py` dataset scripts

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#668]
E.g.,

```
ethan@gandalf:~/RetrieverCode (master *)$ retriever install csv Gentry
=> Installing Alwyn H. Gentry Forest Transect Dataset
Progress: 226 / 226 rows inserted into ./Gentry_sites.csv: 

write() argument must be str, not bytes
```

and a slightly different error

```
ethan@gandalf:~/RetrieverCode (master *)$ retriever install csv leda
=> Installing A database on the life history traits of the Northwest European flora
Downloading releasing_height.txt...
a bytes-like object is required, not 'str'
```

Datasets include:
- First error: baad, Gentry, BBS, BBS50, 
- Second error: leda, EA_petraitis2008

These datasets fail on all engines.

**Comment by ethanwhite** [comment]
Errors in leda, EA_petraitis2008, and baad were all fixed by #691.

**Comment by goelakash** [comment]
This issue with `str` has been fixed. I think we should track the new errors that occur with BBS and BBS50 installation.

**Comment by ethanwhite** [comment]
Last I checked Gentry was still having issues as well. I'm happy with closing this and moving on to more specific issues.

**Comment by goelakash** [comment]
Yes, my thoughts exactly.

**Comment by henrykironde** [comment]
Don't close this issue, It's actually bigger than it looks, working on it and will give you the details. Almost there.

**Comment by goelakash** [comment]
The title is misleading and actually follows a different error, which has been fixed by previous commits. We should file separate bug reports for different bugs.

**Comment by henrykironde** [comment]
Okey I will close this over the weekend when I am cleaning all the issues. Thank you so much 
@goelakash

**Comment by ethanwhite** [comment]
This is fixed now.
