### ISSUE TITLE
Add check for the number of rows inserted against the raw data set number of rows

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#676]
For some datasets that are poorly assembled, retriever may not be able to detect and install the right number of rows as expected from the raw data. For example in EltonTraits shown below.

We should report such cases.
![cmd](https://cloud.githubusercontent.com/assets/5192965/19280960/dee63d34-8fb5-11e6-9d51-5a32fd718e60.png)

**Comment by henrykironde** [comment]
Current state: This issue was partially covered in b2e20708e70e889101c802ba7e56695fb38f6dee
However, we still have some clean up to do with "https://github.com/weecology/retriever/blob/master/lib/engine.py#L117"

Error can be seen when downloading BBS.

**Comment by ethanwhite** [comment]
Is this just an issues with:

`total = self.table.record_id + real_line_length`

My guess is that the `self.table.record_id` part is designed for when we're appending data to an existing table, but then we compare that to just `current` or `real_line_length`. So presumably we want either add `self.table.record_id` to both numbers or neither.

**Comment by articuno12** [comment]
Hi ! I am new here.If this bug is not fixed then can I take it?

**Comment by ethanwhite** [comment]
I think this has been fixed already. @henrykironde - can you confirm this?

@articuno12 - welcome, and thanks for your interest in contributing! We have a number of [issues labeled `getting-started`](https://github.com/weecology/retriever/issues?q=is%3Aissue+is%3Aopen+label%3Agetting-started) that we consider good starting points for people just getting familiar with the project.

**Comment by henrykironde** [comment]
Fixed
