### ISSUE TITLE
AOU codes in BBS data sets

### ISSUE THREAD

**Issue by davharris** [weecology/retriever#682]
At the top of the `SpeciesList.txt` file, it says the following:

```
North American Breeding Bird Survey Species List (06/15/2016) in Phylogenetic order.
Seq = Sequence number indicating phylogenetic order based on 56th Supplement to AOU Check-list of North American Birds.
AOU = Unique species identification number used for BBS data management purposes.
```

In other words, the "AOU" column refers to internal BBS codes and the "Seq" column refers to codes actually used by the AOU.

Should the columns be renamed to reflect this?

**Comment by ethanwhite** [comment]
So when they say "indicating phylogenetic order" they mean that actual AOU codes?

This is a tricky case. The challenge is that if we want people to be able to easily relate the dataset we create to the raw BBS data and it's associated documentation, then we're better off keeping the column names. If we want folks to be able to easily related BBS data to other data sources through AOU codes, then we're better off making the change. We can't do both, so the question is which not perfect choice do we make. I'd be curious to hear everyone's thoughts on the best option here.

If @ahhurlbert, @jescoyle, and anyone else has thoughts we'd love to hear them to.

**Comment by ahhurlbert** [comment]
"Phylogenetic order" is the official order in which species are listed based on their phylogenetic relationships to each other. This gets revised from year to year based on discoveries, e.g., that quails are now considered basal compared to whatever, etc.

The only reason one would ever use `Seq` is if one wanted to print out a local or regional bird checklist in Phylogenetic order (as birders expect them). I would think you can ditch it for any analysis of these data. (If you care about phylogenetic order, you're presumably working with an actual tree!)

Originally, AOU codes were probably in phylogenetic order but much has changed over the past 30-40 years, so now they are just species codes that mostly group reliably by current "Family" concepts but not always.

**Comment by davharris** [comment]
Actually, I [just discovered](https://www.pwrc.usgs.gov/BBl/manual/bandsize.cfm):

>The AOU stopped using species numbers with the 7th edition of the checklist

So I think @ahhurlbert is right: we can probably just drop the `Seq` column entirely. The rank ordering of the two columns is mostly pretty similar anyway (spearman's Rho = 0.82).

**Comment by ethanwhite** [comment]
OK thanks everyone. Unless anyone sees a positive value in getting rid of the `Seq` column I think we'll keep it so as to remain close to the original data source, but I'm also happy to take a PR to get rid of it with an explanation of why.
