### ISSUE TITLE
Move main package into subdirectory

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#683]
The root directory has gotten pretty crowded, and standard structure for Python projects is to have the main package code in a subdirectory with the package name (see http://docs.python-guide.org/en/latest/writing/structure/).

**Comment by kunalpal** [comment]
Hi @henrykironde, @ethanwhite, I am working on this. The `version.py` file is more related to managing the repository rather than the core code. Should I keep it outside the core?

**Comment by ethanwhite** [comment]
Yes, `version.py` should be in the root directory. I believe this is mentioned in the docs linked above. One tricky thing that you'll need to look out for is that existing releases download files from the current `scripts` directory so that directory will probably need to remain in the root directory.

**Comment by ethanwhite** [comment]
Also, welcome and thanks for contributing!!

**Comment by kunalpal** [comment]
Thanks. And yes, I have kept the test and the scripts on root directory. Only the codes strictly necessary for any user to import has been moved.

**Comment by henrykironde** [comment]
Closing, Fixed by @kunalpal  #811 merged into 29e5585
