### ISSUE TITLE
retriever update error on Windows 8

### ISSUE THREAD

**Issue by ahhurlbert** [weecology/retriever#688]
After installing fresh from master and typing `retriever ls`:

```
...
Zachmann2010 is supported by Retriever version 2.0.0-dev
Current version is v2.0.0-dev
Available datasets : 0

Traceback (most recent call last):
  File "C:\Users\hurlbert\AppData\Local\Continuum\Anaconda\Scripts\retriever-script.py", line 9, in <module>
    load_entry_point('retriever==2.0.0-de', 'console_scripts', 'retriever')()
  File "C:\Users\hurlbert\AppData\Local\Continuum\Anaconda\lib\site-packages\retriever\__main__.py", line 152, in main
    lscolumns.printls(sorted(all_scripts, key=lambda s: s.lower()))
  File "C:\Users\hurlbert\AppData\Local\Continuum\Anaconda\lib\site-packages\retriever\lscolumns.py", line 40, in printls
    for pos in range(len(columns[0])):
UnboundLocalError: local variable 'columns' referenced before assignment
```

**Comment by ethanwhite** [comment]
I watched this happen on @ahhurlbert's machine. There is an entire string of lines like

```
Zachmann2010 is supported by Retriever version 2.0.0-dev
Current version is v2.0.0-dev
```

when `retriever ls` runs (one for each script probably). It looks like for some reason we're rejecting scripts based on versions even though the versions match?

Maybe we missed a `script_version` -> `version` in #681? e.g.,
https://github.com/weecology/retriever/search?utf8=%E2%9C%93&q=script_version

**Comment by ethanwhite** [comment]
I was wrong in my initial suspicion about what might have been happening here. 

This error happens when there are no scripts to be displayed (see #119), so it is being triggered in this case by the fact that the retriever doesn't think any of the scripts are up-to-date and doesn't update them.

@ahhurlbert - we've made a few changes that may prevent this from happening in the last couple of months. Can you do the

```
retriever reset all
pip uninstall retriever
pip install git+ssh://git@github.com/weecology/retriever.git
```

routine and see if this is still happening? Thanks.

**Comment by ahhurlbert** [comment]
Different, but still not desired behavior I don't think. 

Status lines for all of the datasets repeat twice (see output below), and at the end it lists only 2 datasets available. As far as I can tell (by playing around with ecodataretriever in R), those are the test datasets Adult and Wine.

```
$ retriever ls
Abalone is supported by Retriever version 2.0.dev
Current version is v2.0.dev
...
<similar lines for all datasets Abalone thru Zachmann, then repeating Abalone thru Zachmann again!>
...
Zachmann2010 is supported by Retriever version 2.0.dev
Current version is v2.0.dev
Available datasets : 2

Adult  Wine
```

**Comment by henrykironde** [comment]
@ahhurlbert, thanks am working on it right away

**Comment by ethanwhite** [comment]
@ahhurlbert - can we set up some time for me to screen share with you on this machine? We recently did installs on a bunch of Windows machines and haven't been able to replicate.

**Comment by ahhurlbert** [comment]
@ethanwhite and I will try to resolve this while he's here in NC this week.

**Comment by ahhurlbert** [comment]
After updating my Anaconda install from scratch, this error (which seemed to be an error in a base python parse function) now seems to be resolved.

**Comment by ethanwhite** [comment]
🎉 That's great news. Thanks Allen!
