### ISSUE TITLE
Error downloading eBird_observation data.

### ISSUE THREAD

**Issue by goelakash** [weecology/retriever#692]
The URL doesn't work anymore.

**Comment by ethanwhite** [comment]
Unfortunately they pulled this dataset down several months ago. It had sounded from @mbjones (in #513) like it might go back up, but I just checked DataONE and now it says "This file is too large to download, please contact us about how to access this data". This probably makes it impossible for us to support the dataset going forward.

@mbjones - do you know if there's anyway to access the eBird data directly over the internet going forward?

**Comment by ethanwhite** [comment]
OK, at this point I think we should go ahead and remove eBird support.
