### ISSUE TITLE
Increment versions on BAAD, leda, EA_petraitis2008, BBS, and BBS50

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#694]
#691 updated 5 scripts but didn't update their version numbers (since we haven't documented this requirement yet). The version numbers in these five scripts all need to be upped to 1.2.

@zhangcandrew - if you have a time this would be something fairly straightforward to help out with. The values for `version` in each of those 5 JSON files just need to be updated.

**Comment by zhangcandrew** [comment]
Am I upping the versions in their respective .py files? I can't seem to find a .json for each of these in the scripts folder.

**Comment by ethanwhite** [comment]
Yes, that's right. For datasets requiring more complicated cleanup and restructuring the information can't be captured in JSON files so the core script is the Python file.
