### ISSUE TITLE
Add developer tools to assure script versions get update

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#707]
Whenever a script is changed its `version` value needs to be incremented. This sort of thing is easy to forget and we should have some tools to help avoid missing it.

- [ ] Add a pre-commit hook that checks if there are changes in ./scripts/ and if so runs `version.py` and runs `git add version.txt`
- [ ] Update `version.py` to check scripts that have been changed (i.e., that have diffs) to see if the script version numbers have been changed, and if not, increment them.

This issue takes over the last two pieces of #318.

**Comment by zhangcandrew** [comment]
Closing this for now after #849 was merged in! This can be reopened if any problems arise with the git hook.
