### ISSUE TITLE
Add ability to print a dataset specific message after installation

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#708]
Sometimes we want to communicate something about a dataset to the user. E.g.,

1. The data disappeared from the web so we can't download it anymore
2. There is an issue in one of the files that prevents us from processing it so we didn't download that one (#238)

We should add a field to take a text based message and print it after the installation of the dataset to cover all of these possibilities. For the first possibility we would then remove all of the tables, thus preventing any installation, and just print out a message saying the dataset is no longer available.

**Comment by kapilkd13** [comment]
Hi, I would like to work on this issue.

**Comment by ethanwhite** [comment]
Great. Thanks @kapilkd13! Go for it and let us know if there's anything we can do to help.

**Comment by ethanwhite** [comment]
Implemented and merged in #846. Thanks again @kapilkd13!
