### ISSUE TITLE
Improve memory usage when creating cross tab

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#715]
Currently  `def get_ct_data` returns a list of all the lines in the dataset for large datasets.
This will result in to memory problems.  

Best way to go about this is perform the cross tab processing as we loop through each line in the add to table. Currently we are processing the cross tab lines before we start looping through the lines

**Comment by ShivamNegi** [comment]
I am working on this. Can you tell me the command to use to test the `engine.py`.

**Comment by ethanwhite** [comment]
To run the full test suite you can use `py.test`.

To just run the unit tests `py.test -k "test_retriever"`.

The integration tests run some tests to make sure that the cross tab functionality is working and can be run with `py.test -k "integration"`.

Let me know if you had something else in mind.

**Comment by ShivamNegi** [comment]
I want to locally test the change I have done in `def get_ct_data`, which is under `./lib/engine.py`. How can I go about this?

**Comment by ethanwhite** [comment]
> I want to locally test the change I have done in def get_ct_data, which is under ./lib/engine.py. How can I go about this?

Ah, got it. To do a local install go to the top level directory of the repository and run:

```
pip install . --upgrade
```

You can then run the `retriever` commands as you normally would, but it will include the changes you've made.

As part of checking to see if you're changes worked you'll also want to check to make sure they didn't break anything. You can do this by running:

```
py.test
```

from the same directory. You'll need the pytest module installed to do this which you can install using:

```
pip install pytest
```

Also what is cross tab processing?

It is taking data that is "wide" and making it "long" or properly normalized. See http://www.ats.ucla.edu/stat/stata/modules/reshapel.htm for some examples.

**Comment by ShivamNegi** [comment]
Thanks.
