### ISSUE TITLE
Remove encoding='latin-1'

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#716]
Remove the hard coded assignments for encoding. 
We should have an optional value in the scripts that could utilize a different encoding.
The retriever should be able to use that property when opening files and processing data based on the assigned encoding, otherwise the retriever will stick with the default encoding.

**Comment by goelakash** [comment]
Yeah we can do that. How do we know which scripts don't support `latin-1` or `utf-8`?

**Comment by ethanwhite** [comment]
> Yeah we can do that. How do we know which scripts don't support latin-1 or utf-8?

The script writer will have to figure that out. We should use the optional `endoding` field from the datapackage spec to store this info:
http://specs.frictionlessdata.io/data-packages/#optional-fields-1

**Comment by jainamritanshu** [comment]
@henrykironde @ethanwhite I would like to work on this issue

**Comment by henrykironde** [comment]
sure go for it

**Comment by jainamritanshu** [comment]
@henrykironde should there be an option for the user to change the encoding through command line?

**Comment by henrykironde** [comment]
no it should only be the scripts that could change the default encoding

**Comment by henrykironde** [comment]
@jainamritanshu, solved this issue.
