### ISSUE TITLE
Testing for 2.0

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#752]
As we move towards releasing 2.0, please help me run `try_install_all.py` on the current master.
Make sure your postgres password is set since we made some changes to the default password for tests.

Comment below in case you are willing to test any part.

Note: A lot of data is downloaded so make sure you have unlimited internet 

The current status of `try_install_all.py` creates a dump directory(test_all) for all the files. In case you using pip install . --upgrade, make sure you delete this folder and clean the directory. This makes installation faster.

| OS \  System      | Python2          | python3  |
| ------------- |:-------------:| -----:|
| Windows 7  64   | @Henrykironde | @Henrykironde|
| Mac    | @Henrykironde | @Henrykironde|
| Ubuntu | @ethanwhite | @ethanwhite|

### Ubuntu, Python 3

Engine, Dataset, Error
('postgres', 'Ramesh2010', ProgrammingError('relation "testschema.macroplots" does not exist\nLINE 1: INSERT INTO testschema.macroplots (plotid, spcode, tree, Tre...\n                    ^\n',))
('mysql', 'Ramesh2010', ProgrammingError(1146, "Table 'testdb.macroplots' doesn't exist"))
('xml', 'PlantTaxonomy', IndexError('list index out of range',))
('xml', 'Adler2007', IndexError('list index out of range',))
('xml', 'Pantheria', IndexError('list index out of range',))
('sqlite', 'gwdd', IndexError('array index out of range',))
('postgres', 'gwdd', IndexError('array index out of range',))
('csv', 'gwdd', IndexError('array index out of range',))
('xml', 'gwdd', IndexError('array index out of range',))
('json', 'gwdd', IndexError('array index out of range',))
('mysql', 'gwdd', IndexError('array index out of range',))
('xml', 'MammalDiet', IndexError('list index out of range',))
('xml', 'leaf_herbivory', IndexError('list index out of range',))
('xml', 'TreeWesternGhats', IndexError('list index out of range',))
('xml', 'PokerHands', IndexError('list index out of range',))
('xml', 'FishParasiteHosts', IndexError('list index out of range',))
('xml', 'PhytoplankonBiovolume', IndexError('list index out of range',))
('postgres', 'Adult', DataError('value too long for type character varying(25)\n',))
('xml', 'ArcticBreedBird', IndexError('list index out of range',))
('sqlite', 'baad', UnboundLocalError("local variable 'open_archive_file' referenced before assignment",))
('postgres', 'baad', UnboundLocalError("local variable 'open_archive_file' referenced before assignment",))
('csv', 'baad', UnboundLocalError("local variable 'open_archive_file' referenced before assignment",))
('xml', 'baad', UnboundLocalError("local variable 'open_archive_file' referenced before assignment",))
('json', 'baad', UnboundLocalError("local variable 'open_archive_file' referenced before assignment",))
('mysql', 'baad', UnboundLocalError("local variable 'open_archive_file' referenced before assignment",))
('sqlite', 'WineQ', IsADirectoryError(21, 'Is a directory'))
('postgres', 'WineQ', IsADirectoryError(21, 'Is a directory'))
('csv', 'WineQ', IsADirectoryError(21, 'Is a directory'))
('xml', 'WineQ', IndexError('list index out of range',))
('json', 'WineQ', IsADirectoryError(21, 'Is a directory'))
('xml', 'Abalone', IndexError('list index out of range',))
('xml', 'MammalMR2010', IndexError('list index out of range',))
('xml', 'EA_petraitis2008', IndexError('list index out of range',))
('mysql', 'HomeRanges', ProgrammingError(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Tucker, M. A., T. J. Ord, and T. L. Rogers. 2014. Evolutionary predictors of mam' at line 1"))

I also had some MySQL errors due to a configuration issue that I've removed. This means that in some cases MySQL could be produces errors that aren't reported here. These tests are against #753.

**Comment by ethanwhite** [comment]
I've got these running on both Python 2 and Python 3 now.

**Comment by ethanwhite** [comment]
Just added errors for Ubuntu + Python 3 to the issue.

**Comment by zhangcandrew** [comment]
Just ran this on Ubuntu + Python 3 also. 

Generated this list of errors: 

ERROR.

Engine, Dataset, Error
('mysql', 'HomeRanges', ProgrammingError(1064, "42000You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Tucker, M. A., T. J. Ord, and T. L. Rogers. 2014. Evolutionary predictors of mam' at line 1"))
('xml', 'Falcone2010', IndexError('list index out of range',))
('postgres', 'Adult', DataError('value too long for type character varying(25)\n',))
('mysql', 'Adult', DataError(1406, "22001Data too long for column 'native_country' at row 366"))
('sqlite', 'Ramesh2010', OperationalError('no such table: Ramesh2010_macroplots',))
('mysql', 'Ramesh2010', ProgrammingError(1146, "42S02Table 'testdb.macroplots' doesn't exist"))
('xml', 'Palmer2007', IndexError('list index out of range',))

**Comment by ethanwhite** [comment]
Here are the current errors from my runs last night, but as @henrykironde and I noticed yesterday some of these aren't real (there appear to be some issues with try_run_all trampling on itself):

Ubuntu + Python 3:

```
Engine, Dataset, Error
('postgres', 'Ramesh2010', ProgrammingError('relation "ramesh2010.macroplots" does not exist\nLINE 1: INSERT INTO Ramesh2010.macroplots (plotid, spcode, tree, Tre...\n                    ^\n',))
('sqlite', 'Ramesh2010', OperationalError('no such table: Ramesh2010_macroplots',))
('mysql', 'Ramesh2010', ProgrammingError(1146, "Table 'Ramesh2010.macroplots' doesn't exist"))
('postgres', 'ForestFires', ProgrammingError('relation "forestfires.data" does not exist\nLINE 1: INSERT INTO ForestFires.data (x, y, month, day, ffmc, dc, is...\n                    ^\n',))
('postgres', 'AvianBodySize', ProgrammingError('relation "avianbodysize.species" does not exist\nLINE 1: INSERT INTO AvianBodySize.species (family, species_number, s...\n                    ^\n',))
('postgres', 'MammalLH', ProgrammingError('relation "mammallh.species" does not exist\nLINE 1: INSERT INTO MammalLH.species (ordered, family, genus, specie...\n                    ^\n',))
('postgres', 'PlantTaxonomy', ProgrammingError('relation "planttaxonomy.planttaxonomy" does not exist\nLINE 1: INSERT INTO PlantTaxonomy.PlantTaxonomy (symbol, synonym_sym...\n                    ^\n',))
('postgres', 'Adler2007', ProgrammingError('relation "adler2007.main" does not exist\nLINE 1: INSERT INTO Adler2007.main (plotyear, id, species, area, x, ...\n                    ^\n',))
('postgres', 'Pantheria', ProgrammingError('relation "pantheria.species" does not exist\nLINE 1: INSERT INTO Pantheria.species (msw05_order, msw05_family, ms...\n                    ^\n',))
('mysql', 'HomeRanges', ProgrammingError(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Tucker, M. A., T. J. Ord, and T. L. Rogers. 2014. Evolutionary predictors of mam' at line 1"))
('xml', 'Palmer2007', IndexError('list index out of range',))
```
