### ISSUE TITLE
Switch from `nulls` to `missingValues` in json package files

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#756]
This isn't in the official spec yet, but it looks like that's the direction it is heading. I've asked for clarification in https://github.com/frictionlessdata/specs/issues/353.

**Comment by ethanwhite** [comment]
OK, we have confirmation of this from the frictionlessdata issue.

**Comment by ShivamNegi** [comment]
I would like to work on this issue. All the json files under the ./scripts folder need to be changed, right?

**Comment by ethanwhite** [comment]
@ShivamNegi - oops, this should have been closed as it was implemented in d2645078c87670a447e7457bf133567ccee8ca44. Sorry about that.

It's great that you're looking for more things to work on. Let me know if you need any help or suggestions. I'll take a quick glance through the issues and make sure there isn't anything else that didn't get closed properly so this doesn't happen again.
