### ISSUE TITLE
Update internals to match datapackage spec

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#765]
After updating our language to match the datapackage spec our internal naming doesn't match the naming in our datapackage files. We should update this to make everything easier to understand. Specifically

* tags -> keywords
* nulls -> missingValues
* name -> title
* shortname -> name

Possibly a few others I'm not thinking of.

In many cases this will basically be find & replace, but being careful to watch out for potential complexities.

**Comment by jainamritanshu** [comment]
@ethanwhite I am working on this

**Comment by ethanwhite** [comment]
This is complete as of the merging of #897. Thanks again @jainamritanshu!
