### ISSUE TITLE
Reinstate Fia script (Forest Inventory and Analysis)

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#766]
Forest Inventory and Analysis changed the file locations.
New species table url: https://apps.fs.usda.gov/fiadb-downloads/CSV/REF_SPECIES.csv
new main:

The new changes needed for FIA

        self.urls = {"main": "https://apps.fs.usda.gov/fiadb-downloads/CSV/CSV/",
                     'species': 'https://apps.fs.usda.gov/fiadb-downloads/CSV/REF_SPECIES.csv'}

**Comment by henrykironde** [comment]
@ethanwhite, should we make the changes in a separate PR, or include them in the current PR under review?

**Comment by ethanwhite** [comment]
Separate PR.

**Comment by henrykironde** [comment]
Am waiting for `FIA` server to go up again, 
https://apps.fs.usda.gov/fiadb-downloads/CSV/CSV/AL_TREE.zip
Else we may switch to downloading  `.csv` files instead of `.zip`
