### ISSUE TITLE
Catch errors when `install` and `download` are run w/o arguments

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#774]
Running `install` and `download` without the name of a dataset triggers a messy Python error. We should report the associated usage help instead.

```
ethan@gandalf:~$ retriever install
Traceback (most recent call last):
  File "/home/ethan/miniconda3/bin/retriever", line 11, in <module>
    load_entry_point('retriever==2.0.dev0', 'console_scripts', 'retriever')()
  File "/home/ethan/miniconda3/lib/python3.5/site-packages/retriever/__main__.py", line 159, in main
    engine = choose_engine(args.__dict__)
  File "/home/ethan/miniconda3/lib/python3.5/site-packages/retriever/lib/tools.py", line 124, in choose_engine
    enginename = enginename.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by henrykironde** [comment]
@ethanwhite could you try to run that command `retriever install` if error,
followed by `retriever reset`

**Comment by Parth-25m** [comment]
I think that the issue has been resolved.

**Comment by henrykironde** [comment]
@Parth-25m did you try to run `retriever install`?

**Comment by Parth-25m** [comment]
yes

`retriever git:(master) retriever install

usage: retriever install [-h] [--compile] [--debug]
                     {mysql,postgres,sqlite,msaccess,csv,json,xml} ...

retriever install: error: too few arguments

➜  retriever git:(master) ✗ retriever download

Exception: no dataset specified.
`

**Comment by ethanwhite** [comment]
Looks like this might be a Python version number difference. On Ubuntu using Python 2 I get the correct behavior, but using Python 3 I get the error reported above. Can anyone else confirm that this is the source of the different behaviors?

**Comment by zhangcandrew** [comment]
I am on Ubuntu, running Python 3 with the most current version of retriever. I am also getting the error above, mentioned by Ethan.

**Comment by henrykironde** [comment]
This could be a permission issue, could you give me the sequence of  command you are running including the command you are using to install

**Comment by ethanwhite** [comment]
```
pip install . --upgrade
retriever install
```

@henrykironde - are you not seeing this on Python 3?

**Comment by henrykironde** [comment]
my errors vary, I am going through it to find why there is a difference
