### ISSUE TITLE
Version.py throws error when run in python2

### ISSUE THREAD

**Issue by ShivamNegi** [weecology/retriever#778]
`str` has no attribute `casefold` in python 2. I suggest we change the `casefold` to `lower` to correct this.

**Comment by ethanwhite** [comment]
Agreed.

**Comment by ShivamNegi** [comment]
#781 done.

**Comment by ethanwhite** [comment]
Fixed in 509dd5802a4dab8fae61650bf39e389eb14a4945.

**Comment by ethanwhite** [comment]
Thanks @ShivamNegi!
