### ISSUE TITLE
Incorporate the PREDICTS database release

### ISSUE THREAD

**Issue by dmcglinn** [weecology/retriever#792]
This is an impressive global database on species richness and abundance - it seems well suited for the `retriever`

http://data.nhm.ac.uk/dataset/902f084d-ce3f-429f-a6a5-23162c73fdf7

**Comment by ethanwhite** [comment]
Totally agree.

I tried to do this right when it came out but there was no direct download link. I've been corresponding with the folks in charge and they provided this link:
http://data.nhm.ac.uk/dataset/the-2016-release-of-the-predicts-database/resource/78dac1a9-6aa0-4dcb-9750-50df04f8ca6e/download

We are allowed to use it for the retriever, but we're not supposed to advertise it more broadly.

**Comment by dmcglinn** [comment]
ah yea I see now that they want your email address to download the files. Nice job getting that direct link!

**Comment by jainamritanshu** [comment]
@ethanwhite I would like to proceed on this. Shall I?

**Comment by henrykironde** [comment]
@jainamritanshu, go for it

**Comment by jainamritanshu** [comment]
@ethanwhite @henrykironde Sorry if I am missing something. I have created the json script of PREDICTS but the python script has not been created. I saw the comment in `def compile_json`(file `lib/compile.py`) that the command to do so is `retriever create_json <script name>`. When I do so, the cli tells me that it is an invalid argument. The exact error I got -
`retriever: error: argument command: invalid choice: 'create_json'`. Please help?

**Comment by ShivamNegi** [comment]
I think that the argument you are searching for here is ```new_json```. You can view all the options using ```retriever -h```.

**Comment by jainamritanshu** [comment]
@ShivamNegi I made the .json file using `new_json`. As I stated

> I have created the json script of PREDICTS but the python script has not been created.

But the .py file script wasn't created and as you can see in the screenshot -
![screenshot from 2017-03-03 21-22-35](https://cloud.githubusercontent.com/assets/15127027/23557865/931d4344-0057-11e7-98e7-1921bc68f471.png)

I saw the comment that stated that I need to execute the command `retriever create_json <script name>`. So I got confused. Thanks anyways. :)

**Comment by henrykironde** [comment]
Sorry, we forgot to change the docs. You could PR the changes to correct that.

**Comment by jainamritanshu** [comment]
@henrykironde Will do that :)
