### ISSUE TITLE
Tests for 2.0.0 version release

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#795]
Hi everyone, we are wrapping up the release of the data retriever 2.0.0. Kindly asking for your time to try the tool out. We have installer for windows, linux and mac. Use the appropriate  installer to test out the software.  Downloads are available. And If you have a question please let me know. Remember if you installed the retriever from source using pip, make sure you uninstall it first. Use `pip uninstall retriever`. In order to remove all copies installed, run the command until there is not retriever version. Let me know how it goes. :+1:   
Link to downloads: (https://drive.google.com/drive/folders/0B0RpXeCC7TSXakxBSS1qR2ZXRUE?usp=sharing)

**Comment by ethanwhite** [comment]
You can also test `pip` based installs using:

pip install git+https://git@github.com/weecology/retriever.git

**Comment by ethanwhite** [comment]
You can also test the R package using:

```
install_github("ropensci/rdataretriever")
```

**Comment by ahhurlbert** [comment]
All good now on my previously bonking Windows 8 machine after reinstalling Anaconda

**Comment by sdtaylor** [comment]
On ubuntu:

- [x] debian package
- [x] rdataretriever + debian package
- [x] anaconda pip install from github
- [x] rdataretriever + anaconda pip install from github

**Comment by MarconiS** [comment]
on MacOs Sierra  10.12.3 (16D32)
All good, included rdataretriever, anaconda pip installer and retriever app

**Comment by henrykironde** [comment]
Thanks everyone who contributed to the release of 2.0.0. We really appreciate the efforts, and being part of the endeavors to make science better and smooth.
