### ISSUE TITLE
install to msaccess error

### ISSUE THREAD

**Issue by emchristensen** [weecology/retriever#798]
When I try to install a dataset to msaccess I get the error:
Couldn't create table (no module named 'pypyodbc')

I've tried doing "pip install pypyodbc --upgrade" which seems to work, but doesn't help with the retriever error.

I'm on a windows 10 machine

**Comment by ethanwhite** [comment]
Is this install done using the Windows installer (the .exe)? If so then I think we packaged the wrong ODBC package with it.

**Comment by emchristensen** [comment]
Yes I used the .exe

**Comment by ethanwhite** [comment]
Thanks. @henrykironde will rebuild that package and have you test again.

**Comment by emchristensen** [comment]
after installing with the new .exe, I now get the error "Access Driver is not found"

**Comment by ethanwhite** [comment]
@emchristensen - I can't remember, did we ever get this figured out?

**Comment by emchristensen** [comment]
I can't remember either.  Can you remind me how to test this, and I'll try it again?

**Comment by emchristensen** [comment]
I just tried it again and got the same error message -- Henry is going to check it out

**Comment by emchristensen** [comment]
this is still not working -- on Windows 10 Pro

**Comment by ethanwhite** [comment]
Given the difficulty of testing I wonder if we should deprecate support for Access.
