### ISSUE TITLE
Mac app bundle

### ISSUE THREAD

**Issue by davharris** [weecology/retriever#802]
From @ethanwhite, I understand that the .app bundle on the mac doesn't need to do anything for retriever to work (because there's no GUI anymore).

Would it be possible to make it so that double-clicking the .app bundle brings up a little window with the rest of the installation instructions? Or a link to the correct section of the web site?  I think a lot of users will just try double-clicking the bundle over and over again, wondering why nothing is happening.

**Comment by davharris** [comment]
Alternatively, making a DMG is pretty easy.  I just followed the steps on this page: http://www.wikihow.com/Make-a-DMG-File-on-a-Mac

The dmg is nice because you can add a background image or a README file with instructions

**Comment by ethanwhite** [comment]
Replaced by #1028
