### ISSUE TITLE
Add `description` field to dataset list?

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#809]
Someone just [asked on Twitter](https://twitter.com/lexnederbragt/status/836252543831396353) about having more info on each dataset on the dataset list page in the docs. I think we maybe talked about including the `description` field at some point and decided it was too much, but looking at that page now I definitely think having the opportunity to see that additional info would be useful. We should consider either adding it there or having links that take the user to pages with more details for each dataset (e.g., the description, citation, keyword and url fields).

**Comment by jainamritanshu** [comment]
Sir I would like to work on this. Could you help me proceed on this?

**Comment by henrykironde** [comment]
@jainamritanshu, unfortunately this is already finished, Just waiting to put in a PR.

**Comment by ethanwhite** [comment]
Fixed by 148ceb37460f5c29056561ac5d32587486337569.
