### ISSUE TITLE
Skip compiling .json files to .py files

### ISSUE THREAD

**Issue by kunalpal** [weecology/retriever#812]
Hi, Is there a reason for compiling [file].json files to [file].py files? We can generate Script class instances directly from the loaded json files. So, what are the benefits of using the current approach?

**Comment by jainamritanshu** [comment]
@kunalpal correct me if I am wrong, but as far as I have understood the flow of Data Retriever, the .json files are used for [datapackaging](https://specs.frictionlessdata.io/data-package/). As the documentation states - 

> Data Package is a simple container format used to describe and package a collection of data sources with additional metadata about those data sources.

There is a `lib/templates.py` which makes a `class Script(object)` which behaves as the parent class for the scripts in python. Instances of this class are created in individual python scripts so as to further download, clean and store the data in a preferred database. I may have skipped/missed few parts, but this seems to be the essence of the flow.

**Comment by henrykironde** [comment]
Correct

**Comment by henrykironde** [comment]
@kunalpal, feel to create a PR based on the design you feel we should adopt. I will be more than happy to go through it.

**Comment by kunalpal** [comment]
Thanks @jainamritanshu and @henrykironde . I certainly will..:) Keeping this open till then.

**Comment by ethanwhite** [comment]
Completed in #1042.
