### ISSUE TITLE
Add autocomplete for commands and dataset names

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#815]
As we add more and more datasets making it easier to remember their names would be useful. One option for doing this is [argcomplete](https://argcomplete.readthedocs.io/en/latest/).

**Comment by kunalpal** [comment]
I am looking into this.

**Comment by kunalpal** [comment]
I have introduced completion for datasets, json files and keywords with `argcomplete` so far. Should `argcomplete` be included in required packages? Also, `argcomplete` requires running `activate-global-python-argcomplete` and `eval "$(register-python-argcomplete retriever)"` after installation. Should I modify `setup.py` accordingly?

**Comment by ethanwhite** [comment]
Yes to both. Thanks!
