### ISSUE TITLE
Add regression test for a .py script

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#830]
We don't currently have any regression testing on `.py` scripts and that has lead to a couple of errors related to those scripts sneaking in in the past year (e.g., see #134). We should add one of these scripts (which ever runs most quickly) to the regression testing to avoid missing these sorts of things in the future.

**Comment by kunalpal** [comment]
@ethanwhite, I would like to work on this.

**Comment by ethanwhite** [comment]
Awesome. Go for it. The way the regression tests work is that they install a given dataset into all of the different output formats and then extract it from each of them into a csv file. The test is against a hash for that csv file that we've confirmed is correct (i.e., we've looked at the raw data and compared it to our csv and made sure the output looks right). Let us know if you have any questions.

**Comment by articuno12** [comment]
@ethanwhite Can I work on it?

**Comment by henrykironde** [comment]
@articuno12, Thank you for showing interest in contributing to the retriever. Please go a head and work on this. If you need any help, feel free to ask. Our community is a very welcoming community with developers from various places of the world, We do welcome all skill sets and provide guidance where needed. :+1:

**Comment by ethanwhite** [comment]
Implemented in 9440442f4be8b5f9a06ea892c283d22608c26215.
