### ISSUE TITLE
Add CI testing against 2.0.0 <= Release versions 

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#838]
This will help us avoid making any backwards incompatible changes to scripts.

**Comment by ethanwhite** [comment]
We just accidentally broke some scripts in `2.0.0` (see #947) by merging a breaking change to the `.py` scripts in #944. This is easy to do so it would be nice to figure out a way to do some testing on it.

**Comment by henrykironde** [comment]
Working on it

**Comment by henrykironde** [comment]
**This is open for anyone to work on**

Test with released versions

For example:
To test `retriever2.0.0`, first uninstall the current version of retriever.
And Install the release to be tested. `Pip install retriever==2.0.0`
and perform some tests like `retriever ls` 

We could create this as a bash_script

**Comment by Prodyte** [comment]
I want to work on it. Any suggestions?

**Comment by henrykironde** [comment]
There is a pull request (PR) on this issue. Feel free to take over it and create a new one. https://github.com/weecology/retriever/pull/1288/files
The idea is to install retriever as shown here https://github.com/weecology/retriever/pull/1288/files#diff-354f30a63fb0907d4ad57269548329e3R31
And test if you get any errors when you run retriever ls as in https://github.com/weecology/retriever/pull/1288/files#diff-354f30a63fb0907d4ad57269548329e3R35

**Comment by ethanwhite** [comment]
I can't remember if we ended up getting this in, but if we have't I think we should go ahead and expect users to upgrade at this point and maybe make the next release 3.0 to make that explicit.

**Comment by ethanwhite** [comment]
Oops, didn't mean to close. @henrykironde - if you agree with my comment above go ahead and close this.

**Comment by ethanwhite** [comment]
It's been long enough at this point that I think we can assume everyone has upgraded to the new script format.
