### ISSUE TITLE
Update script writing documenation on fields

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#840]
From a conversation in one of the PRs, it's noticeable that we don't have documentations on somethings in the script, which may make things complicated

For example:
Why some scripts like the example below, just have links to the direct csv files and no columns/fields names, while others do have columns/fields names added 
We should include such information in the docs

```
{
    "citation": "S. K. Morgan Ernest. 2003. Life history characteristics of placental non-volant mammals. Ecology 84:3402.",
    "description": "",
    "homepage": "",
    "keywords": [
        "Mammals",
        "Compilation"
    ],
    "name": "exMammal",
    "resources": [
        {
            "dialect": {},
            "name": "species",
            "schema": {
                "fields": []
            },
            "url": "http://esapubs.org/archive/ecol/E084/093/Mammal_lifehistories_v2.txt"
        }
    ],
    "retriever": "True",
    "retriever_minimum_version": "2.0.dev",
    "title": "Mammal Life History Database - Ernest, et al., 2003"
    "urls": {
        "species": "www.exampleurl.com"
    },
    "version": "1.0.0"
}

```

However like Ethan said, we do recommend including the fields. Scripts with fields use less processing time.

**Comment by kvnamipara** [comment]
I am working on it.

**Comment by kvnamipara** [comment]
@henrykironde @ethanwhite 
In Documentation, In script creation example, name of table is given as `example-mammal`, while in created json file it is shown as `exMammal`.
![screen shot 2017-03-12 at 1 46 26 pm](https://cloud.githubusercontent.com/assets/18012563/23830190/cc715fb6-072a-11e7-9abd-e778b2ab4759.png)
![screen shot 2017-03-12 at 1 46 47 pm](https://cloud.githubusercontent.com/assets/18012563/23830191/ce8e00e2-072a-11e7-92fb-267d12dcf586.png)
Should I change it?
Also should we include schema in highly recommended attributes given at the top of the documentation page? 
Or should we update the example by giving example of addition of dataset which include addition of schema?

**Comment by kvnamipara** [comment]
@henrykironde @ethanwhite 
Should we change view of common task of Retriever like
![screen shot 2017-03-12 at 2 09 08 pm](https://cloud.githubusercontent.com/assets/18012563/23830303/b33def02-072d-11e7-9b7f-4ab98e2a86c1.png)
to number wise bullets per line like this
![screen shot 2017-03-12 at 2 09 25 pm](https://cloud.githubusercontent.com/assets/18012563/23830304/b4e392b2-072d-11e7-9763-94d9688d4ff8.png)

**Comment by henrykironde** [comment]
`In Documentation, In script creation example, name of table is given as example-mammal, while in created json file it is shown as exMammal.`
 Yes change it

`Also should we update the example by giving example of addition of dataset which include addition of schema?` 
Just giving the names would be fine.

`Should we change view of common task of Retriever like`
Go for it. i think it looks better.

**Comment by kvnamipara** [comment]
@henrykironde 
`From a conversation in one of the PRs, it's noticeable that we don't have documentations on somethings in the script, which may make things complicated`
i am including `fields` section . Any other thing we should consider?

**Comment by henrykironde** [comment]
I suggest making sure that all key values have an explanation.
