### ISSUE TITLE
Add Vanni et al. dataset - global database of nitrogen and phosphorus excretion rates

### ISSUE THREAD

**Issue by dmcglinn** [weecology/retriever#848]
This suggestion came from @emhart 

>Consider adding the data from ["A global database of nitrogen and phosphorus excretion rates of aquatic animals"](http://onlinelibrary.wiley.com/doi/10.1002/ecy.1792/abstract) DOI:10.1002/ecy.1792

**Comment by zhangcandrew** [comment]
The dataset has been merged in #857! Closing this now. Feel free to open it again if any issue pops up with the Vanni dataset.
