### ISSUE TITLE
Desgin complexity relating to adding a Python interface

### ISSUE THREAD

**Issue by ShivamNegi** [weecology/retriever#858]
As mentioned in #137 and in gsoc project idea. A Python interface has to be developed for data retriever.
I am confused on how the file structure for this would be implemented.
The `__init__` file already contains the code for the CLI. In order to implement package capabilities alongside the CLI we will have to add functions for the package in `__init__`. Won't the functions of the CLI show up when we `import retriever`?

**Comment by ethanwhite** [comment]
> The `__init__` file already contains the code for the CLI

The main CLI code is in `__main__` in the `main()` function. This function only gets executed if run from the command line.

> In order to implement package capabilities alongside the CLI we will have to add functions for the package in __init__.

Typically the way to get functions into `__init__` is through imports. Here's a standard simple example:
https://github.com/weecology/METE/blob/master/mete/__init__.py

So, we would want to create these Python interface functions somewhere and then import them. `main()` might be a good place to do this, taking the block code from the relevant conditionals, turning them into functions outside of main, using them in main, and importing them into `__init__`.

> Won't the functions of the CLI show up when we import retriever?

The current list of functions/variables in the import is a bit noisy

```
>>> retriever.
retriever.CITATION             retriever.HOME_DIR             retriever.SCRIPT_WRITE_PATH    retriever.exists(              retriever.open_csvw(           retriever.pwd
retriever.COPYRIGHT            retriever.MASTER_BRANCH        retriever.VERSION              retriever.getmtime(            retriever.open_fr(             retriever.sample_script
retriever.DATA_DIR             retriever.MODULE_LIST(         retriever.absolute_import      retriever.imp                  retriever.open_fw(             retriever.set_proxy(
retriever.DATA_SEARCH_PATHS    retriever.REPOSITORY           retriever.compile_json(        retriever.io                   retriever.os                   retriever.str(
retriever.DATA_WRITE_PATH      retriever.REPO_URL             retriever.csv                  retriever.isfile(              retriever.parse_version(       retriever.sys
retriever.ENCODING             retriever.SCRIPT_LIST(         retriever.current_platform     retriever.join(                retriever.platform             retriever.to_str(
retriever.ENGINE_LIST(         retriever.SCRIPT_SEARCH_PATHS  retriever.dir                  retriever.lib                  retriever.print_function
```

and cleaning that up to only expose the user relevant ones would be a good part of a proposal on this.
