### ISSUE TITLE
Do not cache data files after failed downloads

### ISSUE THREAD

**Issue by kvnamipara** [weecology/retriever#863]
While downloading dataset in csv format, if download fails due to any problem, partially downloaded file is stored.
when we rerun the command to install the data again, if the partially downloaded file is present, then retriever is not downloading it again. So the csv file only contains partial data only.
Please check once.

**Comment by henrykironde** [comment]
Nice, could you give me an example dataset in which that happened for debugging?
And you trying to fix that issue?

**Comment by kvnamipara** [comment]
@henrykironde  
While i was doing local test to verify whether everything is working fine in `portal-dev`(#853). After download got interrupted due to network error, when i tried to rerun the install command, due to presence of partially downloaded file, Retriever didn't download the full version of file.

I think we have to make sure to store file if and only if it is completely downloaded.

Thanks.

**Comment by henrykironde** [comment]
I see, thats actually a good way to go. 
But the implementation I have in mind is not feasible for all files downloaded from the internet. 
`Reading the meta data of a file being downloaded to get the expected size
`
Unless the user knows the number rows he expects, I guess that will be hard to make perfect. 
Let me know if you have a way to accomplish that.

**Comment by ethanwhite** [comment]
What about modifying/improving the top-level error handling? I'm envisioning catching any errors in `__main__` and if an error occurs removing the data associated with that install and informing the user that something has gone wrong. If running with `--debug` then we can also return the associated error message.

**Comment by kvnamipara** [comment]
@ethanwhite @henrykironde 

I agree with above solution to catch error in `__main__` only.

We can also implement by adding feature of reseting individual dataset. Currently `retriever reset all`, remove all the script, data and connection. But ideas is to add one more option, for example `retriever reset portal-dev` will remove all the data for `portal-dev` dataset only. So now if error occur, we will run reset command for that dataset and tell user to run command for installation again.

Is this solutions seems feasible?
Thanks.

**Comment by kvnamipara** [comment]
@ethanwhite @henrykironde 
Is above idea feasible or catching error in `__main__` is better? Thanks.

**Comment by henrykironde** [comment]
Adding retriever reset [dataset] is a good add on.
However this does not actually solve the error.

Since it comes from downloading. We need to catch that error when the download fails. 
To replicate this, try to install any large dataset and as it downloads, disconnect the internet connection and find the best place to add the try block.

**Comment by kvnamipara** [comment]
@henrykironde Ok I will look for it. Thanks.

**Comment by kvnamipara** [comment]
@henrykironde @ethanwhite 
I was busy with my university laboratory exams. Now I will look into this.
Thanks.

**Comment by andy6975** [comment]
Hi, is this issue still available for contribution? I would like to work on this.

**Comment by henrykironde** [comment]
We are deleting the data incase a file is downloaded and an error is caught.
