### ISSUE TITLE
Pre-commit hook causing error on Ubuntu

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#867]
Anytime I try to commit the pre-commit hook is currently producing an error:

```
$ git commit
/usr/bin/env: ‘python\r’: No such file or directory
```

Ubuntu 16.04.

**Comment by zhangcandrew** [comment]
I will look into this tonight!

**Comment by zhangcandrew** [comment]
looks like it was a problem with line endings and formatting on Unix. I ran dos2unix on the file and added a PR for the hook to format it correctly in unix. 

There was a nice quick article about it here: http://thesimplesynthesis.com/post/env-pythonr-no-such-file-or-directory
