### ISSUE TITLE
update fray-jorge-ecolog data

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#876]
The data on the page has some seed data that is not currently included.

current figshare hopege: https://figshare.com/collections/Long-term_monitoring_of_mammals_in_the_face_of_biotic_and_abiotic_influences_at_a_semiarid_site_in_north-central_Chile/3305493

https://ndownloader.figshare.com/files/5625387 (Fray_Jorge_Seeds_20032005I.txt )
https://ndownloader.figshare.com/files/5625390 (Fray_Jorge_Seeds_20032005II.txt  )

**Comment by zhangcandrew** [comment]
I'll add these in when I get the chance!

**Comment by zhangcandrew** [comment]
Closing this issue after the merging of Fray Jorge. Feel free to open if a new pertinent issue arises
