### ISSUE TITLE
Add ability to handle simple archives using JSON scripts

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#884]
Some clean data files are distributed as archives. Instead of having to create `.py` scripts for these files it would convenient to have a way to designate this in the JSON. E.g., we are in the process of converting `tree-demog-wghats`, `pantheria`, and `forest-plots-wghats` to `.py` scripts because they were zipped when moved from the old Ecological Archives site to figshare.

**Comment by kvnamipara** [comment]
@ethanwhite 
Your idea is to use `JSON` file to access data from archives, but for that we require use of higher level language like `python`, right? Does `JSON` directly access archives?

**Comment by jainamritanshu** [comment]
@kvnamipara If I got your question right, I guess there has been a little confusion here. Correct me if I am wrong, JSON scripts here are being used for [datapackaging](https://specs.frictionlessdata.io/data-package/) and does not directly involve the use of JSON to access any field. The JSON script is basically compiled to a `.py ` script with the help of `compile.py`, `templates.py`  and databases are made with the help of `engine.py`.

@ethanwhite I guess we can add optional fields in the datapackage(JSON script) with respect to overriding the `download` method that is done in the JSON scripts for now. I would love any suggestions to work on this

**Comment by kvnamipara** [comment]
@jainamritanshu Thanks for explaining.

**Comment by ethanwhite** [comment]
Thanks to both of your for exploring this further.

Yes, the idea would be to either add new fields to the JSON or modify the existing fields so that they can contain information that multiple files all belong in the same table. We should check the datapackage specification to see if they have something for this and if not engage with that community on potentially drafting something.

We would then add code to the main `engine.py` class that would process this list and insert each file into a single table, similar to the code that is in scripts like `breed-bird-survey.py`starting around Line 158.

**Comment by ethanwhite** [comment]
This has now been implemented.
