### ISSUE TITLE
Pre-commit hook errors on name change

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#885]
I'm in the process of merging #879 and get the following error due to the pre-commit hook:

```
ethan@gandalf:~/RetrieverCode (master +|MERGING)$ git commit
From https://github.com/weecology/retriever
 * branch            master     -> FETCH_HEAD
fatal: pathspec 'scripts/tree_demog_wghats.json' did not match any files
Traceback (most recent call last):
  File ".git/hooks/pre-commit", line 56, in <module>
    subprocess.check_output("git add {}".format(file), shell=True)
  File "/home/ethan/miniconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/ethan/miniconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'git add scripts/tree_demog_wghats.json' returned non-zero exit status 128.
```

I suspect this is due to the name change for the script. We'll want to add some logic to prevent this from happening.

**Comment by zhangcandrew** [comment]
Right so it looks like we were previously comparing all differences in our git diff which caused deleted files to show up and cause this error. A fix to this could be to only look for staged files which are added and changed, not deleted. The git command would look like 
`git diff --cached --name-only --diff-filter=AT scripts`. 

I think I want to hold off on a little bit though before putting in a PR for the git hook. There seems to be another problem that happens with regex matching that I might have to talk to @henrykironde about. If you really want me to put one up before the other fix though, I can. It's a quick line changed at line 48.

**Comment by ethanwhite** [comment]
No rush on my end. I'll just keep overriding with `--no-verify` until this is ready to go.

**Comment by zhangcandrew** [comment]
Just put up the PR. Two minor fixes to the hook!
