### ISSUE TITLE
Use of data from Retriever

### ISSUE THREAD

**Issue by rachelss** [weecology/retriever#898]
For your records I have been using Retriever data in class (BIO539 - Big Data Analysis - University of Rhode Island Sp 2017 - https://rachelss.github.io/BigDataAnalysis/).

(1) Breeding bird survey to teach joins in R. The dataset was modified for a particular demonstration. The lesson is at https://rachelss.github.io/BigDataAnalysis/breedbird.html

(2) For a class assignment in python where students had previously used a similar dataset to learn analysis and are now required to download plant surveys and apply their skills to analyze new data. https://rachelss.github.io/BigDataAnalysis/assignment5.md

I appreciate the easy availability of these data and anticipate using these and other datasets in this and other classes.

**Comment by dmcglinn** [comment]
Awesome, I see that you use R in your class so also checkout `rdataretriever` https://github.com/ropensci/rdataretriever

**Comment by rachelss** [comment]
@dmcglinn I did use rdataretriever! would you like an rdataretriever issue for your records to support future funding?

**Comment by dmcglinn** [comment]
its all good but thanks for letting me know it worked for you guys we 
rolled out a new version recently which hopefully will greatly improve 
cross system compatibility as well as compatibility with Rstudio.

**Comment by ethanwhite** [comment]
Thanks so much for posting this @rachelss! It's always great to hear that the things you're building are helping people and useful for communicating it to funders as well. I have this written down where it needs to be so I'm going to go ahead and close the issue.
