### ISSUE TITLE
Is `parse_script_to_json.py` needed any more?

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#901]
I think this script file was created as part of the move to JSON datapackages in 6dc16a2f259f13b8a86dd64a099d6f29f55f2498. We don't have the script files anymore so I believe we can remove this. Can anyone else see a reason we would need to keep this?

**Comment by henrykironde** [comment]
Yes, that is true. Left that in when we were working on the EA PR initially.

**Comment by goelakash** [comment]
Yeah, I believe its not needed anymore.

**Comment by henrykironde** [comment]
will go ahead and remove it after the EA Pr is finalized

**Comment by ethanwhite** [comment]
Great. Closing this and replacing with a To Do item to remote it #911.
