### ISSUE TITLE
'module' object has no attribute 'BadZipFile'

### ISSUE THREAD

**Issue by davharris** [weecology/retriever#902]
I get the following error when I try to install some data sets. I'm using Retriever version v2.0.0 on my Mac (OS version 10.11.6)

```
$ retriever install sqlite "vertnet-amphibians"
=> Installing Vertnet Amphibians

'module' object has no attribute 'BadZipFile'
Done!
```

I get the same error for vertnet-birds and if I switch `sqlite` for `csv`. I *don't* get the error if I ask for all of vertnet, so it may have to do with the scripts for specific vertnet subsets.

Possibly related to #662, which also mentioned `BadZipFile` (albeit with different capitalization.  Sorry if the problem is on my end.

**Comment by ethanwhite** [comment]
Thanks for reporting @davharris.

It looks to me like the vertnet files on cyverse might be down at the moment. The link we have to `vertnet-amphibians`:

https://de.iplantcollaborative.org/anon-files//iplant/home/shared/commons_repo/curated/Vertnet_Amphibia_Sep2016/VertNet_Amphibia_Sept2016.zip

 is 404ing and if I go through vertnet's site I get a blank page:
http://datacommons.cyverse.org/browse/iplant/home/shared/commons_repo/curated/Vertnet_Amphibia_Sep2016

If this happened part way through your download it could explain what your seeing. It would work on just `vertnet` if you had a cached version.

I just emailed the `vertnet` folks to hopefully get them back up. Once that happens you should try running:

```
retriever reset all
retriever update
retriever install sqlite vertnet-amphibians
```

and see if things are fixed. If not we'll go from there.

**Comment by ethanwhite** [comment]
Cyverse was experiencing a network outage. It appears that this is fixed now. Can you follow the steps above and let us know if that fixes things. Thanks!

**Comment by davharris** [comment]
Looks like that fixed it.  Thanks!

Seems like it might be helpful to add a more informative error message (e.g. "cyverse is down, try again later" or "404"). Otherwise, I can close the issue.

Thanks again!

**Comment by ethanwhite** [comment]
We definitely need better error handling and reporting for cases where the download fails (404 or otherwise). I've opened #903 to address this. Thanks again!
