### ISSUE TITLE
Dataset pantheriatest needs update of null values

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#905]
pantheriatest  also uses '-999.00', '-999'as null value indicators  

[Ref](https://figshare.com/collections/PanTHERIA_a_species-level_database_of_life_history_ecology_and_geography_of_extant_and_recently_extinct_mammals/3301274):  metadata file(in zip file)

**Comment by shreyneil** [comment]
The Following PR https://github.com/weecology/retriever/pull/1045 has aready fixed the issue. It would be great if you could close this.

**Comment by ethanwhite** [comment]
Thanks @shreyneil. Closing now.
