### ISSUE TITLE
Make using custom scripts easier

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#91]
We should allow the explicit passing of a custom script at the command line. At the moment you would put the script in a hidden directory, which isn't bad, but something like:

    retriever install --custom /path/to/myscript

would be better.

This would mean that folks like @davharris could right a ~5 line text script instead of the 50 lines of SQL in #90 with all of the figuring out the types for each field and required customization to the DBMS of choice.

**Comment by henrykironde** [comment]
Solved by adding improved instructions in the documentation.
