### ISSUE TITLE
Naming for Julia package

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#910]
I'm very excited that @ShivamNegi will be developing a Julia wrapper for the retriever as part of his Google Summer of Code project. I'm going to setup a repository for this but we could use a name first. Any thoughts?

**Comment by ShivamNegi** [comment]
Lets go with `DataRetriever.jl`. Julia is amaze! :heart:

**Comment by ethanwhite** [comment]
That works for me. Does `data-retriever-jl` work for a repo name?

**Comment by henrykironde** [comment]
data-retriever-jl works fine.

**Comment by henrykironde** [comment]
data-retriever-jl works fine.

**Comment by ethanwhite** [comment]
OK, I just created a repo and gave @ShivamNegi and the core retriever folks write access:
https://github.com/weecology/data-retriever-jl
