### ISSUE TITLE
Python interface design and Julia interface

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#914]
Add Python interface #137 

This issue will be used to discuss details of adding python interface and Julia

**Comment by henrykironde** [comment]
We shall have to come up with new clean functions specifically for the interfaces in some cases. These functions should only return the required functions and should not include the print statements that we get when running retriever in command line.

**For example:** 
`retriever ls` will print some information for users when in CLI, like the download progress when updating.

For the interface, we shall have the a function, i.e ` get_datasets()`, or `retriever_datasets()` that return a list of datasets with no additional information. 

In this way we can have Julia use the python functions and get only required with out having to pre-process the Julia out put. This will keep the software intact.

**Comment by henrykironde** [comment]
Hi @ShivamNegi, I have looked at the branch `https://github.com/ShivamNegi/retriever/commits/restructure_commits`
In dataset there are still some merge conflicts `retriever/lib/datasets.py` I think you have included all the changes, Go ahead and clean up the last bit and I will get ready to review it. Also after making the last commit, run tests locally before you push.

**Comment by ShivamNegi** [comment]
Hi! I have resolved the merge conflict in `retriever/lib/datasets.py`. Please review the the commits. These commits are only for the `python-interface` branch. Once these are done I will merge it with `master`.

**Comment by henrykironde** [comment]
Okey, you can PR to this branch https://github.com/weecology/retriever/tree/python-interface2.
If from the latest master

**Comment by henrykironde** [comment]
NOTE: the changes in scripts will break compatibility of older versions. But don't worry we shall deal with that later.

**Comment by henrykironde** [comment]
Closing because have have both interface and julia package. Any issues regarding this issue can be resubmitted as a new issue
