### ISSUE TITLE
Out of the box testing errors on OSX Sierra

### ISSUE THREAD

**Issue by goelakash** [weecology/retriever#922]
Hi guys,

I recently ran the tests locally on Mac OSX Sierra, and a bunch of tests got errored out. I was expecting all the DB tests to fail, but I got some csv and others tests to fail as well. Error log: 
[error.txt](https://github.com/weecology/retriever/files/1065966/error.txt)

**Comment by henrykironde** [comment]
Looks like you are running `nose tests`.
We are using `pytests`
Also make sure the repo is clean and dependencies are up to date specially sqlite. 
Could you try to run the tests in a new python environment 
I am also using OSX Sierra.

**Comment by goelakash** [comment]
Closing as this seems to be as it seems that the documentation is stale.
