### ISSUE TITLE
Update docs for contributions.

### ISSUE THREAD

**Issue by goelakash** [weecology/retriever#926]
Based on the recent comments by @henrykironde on #922 , I think some of it needs updating, especially the part relating to the testing.

**Comment by henrykironde** [comment]
Thanks @goelakash, there are many changes that have taken place over the last period and we may have forgotten to keep track of some details. I will go through the docs and check for some updates required. Additionally, it would be helpful if you provide more information on the errors. Or point out some things that are not clear.

**Comment by henrykironde** [comment]
We have updated the test documentation over time.  I have not seen the recent user having any more trouble when it comes to tests and setting up the test environment. Thanks @goelakash.
