### ISSUE TITLE
Pre-commit hook preventing new script additions?

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#927]
I've been in the process of cleaning up #821 and am running into an issue with the pre-commit hook:

```
ethan@gandalf:~/RetrieverCode (pr/821 *+)$ git commit --amend 
remote: Counting objects: 11, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 11 (delta 8), reused 11 (delta 8), pack-reused 0
Unpacking objects: 100% (11/11), done.
From https://github.com/weecology/retriever
 * branch            master     -> FETCH_HEAD
Traceback (most recent call last):
  File ".git/hooks/pre-commit", line 62, in <module>
    if not script_current_version > get_script_version(file):
  File ".git/hooks/pre-commit", line 35, in get_script_version
    return LooseVersion(version_dict[file_name])
KeyError: 'predicts.py'
```

I haven't looked into this, but a quick guess from the error message is that we may be looking up a version number for the script, but if it's a new script it isn't in the associated dictionary and so it errors.

**Comment by zhangcandrew** [comment]
So there's a part of our code where we check changes with a diff filter that looks for added and modified files but not deleted ones. I don't remember why I had it check to make sure we included added files in the git diff, but I made some comments to @henrykironde 's branch that should fix it up.

**Comment by zhangcandrew** [comment]
Looks like it's fixed for now. Closing the issue. Re-open if necessary
