### ISSUE TITLE
NYC TreesCount dataset does not run on python 3

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#961]
Error:
```
=> Installing nyc-tree-count

Downloading rows.csv...
cannot import name 'urlretrieve'
Done!
```

**Comment by ethanwhite** [comment]
This works properly for me on Python 3, Ubuntu 16.04.

**Comment by henrykironde** [comment]
I will do some tests to confirm.

**Comment by ethanwhite** [comment]
Just confirmed that this is working fine on another machine. Closing for now. Feel free to reopen if you can confirm and provide some more specific system details so we can figure out what's going on.
