### ISSUE TITLE
Add GDP data

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#967]
There is a data package here: https://github.com/datasets/gdp

The raw data is at: http://api.worldbank.org/indicator/NY.GDP.MKTP.CD?format=csv

**Comment by ethanwhite** [comment]
Could be addressed using #980.

**Comment by shreyneil** [comment]
@ethanwhite sir , where is the citation for this dataset available?

**Comment by henrykironde** [comment]
This does not have a citation.
