### ISSUE TITLE
Add ability to use existing data packages

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#968]
We use Frictionless data's data package standard. One of the advantages of this is that we should be able to use any existing packages directly. This would let us easily support a large number of new datasets. Functionality would include:

* Store a list of data package locations, probably in a single file
* For each location download the data package
* Automatically place the csv files in the correct locations
* Automatically place the the json file in the `scripts` directory and make any necessary modifications to it

Here are a bunch of existing data packages that this can be tested on and that we could quickly incorporate:

https://github.com/datasets

**Comment by henrykironde** [comment]
Thats great, amazing work

**Comment by ethanwhite** [comment]
FYI - I've started work on this. Others are more than welcome to help, but ping me if you're interested so I can get what I've done up onto a branch.

**Comment by henrykironde** [comment]
Adding this to #1574
