### ISSUE TITLE
List scritps by tags / keywords

### ISSUE THREAD

**Issue by ShivamNegi** [weecology/retriever#969]
This is an issue for `python-interface2` branch raised in #954 
The datasets function doesn't deal with the `-l` parameter which is a feature of the CLI. I propose on adding a separate parameter for `-l` functionality. Something like:
```python
def datasets(arg_keyword=None)
```
Which could be used like
```python
import retriever as rt
rt.datasets("birds")
```
Output:
```
['antarctic-breed-bird',
 'bird-migration-data',
 'bird-size',
 'elton-traits',
 'home-ranges']
```

**Comment by ShivamNegi** [comment]
There still remains a need for detailed description of the scripts. This function isn't meant to handle such a case. We could add a verbose parameter in the `datasets` function and add in that functionality as well.

**Comment by henrykironde** [comment]
`def datasets(arg_keyword=None) looks good`

**Comment by ethanwhite** [comment]
It would be nice to support license based searches as well.

**Comment by ethanwhite** [comment]
See also #1029
