### ISSUE TITLE
Use Frictionless data spec for types

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#981]
Our usage of `type` doesn't not currently match [the spec](https://specs.frictionlessdata.io/table-schema/#types-and-formats). This will require some changes to `lib/engine.py` and to the individual engines, probably with some care given to supporting both our old usage and the proper spec to maintain backwards compatibility.

Needed for #980.

**Comment by henrykironde** [comment]
We handled this and more specification to ingest such data is in the PR https://github.com/weecology/retriever/pull/1420
