### ISSUE TITLE
Add ND gain data set 

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever#988]
The ND-GAIN Country Index is a project of the University of Notre Dame Global Adaptation Initiative (ND-GAIN).
The index summarizes a country's vulnerability to climate change and other global challenges in combination with its readiness to improve resilience.
ref: http://index.gain.org/

Download data from: http://index.gain.org/about/download

**Comment by adhaamehab** [comment]
Hi @henrykironde .
Can I work on this one ? 
Could you provide me with some information/resources about how retriever store the datasets so I can get this issue done ?

**Comment by henrykironde** [comment]
http://retriever.readthedocs.io/en/latest/scripts.html

**Comment by shreyneil** [comment]
@henrykironde  is there any direct download link related to this data?

**Comment by ethanwhite** [comment]
@shreyneil - looks like this might be it http://gain.nd.edu/assets/256365/resources_2017_03_10_14h04.zip

**Comment by shreyneil** [comment]
Thanx sir, but i think this  https://gain-new.crc.nd.edu/assets/gain/files/resources-2017-03-10-14h04.zip  a more appropriate link as i was getting errors with the previous link.

**Comment by shreyneil** [comment]
@henrykironde it would be great if you could close this.

**Comment by ethanwhite** [comment]
Thanks @shreyneil.
