### ISSUE TITLE
Changing to Read the Docs: sphinx_rtd_theme

### ISSUE THREAD

**Issue by ShivamNegi** [weecology/retriever#994]
I really like this [sphinx theme](http://deeplearning.net/software/theano/index.html). I propose to update our docs to this theme. I am ready to take this up if everyone approves. The repository of the theme is here: [sphinx_rtd_theme](https://github.com/rtfd/sphinx_rtd_theme).

**Comment by ethanwhite** [comment]
:+1:

**Comment by henrykironde** [comment]
I prefer the old classic one  :smile: though it looks outdated.
Having said that, I look forward to having a new theme. :+1:

**Comment by ethanwhite** [comment]
Complete in #1027. Thanks again @ShivamNegi!
